### ISSUE TITLE
Availability of aws-serverless-java-container jar

### ISSUE THREAD

**Issue by przemos** [awslabs/aws-serverless-java-container#1]
Hi, 

can you let us know in which maven repository the artifact is deployed ?

Thanks,
Przemek

**Comment by SAPessi** [comment]
Hi,

This is not submitted to a repo yet. For the time being you can just clone/download the repo to your workstation and run `mvn install`. As soon as we merge the spring-support branch we'll push the packages to a public repository.

Stefano

**Comment by przemos** [comment]
Cheers :)
I work around it by using by using https://jitpack.io/ temporarily.
Great job Stefano!

**Comment by SAPessi** [comment]
version 0.2 of the library is now on the maven repository, closing this,
