### ISSUE TITLE
Spring-Boot Lambda Petstore example is missing proxy.model why?

### ISSUE THREAD

**Issue by quantum-fusion** [awslabs/aws-serverless-java-container#101]
* Framework version: XX
* Implementations: Jersey / Spring / Spring Boot / Spark

## Scenario

cd $HOME/aws-serverless-java-container-master
mvn compile

## Expected behavior

The main project for server less was compiled which shows success.

The spring-boot project called pet-store was compiled, however shows that there are dependency errors while executing mvn compile.

------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] AWS Serverless Java container ...................... SUCCESS [  0.348 s]
[INFO] AWS Serverless Java container support - Core ....... SUCCESS [  0.553 s]
[INFO] AWS Serverless Java container support - Jersey implementation SUCCESS [  0.527 s]
[INFO] AWS Serverless Java container support - Spark implementation SUCCESS [  0.190 s]
[INFO] AWS Serverless Java container support - Spring implementation SUCCESS [  0.112 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.867 s
[INFO] Finished at: 2018-01-16T20:48:33-05:00
[INFO] Final Memory: 15M/440M
[INFO] ------------------------------------------------------------------------

## Actual behavior

Same.

## Steps to reproduce

cd samples/springboot/pet-store

mvn compile

## Full log output

[ERROR] /Users/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[6,44] package com.amazonaws.serverless.proxy.model does not exist
[ERROR] /Users/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[7,44] package com.amazonaws.serverless.proxy.model does not exist
[ERROR] /Users/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[21,46] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[21,63] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[5,44] package com.amazonaws.serverless.proxy.model does not exist
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[6,44] package com.amazonaws.serverless.proxy.model does not exist
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[21,46] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[21,63] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[37,9] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[37,99] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[37,57] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[39,9] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[41,31] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[39,9] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[39,65] cannot find symbol
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[41,9] cannot find symbol
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project serverless-spring-boot-example: Compilation failure: Compilation failure:
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[6,44] package com.amazonaws.serverless.proxy.model does not exist
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[7,44] package com.amazonaws.serverless.proxy.model does not exist
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[21,46] cannot find symbol
[ERROR] symbol:   class AwsProxyRequest
[ERROR] location: class com.amazonaws.serverless.sample.springboot.StreamLambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[21,63] cannot find symbol
[ERROR] symbol:   class AwsProxyResponse
[ERROR] location: class com.amazonaws.serverless.sample.springboot.StreamLambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[5,44] package com.amazonaws.serverless.proxy.model does not exist
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[6,44] package com.amazonaws.serverless.proxy.model does not exist
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[21,46] cannot find symbol
[ERROR] symbol:   class AwsProxyRequest
[ERROR] location: class com.amazonaws.serverless.sample.springboot.LambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[21,63] cannot find symbol
[ERROR] symbol:   class AwsProxyResponse
[ERROR] location: class com.amazonaws.serverless.sample.springboot.LambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[37,9] cannot find symbol
[ERROR] symbol:   class AwsProxyRequest
[ERROR] location: class com.amazonaws.serverless.sample.springboot.StreamLambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[37,99] cannot find symbol
[ERROR] symbol:   class AwsProxyRequest
[ERROR] location: class com.amazonaws.serverless.sample.springboot.StreamLambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[37,57] cannot find symbol
[ERROR] symbol:   method getObjectMapper()
[ERROR] location: class com.amazonaws.serverless.proxy.internal.LambdaContainerHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[39,9] cannot find symbol
[ERROR] symbol:   class AwsProxyResponse
[ERROR] location: class com.amazonaws.serverless.sample.springboot.StreamLambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/StreamLambdaHandler.java:[41,31] cannot find symbol
[ERROR] symbol:   method getObjectMapper()
[ERROR] location: class com.amazonaws.serverless.proxy.internal.LambdaContainerHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[39,9] cannot find symbol
[ERROR] symbol:   class AwsProxyRequest
[ERROR] location: class com.amazonaws.serverless.sample.springboot.LambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[39,65] cannot find symbol
[ERROR] symbol:   class AwsProxyRequest
[ERROR] location: class com.amazonaws.serverless.sample.springboot.LambdaHandler
[ERROR] /Users/hottelet/Desktop/aws-serverless-java-container-master/samples/springboot/pet-store/src/main/java/com/amazonaws/serverless/sample/springboot/LambdaHandler.java:[41,9] cannot find symbol
[ERROR] symbol:   class AwsProxyResponse
[ERROR] location: class com.amazonaws.serverless.sample.springboot.LambdaHandler

**Comment by quantum-fusion** [comment]
The issue is that proxy.model does not exist in this project.

Why are these dependencies missing?

**Comment by SAPessi** [comment]
Hey @quantum-fusion, We have done a bit of refactoring in the repo preparing for the 0.1 release. For the latest version of the samples to work (cloned from this repo), you will also have to install the 0.9-SNAPSHOT version of the library here. Run `mvn install` in the root of the cloned repository and then try to re-build the sample. Once 0.9 official is published on maven central the issue will go away

**Comment by quantum-fusion** [comment]
see issue 103.

**Comment by quantum-fusion** [comment]
I will try your suggestions, however I was able to root-cause the issue, see issue 103.

**Comment by SAPessi** [comment]
Provided full instructions in #103.
