### ISSUE TITLE
Stack tace error returned when incorrect body is provided for POST request

### ISSUE THREAD

**Issue by alepeltier** [awslabs/aws-serverless-java-container#102]
* Framework version: 0.8
* Implementations: Jersey / Jackson

I'm using aws-serverless-java-container to run a lambda which handles POST requests passed through a proxy in API Gateway. 

When I supply an incorrect body to the API I get an error message back with the full stack trace of the application. I thought that this might be thrown in the lambda handler but when trying to debug it I can't narrow down where the exception is being thrown.

Do you have any idea where this error is being thrown so I can catch it and return a sensible error which doesn't display the stack trace of the application?

The error I get returned looks like this:

Unrecognized field "Test" (class XXXX.XXXX.XXXX.XXXX.XXXX.XXXX), not marked as ignorable (2 known properties: "test1", "test"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@442ab112; line: 3, column: 16] (through reference chain: XXXX.XXXX.XXXX.XXXXX.XXXX.XXXX["XXXXX"]->XXXX.XXX.XXX.XXXX.XXXX.XXXX["Test"])

**Comment by SAPessi** [comment]
Hi @alepeltier, are you using a POJO handler or a Stream handler for your Lambda function? Any chance you can post the full stack trace of the exception? To confirm, you see the stack trace in the body of the response?

**Comment by alepeltier** [comment]
Hello @SAPessi 

The handler code is:

public class ApplicationHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {
    private ResourceConfig jerseyApplication = new ResourceConfig()
            .packages("XXX.XXX")
            .property(ServerProperties.BV_SEND_ERROR_IN_RESPONSE, true)
            .property(ServerProperties.BV_DISABLE_VALIDATE_ON_EXECUTABLE_OVERRIDE_CHECK, true)
            .register(JacksonFeature.class)
            .register(TachonetResponse.class)
            .register(ValidationExceptionMapper.class)
            .register(ValidationConfigurationContextResolver.class);

    private JerseyLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler
            = JerseyLambdaContainerHandler.getAwsProxyHandler(jerseyApplication);

    /**
     * This lambda function doesn't call any methods it instead calls the jersey config which determines which methods
     * will be called.
     *
     * @param awsProxyRequest AwsProxyRequest
     * @param context         Context
     * @return JerseyLambdaContainerHandler
     */
    @Override
    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        return handler.proxy(awsProxyRequest, context);
    }
}

I can send you the stack trace in a private message however I'd rather not post it on here as it is a sensitive system.

**Comment by alepeltier** [comment]
Just to clarify that response I posted in my original message is what’s displayed in postman and returned when the API is called.

**Comment by SAPessi** [comment]
If you can clean up the stack trace, I'm only interested in the lines that are relevant to aws-serverless-java-container.

Off the top of my head, it looks like the framework is receiving a response from Jersey that already contains the exception, so it's treating it as a valid response. Is your ValidationExceptionMapper trapping this? Is it called at all? What does it generate in the toResponse method()?

**Comment by SAPessi** [comment]
Let me know if you get anywhere with this @alepeltier. 

What's suspicious to me is that the library includes its own "safety" [exception handler](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/AwsProxyExceptionHandler.java) that should hide any stack trace and simply return 500s or 502s depending on the exception. We have included this to avoid exposing any stack traces of confidential info. The main [`proxy` method](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java#L132) catches all `Exception` and passes them through the handler. 

Since you see the stack trace in the response, I suspect the exception does not bubble up all the way to the library, instead it's handled by Jersey somewhere which then returns a valid response (with the stack trace in the body)

**Comment by alepeltier** [comment]
@SAPessi  I think it's been narrowed down to the @JsonProperty tags being used in the model. Thanks for the advise I'll let you know if we still have the issue.

**Comment by SAPessi** [comment]
@alepeltier I think you have two separate issues: First, the application is throwing an exception when it receives a model it doesn't recognize. Second, the exception is bubbling up all the way to the client.

The first one, is not necessarily bad behavior. Think of it as a form of validation, if the request model is not valid, the request fails - why not? makes sense to me. If you wanted to make it work regardless. You can either use the `@JsonIgnoreProperties(ignoreUnknown = true)` annotation on the class just like I do [here](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/CognitoAuthorizerClaims.java#L43). Alternatively, you could use the `@JsonAnySetter` and getter annotations to catch all unknown fields and store them in a map, just like I do [here](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/CognitoAuthorizerClaims.java#L82).

The big issue here is that the exception is bubbling up. To solve that, we should start investigating the `ExceptionMapper`.

Hopefully this was helpful. Let me know how you get on.

**Comment by alepeltier** [comment]
@SAPessi  you were correct the issue was being thrown by the ExceptionMapper.

I've managed to fix it by creating the following class

`
@Provider
public class JsonMappingExceptionMapper implements ExceptionMapper<JsonMappingException> {
    @Override
    public Response toResponse(JsonMappingException exception) {
        return Response.status(Response.Status.BAD_REQUEST).build();
    }
}
`

Thank you for all your help this is now nicely hiding the stack trace
