### ISSUE TITLE
Spring-Boot pet store missing pom.xml dependencies for com.amazonaws.serverless.sample.springboot.StreamLambdaHandler.java

### ISSUE THREAD

**Issue by quantum-fusion** [awslabs/aws-serverless-java-container#103]
The problem is that mvn package results is missing dependencies for the com.amazonaws.serverless.sample.springboot.StreamLambdaHandler.java 

These are the dependencies that are missing:

import com.amazonaws.serverless.exceptions.ContainerInitializationException;
import com.amazonaws.serverless.proxy.internal.LambdaContainerHandler;
import com.amazonaws.serverless.proxy.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler;

The root cause of the issue, is that the pom.xml file is loading the wrong project, and it needs to be corrected:
https://github.com/awslabs/aws-serverless-java-container/blob/06756285a14c3917a1799c85213d0c4c9fdb449f/samples/springboot/pet-store/pom.xml#L25

Please fix, so that the spring-boot pet store example can be in an executable and compilable state, by issuing mvn package.

**Comment by SAPessi** [comment]
The pom.xml is configured to load the latest version available - that's what the [) parenthesis mean. It would load 0.9-SNAPSHOT if you `mvn install` it on your machine.

The process is:
```bash
$ git clone git@github.com:awslabs/aws-serverless-java-container.git
$ cd aws-serverless-java-container
$ mvn clean install
$ cd samples/springboot/pet-store
$ mvn package
```

**Comment by quantum-fusion** [comment]
The process is: 

$ git clone git://github.com/awslabs/aws-serverless-java-container.git
$ cd aws-serverless-java-container/
$ mvn clean install
$ cd samples/springboot/pet-store
$ mvn package

Results: /pet-store/target/serverless-spring-boot-example-1.0-SNAPSHOT-shaded.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.744 s
[INFO] Finished at: 2018-01-17T11:56:54-05:00
[INFO] Final Memory: 61M/369M
[INFO] ------------------------------------------------------------------------

**Comment by quantum-fusion** [comment]
I would recommend adding these instructions to your README.txt on the Wiki.
