### ISSUE TITLE
Make it compatible with Jersei 2.26

### ISSUE THREAD

**Issue by feinstein** [awslabs/aws-serverless-java-container#108]
It would be nice if the Jersey version could be bumped to `2.26`.

**Comment by SAPessi** [comment]
I'm working on this for the next release. Already tracking in #95 - I'm going to close this issue for now.

**Comment by feinstein** [comment]
Oh, great, I just updated from 0.8 and I thought I remembered 0.9 would accept Jersey 2.26. Thanks.

**Comment by SAPessi** [comment]
0.9 is still running the older version. I will push 2.26 for version 1.0 - I was running into too many issues and needed 0.9 to go out.

**Comment by feinstein** [comment]
Great, thanks!
