### ISSUE TITLE
Static or No-Static Handler?

### ISSUE THREAD

**Issue by feinstein** [awslabs/aws-serverless-java-container#109]
The documentation [here](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Jersey) says:

>The handler object should be declared as a class property and be static. By doing this, Lambda will re-use the instance for subsequent requests.

But the code sample just below the text doesn't have the `static` modifier. Why? Should `handler` be static or not?

**Comment by SAPessi** [comment]
I'll clean up the documentation. The point I need to make is that the handler should be declared as member variables in your handler class. The Lambda runtime initializes your handler as a singleton and keeps re-using the same object to handle subsequent events - given this behavior, having the handler as a member variables allows us to re-use the same handler across multiple events.

**Comment by feinstein** [comment]
That's good to be on the documentations as well.

**Comment by SAPessi** [comment]
Updated samples and doc is ready for next release. resolving.
