### ISSUE TITLE
Recomendations for Better Cold Start Performance

### ISSUE THREAD

**Issue by feinstein** [awslabs/aws-serverless-java-container#110]
Are there any recommendations for better Cold Start performance?

I have a very simple Jersey application, my jar package is 10MB, it's 3 REST Resources, all of them small, I have only logging and DB libraries (MySQL Driver and HikariCP), no VPC, and I am getting around **10s cold start times**, but 200ms hot-start execution times. 

Are there any ways to optimize this?

**Comment by SAPessi** [comment]
* More memory = more CPU - the minimum amount of memory I'd recommend for a Java function is 512MB, try and go even higher to see what you achieve
* Instead of pointing ResourceConfig to a package, register exactly the classes you need

I'll create a docs page with these tips.

**Comment by feinstein** [comment]
I will try to point the classes themselves, I am already at 512mb machine, I don't want to increase the costs higher than that.

**Comment by SAPessi** [comment]
Updated docs to recommend static handlers and samples. All changed in the `next-release` branch of docs and `core` branch of the codebase. Closing this issue.
