### ISSUE TITLE
requestId always returns value "test-invoke-request"

### ISSUE THREAD

**Issue by thallium205** [awslabs/aws-serverless-java-container#125]
* Framework version: 0.9.1
* Implementations: Spring

## Scenario
Pulling the requestId value from the request payload at: `((AwsProxyHttpServletRequest) request).getAwsProxyRequest().getRequestContext().getRequestId()`.

## Expected behavior
The value of this should be the UUID that is generated from API gateway as described here under "Input Format of a Lambda Function for Proxy Integration" -> https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format

## Actual behavior
Instead, the requestId in the requestContext of the response is returning a string constant of "test-invoke-request".  

## Steps to reproduce
Make a call to your lambda function through API gateway and read the value of requestId in the proxyRequest object.

**Comment by SAPessi** [comment]
hey @thallium205, that request id is set by the AwsProxyRequestBuilder used in the unit tests for the framework: https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java#L69

Are you saying we should set a valid UUID for the unit tests?

**Comment by SAPessi** [comment]
I think I know what's going on. API Gateway also automatically sends the `test-invoke-request` value for `requestId` when you use the test interface from the console - you can see it in the logs generated on the right on the `Endpoint request body after transformations:` line. Are you testing using the console or calling an API that is actually deployed?

```
"stage":"test-invoke-stage",
"requestId":"test-invoke-request"
```

**Comment by thallium205** [comment]
Argh!  You're absolutely correct: when using the API Gateway's "Method Test" feature, it will include that constant as the requestId as revealed in the generated logs.  However, when hitting the endpoint using the invocation URL (through curl, for example), it generates the expected UUID requestId.
Sorry about this report... it is clearly not an issue with this library.  Thanks.
