### ISSUE TITLE
Can't build project well due to lack of jars  in sonatype-nexus-snapshots

### ISSUE THREAD

**Issue by humank** [awslabs/aws-serverless-java-container#129]
* Framework version: 1.0
* Implementations: Spark

## Scenario
I'm just update this project from v0.9 to v1.0 at 2018/03/01, and encountered a build error due to lack of artifact com.amazonaws.serverless:aws-serverless-java-container-core:jar:1.1-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
## Expected behavior
while running the followig command it should be  done without other errors.

1. mvn clean
2. mvn package

## Actual behavior
Get the error message : 
[ERROR] Failed to execute goal on project aws-serverless-java-container-spark: Could not resolve dependencies for project com.amazonaws.serverless:aws-serverless-java-container-spark:jar:1.1-SNAPSHOT: Could not find artifact com.amazonaws.serverless:aws-serverless-java-container-core:jar:1.1-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
## Steps to reproduce
You can just to clone current version project, and run with maven commands to package project, then it's reproduced.
## Full log output

```
 ~/git/awslabs/aws-serverless-java-container/aws-serverless-java-container-spark   master  mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AWS Serverless Java container support - Spark implementation 1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.amazonaws.serverless:aws-serverless-java-container-core:jar:1.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.569 s
[INFO] Finished at: 2018-03-01T10:19:38+08:00
[INFO] Final Memory: 9M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aws-serverless-java-container-spark: Could not resolve dependencies for project com.amazonaws.serverless:aws-serverless-java-container-spark:jar:1.1-SNAPSHOT: Failure to find com.amazonaws.serverless:aws-serverless-java-container-core:jar:1.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

**Comment by SAPessi** [comment]
1.1-SNAPSHOT is only available in the GitHub repo. 1.0 is the published. Add your dependency to version 1.0.

**Comment by SAPessi** [comment]
Never mind, think I understand what you are doing now. to package the project you need to run mvn package from the root, not inside the spark directory. All modules depend on each other. To make 1.1-SNAPSHOT available in your local repository, use `mvn install`, not package:

```bash
$ git clone https://github.com/awslabs/aws-serverless-java-container.git
$ cd aws-serverless-java-container
$ mvn install
```

**Comment by humank** [comment]
Thanks @SAPessi !
