### ISSUE TITLE
Function returned an invalid response

### ISSUE THREAD

**Issue by sebastientromp** [awslabs/aws-serverless-java-container#134]
* Framework version: 1.0
* Implementations: Spring Boot

## Scenario

* I created the archetype using 
```
 mvn archetype:generate -DgroupId=my.service -DartifactId=my-service -Dversion=1.0-SNAPSHOT        -DarchetypeGroupId=com.amazonaws.serverless.archetypes  \
      -DarchetypeArtifactId=aws-serverless-springboot-archetype \
      -DarchetypeVersion=1.0.1
```
* I run `mvn package`
* Then started sam using `sam local start-api --template sam.yaml` with output
```
2018/03/11 15:12:19 Connected to Docker 1.35
2018/03/11 15:12:19 Fetching lambci/lambda:java8 image for java8 runtime...
java8: Pulling from lambci/lambda
Digest: sha256:c2ec8db145bbe44154dbddcdd2976ab8afd60d58d7d633dc98f53f657c0ef909
Status: Image is up to date for lambci/lambda:java8

Mounting my.service.StreamLambdaHandler::handleRequest (java8) at http://127.0.0.1:3000/{proxy+} [OPTIONS GET HEAD POST PUT DELETE PATCH]

You can now browse to the above endpoints to invoke your functions.
You do not need to restart/reload SAM CLI while working on your functions,
changes will be reflected instantly/automatically. You only need to restart
SAM CLI if you update your AWS SAM template.
```
* Then tried to call the /ping endpoint at `curl -s http://127.0.0.1:3000/ping | python -m json.tool`

## Expected behavior

The server replies with a "pong" message

## Actual behavior

```
2018/03/11 15:12:46 Invoking my.service.StreamLambdaHandler::handleRequest (java8)
2018/03/11 15:12:46 Decompressing G:\Source\lambdas\my-service\target\my-service-1.0-SNAPSHOT.jar
2018/03/11 15:13:49 Mounting /c/Users/Daedin/AppData/Local/Temp/aws-sam-local-1520777566162251000 as /var/task:ro inside runtime container
START RequestId: 48dfc4ef-52c7-4674-8bf3-1853e7e8f4d4 Version: $LATEST
END RequestId: 48dfc4ef-52c7-4674-8bf3-1853e7e8f4d4
REPORT RequestId: 48dfc4ef-52c7-4674-8bf3-1853e7e8f4d4  Duration: 9083.56 ms    Billed Duration: 9100 ms        Memory Size: 512 MB     Max Memory Used: 15 MB
2018/03/11 15:14:01 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): invalid character '-' after top-level value
```

which results in an Internal Server Error

## Steps to reproduce

See description

## Full log output

```
$ sam local start-api --template sam.yaml
2018/03/11 15:12:19 Connected to Docker 1.35
2018/03/11 15:12:19 Fetching lambci/lambda:java8 image for java8 runtime...
java8: Pulling from lambci/lambda
Digest: sha256:c2ec8db145bbe44154dbddcdd2976ab8afd60d58d7d633dc98f53f657c0ef909
Status: Image is up to date for lambci/lambda:java8

Mounting my.service.StreamLambdaHandler::handleRequest (java8) at http://127.0.0.1:3000/{proxy+} [OPTIONS GET HEAD POST PUT DELETE PATCH]

You can now browse to the above endpoints to invoke your functions.
You do not need to restart/reload SAM CLI while working on your functions,
changes will be reflected instantly/automatically. You only need to restart
SAM CLI if you update your AWS SAM template.

2018/03/11 15:12:46 Invoking my.service.StreamLambdaHandler::handleRequest (java8)
2018/03/11 15:12:46 Decompressing G:\Source\lambdas\my-service\target\my-service-1.0-SNAPSHOT.jar
2018/03/11 15:13:49 Mounting /c/Users/Daedin/AppData/Local/Temp/aws-sam-local-1520777566162251000 as /var/task:ro inside runtime container
START RequestId: 48dfc4ef-52c7-4674-8bf3-1853e7e8f4d4 Version: $LATEST
END RequestId: 48dfc4ef-52c7-4674-8bf3-1853e7e8f4d4
REPORT RequestId: 48dfc4ef-52c7-4674-8bf3-1853e7e8f4d4  Duration: 9083.56 ms    Billed Duration: 9100 ms        Memory Size: 512 MB     Max Memory Used: 15 MB
2018/03/11 15:14:01 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): invalid character '-' after top-level value
```

**Comment by SAPessi** [comment]
I'm looking into this and trying to replicate. I'll update here as soon as I figure out what's going on.

**Comment by SAPessi** [comment]
hey @sebastientromp, The archetype works fine when deployed in Lambda. However, it breaks with SAM local. I suspect this has something to do with how SAM local reads the function output - it expects as the last message in the stdout. Spring Boot logs a lot of messages at boot and adds a shutdown message after the output is printed out. I thought [this line](https://github.com/awslabs/aws-serverless-java-container/blob/master/archetypes/springboot/src/main/resources/archetype-resources/src/main/java/Application.java#L30) was enough to switch off logging from Spring Boot, at least it was in the previous release. I'll do some more digging to figure out how to disable the spring boot logs.

**Comment by SAPessi** [comment]
Ok @sebastientromp, I figured out how to fix this for SAM local. Under `/src/main`, create a `resources` folder and put a new `application.properties` file in there. In the properties file we simply tell SpringBoot to turn off its logging (setting it to WARN may be enough).

```properties
logging.level.root=OFF
```
![screen shot 2018-03-12 at 9 23 25 am](https://user-images.githubusercontent.com/2996317/37296095-27089874-25d7-11e8-9c57-62341b7a049f.png)

I'll keep this issue open to track the update of the archetype. I'll have this included in the next release.

**Comment by rafehi** [comment]
Also ran into a variant of this issue. Running a clean checkout of the aws sample works fine, however as soon as you remove `logback.xml` (which sets the log level to ERROR), it fails with the same error. Creating the `application.properties` file with the `logging.level.root=OFF` (as mentioned by @SAPessi ) also fixes it in this scenario.

**Comment by rafehi** [comment]
The following configuration in `application.properties` also works (only disables logging for the two packages that print at shutdown):

```
logging.level.org.springframework.jmx=ERROR
logging.level.org.springframework.boot.web.servlet=ERROR
```

**Comment by SAPessi** [comment]
Thanks @rafehi - I'll include this in the archetypes and samples for the next release

**Comment by SAPessi** [comment]
The fix for this is included in the latest merge. Closing the issue

**Comment by sebastientromp** [comment]
Thanks! I'm just right now getting back to serverless, your help is much appreciated :)

> Thanks @rafehi - I'll include this in the archetypes and samples for the next release

The doc already mentions archetype version 1.1, but it doesn't seem to exist yet. Am I correct?
I'll work with manual modifications in the meantime

Cheers!

**Comment by SAPessi** [comment]
Hey @sebastientromp, I can see the archetypes in [maven central](https://search.maven.org/#search%7Cga%7C1%7Ccom.amazonaws.serverless.archetypes). What error are you getting?

**Comment by sebastientromp** [comment]
Indeed, it works well. I must have made a typo when typing the commands.

Sorry for the noise, and thanks for the help!
