### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mattcorey** [awslabs/aws-serverless-java-container#14]
Any way we can get a new release with the recent changes?  Are there any other roadmap items you have in mind for this library?

**Comment by SAPessi** [comment]
Yes, we will push 0.3 out now (latest early next week). I have some clean up and refactoring to do but otherwise features are driven by requests here. If there is something else you'd like to see in the library let us know and we'll get right to it.

**Comment by SAPessi** [comment]
Version 0.3 is now on maven central. Closing this issue. Feel free to open another issue if you come up with other features you'd like in the library
