### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by SAPessi** [awslabs/aws-serverless-java-container#142]
* Framework version: 1.0.1
* Implementations: Jersey / Spring / Spring Boot / Spark

* Add initialize() method and move framework initialization to it. By default the initialize method should be called by the static `getAwsProxyHandler()`
* Move initialization of `ObjectReader` and `ObjectWriter` to the constructor of `LambdaContainerHandler`

**Comment by SAPessi** [comment]
Both of these are addressed

**Comment by cloud9aws** [comment]
@SAPessi Thanks for bringing in the performance improvements by 1.1. release. Is there a benchmark testing to show mow much it reduce the cold start time, to what degree ?
