### ISSUE TITLE
APIGateway Stage in spring boot lambda handler

### ISSUE THREAD

**Issue by ktamilvanan** [awslabs/aws-serverless-java-container#148]
I am using the SpringBootLambdaContainerHandler as given in the example

```
public class StreamLambdaHandler implements RequestStreamHandler {
    private static SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;

    static {
        try {
            handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class);

        } catch (ContainerInitializationException e) {
            // if we fail here. We re-throw the exception to force another cold start
            log.error("Exception occured proxying to spring boot ",e);
            throw new RuntimeException("Could not initialize Spring Boot application", e);
        }
    }

    public StreamLambdaHandler() {
        // we enable the timer for debugging. This SHOULD NOT be enabled in production.
//        Timer.enable();
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException {
        handler.proxyStream(inputStream, outputStream, context);

        // just in case it wasn't closed by the mapper
        outputStream.close();
    }

}
```
I understand that I can user handler.activateSpringProfiles("profile"). I would like to use the api gateway stage and activate the corresponding profile. Can someone provide an example of how to retrieve the stage from the request. When i try to read the inputstream, 

> com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input

error is thrown on the aws lambda. 

Thanks.

**Comment by SAPessi** [comment]
Hi @ktamilvanan, apologies for the delay. The stage is available in the API Gateway context. The context object is included in the servlet request as [an attribute](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java#L38). From your application's request handlers, you can inject the servlet request and retrieve the context object with the `getAttribute(API_GATEWAY_CONTEXT_PROPERTY)` method. 

One warning on this. To activate a different profile the framework will have to re-initialize the spring application, which means you will have a double cold start. I would rather deploy multiple copies of the Lambda function, one per stage, and set the stage in an environment variable. This way you can initialize it only once for the correct stage.

**Comment by ktamilvanan** [comment]
@SAPessi Thanks for the reply. We will be deploying multiple copies of the lambda for different stages. But we wanted to get the profile from the api gateway context. Will update when i have this working.

**Comment by SAPessi** [comment]
Resolving since I haven't heard back in a while.

**Comment by mohit224** [comment]
Is there a working example I can refer to on how to activate Spring Profile using API Gateway stages? I tried using the stageVariable but not able to pull the value in my handler. 

`public class StreamLambdaHandler implements RequestStreamHandler {
	private static SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
	static {
		try {
			handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class);
		} catch (ContainerInitializationException e) {
			// if we fail here. We re-throw the exception to force another cold start
			e.printStackTrace();
			throw new RuntimeException("Could not initialize Spring Boot application", e);
		}
	}

	@Override
	public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException {
               // This is printing as null
		System.out.println(
				"*****stage value::: " + handler.getServletContext().getAttribute("API_GATEWAY_CONTEXT_PROPERTY"));
                // This is printing as blank
		System.out.println("*****context path value::: " + handler.getServletContext().getContextPath());
	      // This is printing as blank	
              System.out.println("*****stage variables ::: "
				+ handler.getServletContext().getAttribute("API_GATEWAY_STAGE_VARS_PROPERTY"));
		handler.proxyStream(inputStream, outputStream, context);

	}
}`

Also is this still a correct way to set the spring profile or is there a better way to pass the stage variable from API Gateway to set the spring profile. 
@sapessi  Could you please let me know?

**Comment by sapessi** [comment]
Hi @mohit224, you can [use `activateSpringProfiles` method](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-springboot2/src/main/java/com/amazonaws/serverless/proxy/spring/SpringBootLambdaContainerHandler.java#L153) of the container handler object from the `handleRequest` method.

Keep in mind that using it will trigger a cold start of the application inside the `handleRequest` method - which will be slow. To learn more, I [gave a talk at re:Invent about this](https://www.youtube.com/watch?v=ddg1u5HLwg8&t=1s).

**Comment by mohit224** [comment]
thanks for the quick response @sapessi. I will go through your talk and I did saw your comment about the cold start issue on this, thought you came up with any new approach as I guess it would be cool if we can somehow set the spring profile using the stage. But can you also tell me how to retrieve the stage variable using the above approach. 
I did tried using the activeSpringProfiles directly but I was getting below error in the lambda: 
Here is my habdler code: 
`@Override
	public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException {
		handler.activateSpringProfiles("prod");
		handler.proxyStream(inputStream, outputStream, context);

	}`

The error I am seeing in cloud watch after above configuration: 

2020-06-12T11:32:41.443-05:00 | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.IllegalStateException: No ServletContext set
-- | --
