### ISSUE TITLE
Built in support for Struts2 based lambda functions

### ISSUE THREAD

**Issue by jogep** [awslabs/aws-serverless-java-container#149]
* Framework version: 2.5.16
* Implementations: Struts2

## Scenario
I created a similar Struts2 Handler like for Spring based Lambdas. This functionality could mayby directly included into this project?

Struts2 Plugin:
https://github.com/struts-community-plugins/struts2-cloud-support/tree/master/struts2-aws-lambda-support-plugin

Struts2 Lambda Handler Implementation:
https://github.com/struts-community-plugins/struts2-cloud-support/tree/master/struts2-aws-lambda-support-plugin/src/main/java/org/apache/struts2/aws/lambda/support/handler

## Expected behavior
Support Struts2 as well.

## Actual behavior
Only Jersey and Spring are supported.

**Comment by SAPessi** [comment]
Hi @jogep - looks really good. We'd be happy to include this in the framework to give official Struts2 support. Can you update it to work with the latest version of the framework and send us a pull request. We can do code review and request changes in the pull request.

**Comment by jogep** [comment]
Hi @SAPessi , I created the PR for this feature request.

https://github.com/awslabs/aws-serverless-java-container/pull/159

**Comment by SAPessi** [comment]
Merged in core branch. Resolving.
