### ISSUE TITLE
Extract lambda environment variables

### ISSUE THREAD

**Issue by dotekien** [awslabs/aws-serverless-java-container#152]
* Framework version: 1.1
* Implementations: Jersey / Spring / Spring Boot / Spark

## Scenario
Extract lambda environment variables. For example:
--environment Variables={S3_BUCKET=Test}

## Expected behavior
get the map <variable_Name, variable_Value>

## Actual behavior
There is not support right now

**Comment by SAPessi** [comment]
Hey @dotekien, this framework does not touch the environment variables at all. Lambda sets them as variables in the OS when it starts your process. You need to read them using the standard Java syntax: 

````java
Map<String, String> env = System.getenv();

**Comment by dotekien** [comment]
You are right. 
I think it is related to the SAM cli issue which does not allow to have custom variable name. 
If I put DEPLOY_ENV in either env.json or in template.yaml, it is unable to find it via System.getenv()
