### ISSUE TITLE
Requests hanling clarification with lambda Context

### ISSUE THREAD

**Issue by nikita-clearscale** [awslabs/aws-serverless-java-container#155]
Hello,

I have not found any documentation about `com.amazonaws.services.lambda.runtime.Context` usage.
For example what if it is needed to get rest of time lambda time:

    import com.amazonaws.services.lambda.runtime.Context

    @RestController
    @EnableWebMvc
    public class PetsController {
        @RequestMapping(path = "/pets", method = RequestMethod.POST)
        public void createPet() {
            Context lambdaContext = // ???
            if (lambdaContext.getRemainingTimeInMillis > 60*1000) {
                doSomeLongWork();
            }
        }
    }

I have quickly examined code source but did not found any ways to get such context.

I have an idea to save it into some static variable during `handleRequest` method but this will lead to conflict between
lambda invocations. So `com.amazonaws.services.lambda.runtime.Context` have to be bound with request scope in spring,
but I have no idea how do this with you library :(

Could you please clarify `import com.amazonaws.services.lambda.runtime.Context` usage in documentation?

**Comment by SAPessi** [comment]
Hey @nikita-clearscale, the Lambda context, alongside the API Gateway context properties, is written as an attribute on the request. You can inject the `HttpServletRequest` as a parameter to your method and then use the `getAttribute` method. See the [`RequestReader`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java#L41).

I'll keep this issue open to make sure we update the documentation to include this.

**Comment by SAPessi** [comment]
@nikita-clearscale just noticed that this is discussed in the [documentation](https://github.com/awslabs/aws-serverless-java-container/wiki#security-and-api-gateway-context). Any suggestion on what we should do to make this more visible?

**Comment by sapessi** [comment]
Resolving this.
