### ISSUE TITLE
Problems with 403 Forbidden and 405 Method Not Allowed

### ISSUE THREAD

**Issue by davidmco65** [awslabs/aws-serverless-java-container#17]
Hi,
I'm having an issue trying to get a single Java Lambda to handle all HTTP Methods.

Here's my interface:

```
public interface ContactResource
{
	@DELETE
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	@Path("/{id}")
	public Response deleteContact(@PathParam("id") String id);

	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response createContact(ContactObject co);

	...
}
```

And my implementation class:

```
@Path("/contacts")
public class ContactResourceImpl implements ContactResource
{
	@Override
	public Response deleteContact(@PathParam("id") String id)
	{
		return deleteContact(id, null);
	}

	@Override
	public Response createContact(ContactObject co)
	{
		LOG.debug("Entering contacts::POST");
		try
		{
			...
		}
	}
}
```

Yet when I try to use Postman to call POST on /contacts (actually /TEST/contacts because TEST is my stage name), I get the 403 Forbidden error.

And when I try to use DELETE on /contacts/12345 - where I should receive a 404 Not Found because Contact with id 12345 doesn't exist - I get 405 Method Not Allowed.  I also get a return header of "Allow={GET,OPTIONS,PUT}".

Any help would be greatly appreciated!

Thanks,
David

**Comment by SAPessi** [comment]
Looking into it. Just to confirm, if you start this on your local machine using the embedded container in Jersey it responds correctly?

**Comment by SAPessi** [comment]
I've tried to test something similar in local with Jersey 2.24. Looks like you cannot define a method with a sub-path in the interface,  you have to define both in the implementation. Note that all of these tests are with the embedded Grizzly container in local. We'll get to Lambda and API Gateway next.

The DELETE method works for me when the interface is defined like this:
```java
public interface ContactResource
{
    @DELETE // you could skip this, it's here just for clarity
    @Consumes({MediaType.APPLICATION_JSON})
    @Produces({MediaType.APPLICATION_JSON})
    public Response deleteContact(String id);

    @POST
    @Consumes({MediaType.APPLICATION_JSON})
    @Produces({MediaType.APPLICATION_JSON})
    public Response createContact(Map<String, String> co);
}
```

And the implementation looks like this
```java
@Path("contacts")
public class ContactResourceImpl implements ContactResource {

    @DELETE
    @Path("{id}")
    public Response deleteContact(@PathParam("id") String id)
    {
        return Response.status(204).build();
    }

    public Response createContact(Map<String, String> co)
    {
        return Response.status(200).build();
    }
}
```

**Comment by davidmco65** [comment]
So when I define in both Interface and Implementation, I get Duplicate definition errors.  It thinks both the Interface and Implementation are definitions.

So I ran my JUnit tests, which I'm assuming fires up Grizzly.  All tests worked.  I've actually got more methods:



	@HEAD
	@Path("/ping")
	@Consumes({MediaType.APPLICATION_JSON})
	public Response ping(@QueryParam("numAdditionalInstancesToPing") int numAdditionalInstancesToPing);
	
	@DELETE
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	@Path("/{proxy}")
	public Response deleteContact(@PathParam("proxy") String id);

	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response createContact(ContactObject co);

	@PUT
	@Path("/{proxy}")
	@Produces({MediaType.APPLICATION_JSON})
	@Consumes({MediaType.APPLICATION_JSON})
	public Response updateContact(@PathParam("proxy") String id, ContactObject co);

	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public Response getByCustId(@QueryParam("cid") String cid);

	@GET
	@Path("/{proxy}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response getById(@PathParam("proxy") String id);

And it appears that all my tests work just fine.

Thanks,
David

**Comment by SAPessi** [comment]
Is there a repo where we can take a look at the entire app?

On the 1st question, 403 is normally returned by API Gateway when you try to open a method that is not defined in the API. Would be good to see the API Gateway definition.

**Comment by davidmco65** [comment]
Unfortunately, this is a private business app and I can't share all of the sources.  I can share more of the code around this resource with a little editing.
Here's the API definition:
![image](https://cloud.githubusercontent.com/assets/16906571/24153549/5e5fdc32-0e14-11e7-8e0e-653c73377eb2.png)

![image](https://cloud.githubusercontent.com/assets/16906571/24153574/778d4140-0e14-11e7-91e4-1ad4f6773716.png)

![image](https://cloud.githubusercontent.com/assets/16906571/24153599/899102be-0e14-11e7-92e6-448ef406b750.png)

Complete (scrubbed) Resource interface:
	package com.microstar.tap3.contact;

	import javax.ws.rs.Consumes;
	import javax.ws.rs.DELETE;
	import javax.ws.rs.GET;
	import javax.ws.rs.HEAD;
	import javax.ws.rs.POST;
	import javax.ws.rs.PUT;
	import javax.ws.rs.Path;
	import javax.ws.rs.PathParam;
	import javax.ws.rs.Produces;
	import javax.ws.rs.QueryParam;
	import javax.ws.rs.core.MediaType;
	import javax.ws.rs.core.Response;
	import com.microstar.tap3.contact.api.ContactObject;

	public interface ContactResource
	{

		/*
		 * Returns nothing; just serves to keep the Lambda warm.
		 * <p>
		 * This method always returns immediately with an 200 OK status and no body.
		 * 
		 * @return	200 OK status with no body.
		 */
		@HEAD
		@Path("/ping")
		@Consumes({MediaType.APPLICATION_JSON})
		public Response ping(@QueryParam("numAdditionalInstancesToPing") int numAdditionalInstancesToPing);
		
		@DELETE
		@Consumes({MediaType.APPLICATION_JSON})
		@Produces({MediaType.APPLICATION_JSON})
		@Path("/{proxy}")
		public Response deleteContact(@PathParam("proxy") String id);

		@POST
		@Consumes({MediaType.APPLICATION_JSON})
		@Produces({MediaType.APPLICATION_JSON})
		public Response createContact(ContactObject co);

		@PUT
		@Path("/{proxy}")
		@Produces({MediaType.APPLICATION_JSON})
		@Consumes({MediaType.APPLICATION_JSON})
		public Response updateContact(@PathParam("proxy") String id, ContactObject co);

		@GET
	//	@Path("/{cid}")
		@Produces({MediaType.APPLICATION_JSON})
		public Response getByCustId(@QueryParam("cid") String cid);

		@GET
		@Path("/{proxy}")
		@Produces({MediaType.APPLICATION_JSON})
		public Response getById(@PathParam("proxy") String id);

	}

And complete (scrubbed) Resource impl:
	package com.microstar.tap3.contact;

	import java.net.URI;
	import java.net.URISyntaxException;
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Set;

	import javax.persistence.EntityManager;
	import javax.persistence.RollbackException;
	import javax.persistence.criteria.CriteriaBuilder;
	import javax.ws.rs.Path;
	import javax.ws.rs.PathParam;
	import javax.ws.rs.QueryParam;
	import javax.ws.rs.client.Client;
	import javax.ws.rs.client.ClientBuilder;
	import javax.ws.rs.client.Invocation.Builder;
	import javax.ws.rs.client.WebTarget;
	import javax.ws.rs.core.MediaType;
	import javax.ws.rs.core.Response;
	import javax.ws.rs.core.Response.Status;

	import org.hibernate.Criteria;
	import org.hibernate.IdentifierLoadAccess;
	import org.hibernate.Session;
	import org.hibernate.SessionFactory;
	import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
	import org.hibernate.cfg.Configuration;
	import org.hibernate.criterion.Restrictions;
	import org.hibernate.query.Query;
	import org.hibernate.service.ServiceRegistry;

	import com.amazonaws.services.lambda.AWSLambdaClientBuilder;
	import com.amazonaws.services.lambda.invoke.LambdaInvokerFactory;
	import com.github.fluent.hibernate.cfg.scanner.EntityScanner;
	import com.microstar.tap3.api.BaseResourceImpl;
	import com.microstar.tap3.api.BasePingAPI;
	import com.microstar.tap3.contact.api.ContactObject;
	import com.microstar.tap3.contact.transform.ContactTransformer;
	import com.microstar.tap3.model.ContactType;
	import com.microstar.tap3.model.Address;
	import com.microstar.tap3.model.Contact;
	import com.microstar.tap3.model.Customer;
	import com.microstar.tap3.model.CustomerContactLink;
	import com.microstar.tap3.util.RestUtil;

	import org.slf4j.Logger;
	import org.slf4j.LoggerFactory;

	@Path("/contacts")
	public class ContactResourceImpl implements ContactResource
	{
		private static SessionFactory	tap3SessionFactory;
		private static ServiceRegistry	tap3ServiceRegistry;
		private static Session			tap3Session;
		private static final Logger 	LOG = LoggerFactory.getLogger(ContactResourceImpl.class);
		private static CriteriaBuilder	cb;
		private static EntityManager	em;
		
		static
		{
			LOG.info("Starting Static initializer...");
			if ( em != null )
			{
				LOG.info("Init:  Already initialized!");
			}
			else
			{
				LOG.info("Doing init()");
				Configuration tap3cfg = new Configuration()
						.addResource("hibernate.cfg.xml")
		//				.setProperty("hibernate.show_sql", "true")
		//				.setProperty("hibernate.format_sql", "true")
						;
				
				String dbName = System.getenv("DBname");
				String dbUser = System.getenv("DBuser");
				String dbPass = System.getenv("DBpass");
				
				LOG.info("Found DBname: " + dbName);
				LOG.info("Found DBuser: " + dbUser);
				
				LOG.info("Starting scanPackages...");
				EntityScanner.scanPackages("com.microstar.tap3.model").addTo(tap3cfg);
				LOG.info("Starting cfg.configure...");
				tap3cfg = tap3cfg.configure();
				LOG.info("Starting Registry.build...");
				tap3ServiceRegistry = new StandardServiceRegistryBuilder().applySettings(tap3cfg.getProperties())
						.build();
				LOG.info("Starting buildSessionFactory..");
				tap3SessionFactory = tap3cfg.buildSessionFactory(tap3ServiceRegistry);
				LOG.info("Starting openSession...");
				tap3Session = tap3SessionFactory.openSession();
				LOG.info("Starting createEM...");
				em = tap3Session.getEntityManagerFactory().createEntityManager();
				LOG.info("Starting getCriteriaBuilder...");
				cb = em.getCriteriaBuilder();
				LOG.info("Done.");
			}
			
			LOG.info("Exiting Static initializer...");

		}
		
		@Override
		public Response deleteContact(String id)
		{
			return deleteContact(id, null);
		}
		
		/* (non-Javadoc)
		 * @see com.microstar.tap3.contact.ContactResource#deleteContact(java.lang.String)
		 */
		public Response deleteContact(String id, String cid)
		{
			LOG.debug("Entering contacts::DELETE /" + id);
			try
			{
				// Find the Contact in the DB
				tap3Session.beginTransaction();
				IdentifierLoadAccess<Contact> ila = tap3Session.byId(Contact.class);
				Contact c = ila.getReference(id);

				if ( c == null )
				{
					LOG.debug("Exiting contacts::DELETE /" + id + ": NOT_FOUND");
					return Response
							.status(Status.NOT_FOUND)
							.build();
				}

				//
				// For some reason, getCustomerContactLinks doesn't return anything, even though there are linked instances.
				// Will do it manually, I guess.
				//
				
				@SuppressWarnings("deprecation")
				Criteria cclCrit = tap3Session.createCriteria(CustomerContactLink.class);
				cclCrit.add(Restrictions.eq("contact", c));
				@SuppressWarnings("unchecked")
				List<CustomerContactLink> ccls = (List<CustomerContactLink>) cclCrit.list();
				boolean updated = false;
				
				for ( CustomerContactLink ccl : ccls )
				{
					if ( cid != null )
					{
						if ( ccl.getCustomer().getTapcustomerId().equals(cid))
						{
							ccl.setDeleted(true);
							updated = true;
						}
					}
					else
					{
						ccl.setDeleted(true);
						updated = true;
					}
					
					if ( updated )
						tap3Session.update(ccl);
				}
				tap3Session.getTransaction().commit();

				if ( ! updated )
				{
					LOG.debug("Exiting contacts::DELETE /" + id + ": NOT_FOUND");
					return Response
							.status(Status.NOT_FOUND)
							.build();
				}
				LOG.debug("Exiting contacts::DELETE /" + id + ": OK");
				return Response
						.ok().build();
			}
			catch ( Exception e )
			{
				e.printStackTrace();
				LOG.debug("Exiting contacts::DELETE /" + id + ": Exception: " + e.getMessage());
				return Response
						.serverError()
						.entity("Caught exception: " + e.getMessage())
						.build();
			}
		}
		
		/* (non-Javadoc)
		 * @see com.microstar.tap3.contact.ContactResource#createContact(com.microstar.tap3.contact.api.ContactObject)
		 */
		@Override
		public Response createContact(ContactObject co)
		{
			LOG.debug("Entering contacts::POST");
			try
			{
				tap3Session.beginTransaction();
				
				// Setup the new objects
				Contact c = ContactTransformer.transform(co);
				Address a = ContactTransformer.transformAddress(co);
				CustomerContactLink ccl = new CustomerContactLink();
				
				// Find the customer
				IdentifierLoadAccess<Customer> custIla = tap3Session.byId(Customer.class);
				Customer cust = custIla.getReference(co.getCustomerId());
				if ( cust == null )
					return Response
							.status(Status.NOT_ACCEPTABLE)
							.entity(RestUtil.errorMsg("Customer " + co.getCustomerId() + " not found.", null))
							.build();
				
				ccl.setCustomer(cust);
				ccl.setContact(c);
				if ( a != null )
					ccl.setAddress(a);
				
				// Look up the Contact Type by name
				String hql = "FROM ContactType a WHERE name = '" + co.getContactType() + "'";
				Query<ContactType> query = tap3Session.createQuery(hql, ContactType.class);
				
				@SuppressWarnings("deprecation")
				ContactType ct = query.uniqueResult();
				if ( ct == null )
					return Response
							.status(Status.NOT_ACCEPTABLE)
							.entity(RestUtil.errorMsg("Contact Type " + co.getContactType() + " not found.", null))
							.build();
				
				ccl.setContactType(ct);
				
				// Persist the objects
				tap3Session.save(c);
				if ( a != null )
					tap3Session.save(a);
				tap3Session.save(ccl);
				tap3Session.getTransaction().commit();
				
				co.setId(c.getId());
				
				return Response
						.status(Status.CREATED)
						.entity(co)
						.location(new URI(null,null, "/contacts/" + c.getId(),null))
						.build();

			} catch ( Exception e )
			{
				e.printStackTrace();
				return Response
						.serverError()
						.entity("Caught exception: " + e.getMessage())
						.build();
			}
			finally
			{
				
			}
		}
		
		/* (non-Javadoc)
		 * @see com.microstar.tap3.contact.ContactResource#updateContact(java.lang.String, com.microstar.tap3.contact.api.ContactObject)
		 */
		@Override
		public Response updateContact(String id, ContactObject co)
		{
			LOG.debug("Entering contacts::PUT /" + id);
			try
			{
				// Find the Contact in the DB
				tap3Session.beginTransaction();
				IdentifierLoadAccess<Contact> ila = tap3Session.byId(Contact.class);
				Contact c = ila.getReference(id);

				if ( c == null )
				{
					return Response
							.status(404)
							.build();
				}

				// Update the Contact
				c = ContactTransformer.transform(co, c);
				
				// Check to see if there's an address to update as well
				if ( co.getAddress() != null )
				{
					// We'll need to get the Contact's CCL to find the correct Address to update.
					if ( c.getCustomerContactLinks() == null || c.getCustomerContactLinks().isEmpty() || c.getCustomerContactLinks().size() > 1 )
					{
						return Response
								.status(500)
								.location(new URI(null, null, "/contacts/" + id))
								.entity(RestUtil.errorMsg("CustomerContactLink invalid", c.getCustomerContactLinks()))
								.build();
					}
					
					CustomerContactLink ccl = c.getCustomerContactLinks().iterator().next();
					Address a = ccl.getAddress();
					a = ContactTransformer.transform(co, a);
					tap3Session.update(a);
				}
				
				// Update Contact and commit transaction
				tap3Session.update(c);
				tap3Session.getTransaction().commit();
				LOG.debug("Updated Contact " + id);
				
				return Response
						.ok()
						.entity(co)
						.location(new URI(null,null,"/contacts/" + id,null))
						.build();

			} catch (URISyntaxException e)
			{
				e.printStackTrace();
				return Response
						.serverError()
						.entity("Caught exception: " + e.getMessage())
						.build();
			} catch (RollbackException e)
			{
				e.printStackTrace();
				return Response
						.serverError()
						.entity("Caught exception: " + e.getMessage())
						.build();
			}
			finally
			{
				
			}
		}
		
		/* (non-Javadoc)
		 * @see com.microstar.tap3.contact.ContactResource#getByCustId(java.lang.String)
		 */
		@Override
		public Response getByCustId(String cid)
		{
			LOG.info("Entering contacts::GET ?cid=" + cid);
			try
			{
				
	//			long start = System.currentTimeMillis();
				@SuppressWarnings("deprecation")
				Criteria custCrit = tap3Session.createCriteria(Customer.class);
				custCrit.add(Restrictions.eq("tapcustomerId", cid));
				Customer cust = (Customer) custCrit.uniqueResult();
	//			long end = System.currentTimeMillis();
	//			LOG.info("Cust took: " + (end-start));

	//			start = System.currentTimeMillis();
	//			javax.persistence.criteria.CriteriaQuery<Customer> q = cb.createQuery(Customer.class);
	//			Root<Customer> c1 = q.from(Customer.class);
	//			ParameterExpression<String> p = cb.parameter(String.class);
	//			q.select(c1).where(cb.equal(c1.get("tapcustomerId"), p));
	//			TypedQuery<Customer> query = em.createQuery(q);
	//			query.setParameter(p, cid);
	//			Customer cust1 = query.getSingleResult();
	//			end = System.currentTimeMillis();
	//			LOG.info("Cust1 took: " + (end-start));
				
				if ( cust == null )
				{
					return Response
							.status(404)
							.location(new URI(null, null, "/contacts?cid=" + cid, null))
							.build();
				}
				
				Set<CustomerContactLink> ccls = cust.getCustomerContactLinks();
				
				ArrayList<ContactObject> contacts = new ArrayList<>();
				for ( CustomerContactLink ccl : ccls )
				{
					if ( ! ccl.isDeleted() )
					{
						Contact c = ccl.getContact();
						Address a = ccl.getAddress();
						String ct = ccl.getContactType().getName();
						
						ContactObject co = new ContactObject();
						co.setContactType(ct);
						co = ContactTransformer.transform(c, a, co);
						
						contacts.add(co);
					}
				}

				return Response.ok()
						.entity(contacts)
						.location(RestUtil.makeURI("/contacts?cid=" + cid))
						.build();
			}
			catch (URISyntaxException e)
			{
				e.printStackTrace();
				return Response
						.serverError()
						.entity("Caught exception: " + e.getMessage())
						.build();
			}
		}
		
		/* (non-Javadoc)
		 * @see com.microstar.tap3.contact.ContactResource#getById(java.lang.String)
		 */
		@Override
		public Response getById(String id)
		{
			LOG.info("Entering contacts::GET /" + id);
			try
			{
				@SuppressWarnings("deprecation")
				Criteria crit = tap3Session.createCriteria(Contact.class);
				crit.add(Restrictions.idEq(id));
				
				Contact c = (Contact) crit.uniqueResult();
				if ( c == null )
				{
					return Response.status(404)
							.location(new URI(null, null, "/contacts/" + id, null))
							.build();
				}

				LOG.info("Got contact: " + c.getFirstName() + " " + c.getLastName());
				ContactObject co = new ContactObject();
				if ( c.getCustomerContactLinks() == null || c.getCustomerContactLinks().size() != 1 )
				{
					return Response
							.serverError()
							.entity(RestUtil.errorMsg("Invalid CCL", c.getCustomerContactLinks()))
							.build();
				}

				co.setContactType(c.getCustomerContactLinks().iterator().next().getContactType().getName());
				Address a = c.getCustomerContactLinks().iterator().next().getAddress();

				// Transform Contact and Address into ContactObject
				co = ContactTransformer.transform(c, a, co);
				
	//			co.setContact(co.createContact(c.getId(), c.getPrefix(), c.getFirstName(), c.getLastName(), c.getSuffix(), c.getJobTitle(), c.getDeskPhone(), c.getCellPhone(), c.getEmailAddress(), c.isReceiveOrderUpdates(), c.isReceiveInvoice(), c.isReceiveBill(), c.isReceiveNewsletter(), c.getSdfdid()));


				return Response
						.ok()
						.entity(co)
						.location(new URI(null, null, "/contacts/" + id, null))
						.build();
			}
			catch ( Exception ex )
			{
				return Response
						.serverError()
						.entity("Caught exception: " + ex.getMessage())
						.build();
			}
		}

		@Override
		public Response ping(int numAdditionalInstancesToPing)
		{
			LOG.info("Entering ping::" + numAdditionalInstancesToPing);
			LOG.info("ContactResourceImpl: " + this);
			LOG.info("Thread: " + Thread.currentThread().getId());
			
			if ( numAdditionalInstancesToPing > 0 )
			{
				try
				{
					Client client = ClientBuilder.newClient();
					String baseUrl = "https://y8m4qszor5.execute-api.us-west-2.amazonaws.com/TEST/contacts/ping?numAdditionalInstancesToPing=" +
							(numAdditionalInstancesToPing-1);
					WebTarget target = client.target(baseUrl);
					Builder builder = target.request().accept(MediaType.APPLICATION_JSON_TYPE);
					LOG.info("Ping::Calling ping with " + (numAdditionalInstancesToPing-1));
					Response response = builder.head();
					if ( response.getStatus() != Response.Status.OK.getStatusCode() )
					{
						LOG.info("PING ERROR: Calling ping from ping failed: " + response.getStatus());
					}
					LOG.info("Ping::Done calling");
				} catch (Exception ex)
				{
					ex.printStackTrace();
				}
			}
			
			LOG.info("Exiting ping");
			return Response
					.ok()
					.build();
		}
	}

**Comment by SAPessi** [comment]
Thanks Daniel, 

You are getting a 403 on the POST because there isn't an HTTP method defined in the `/contacts` resource in API Gateway. The `ANY` method you have defined there in the `{proxy+}` resource will only handle calls to sub-resources of contacts, for example `/contacts/123`. To handle requests to the contacts resource your API should look like this:

```
/
|_ /contacts
   |_ANY -> Lambda (POST/GET calls to /contacts)
   |_/{proxy+}
      |_ANY -> Lambda (calls to /contacts/123 - could be the same Lambda function for both
```

This is a start. I'll look into the code today but the 405 sounds like something with Jersey. I'll let you know what I find.

**Comment by davidmco65** [comment]
Oh wow!  I didn't know you had to do that!  Thanks so much!  That helps a lot.  I'll try that out very shortly.

David

**Comment by SAPessi** [comment]
I also edited your comment to add an even more scrubbed version of the impl class.

**Comment by SAPessi** [comment]
Assuming the API Gateway configuration fixes your 403 on the POST. I'm now trying to replicate the 405 on the DELETE method without much luck. 

When I start the server in local with your latest code, it responds to the DELETE method as expected. Same when I use Lambda and API Gateway.

This is the class I'm using to run the local tests:
```java
import org.glassfish.grizzly.http.server.HttpServer;
import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory;
import org.glassfish.jersey.jackson.JacksonFeature;
import org.glassfish.jersey.logging.LoggingFeature;
import org.glassfish.jersey.server.ResourceConfig;

import javax.ws.rs.core.UriBuilder;
import java.io.IOException;
import java.net.InetAddress;
import java.net.URI;
import java.net.UnknownHostException;

public class Service {
    public static void main(String[] args) throws IOException {
        System.out.println("Starting Embedded Jersey HTTPServer...\n");
        HttpServer httpServer = createHttpServer();

        httpServer.start();
    }

    private static HttpServer createHttpServer() throws IOException {
        ResourceConfig rc = new ResourceConfig()
                .packages("com.sapessi.testapi") // this is the package where I created your Contact class
                .register(JacksonFeature.class)
                .register(LoggingFeature.class);

        return GrizzlyHttpServerFactory.createHttpServer(getServerUri(), rc);
    }

    private static URI getServerUri() {
        return UriBuilder.fromUri("http://" + getLocalHostname() + "/").port(8085).build();
    }

    private static String getLocalHostname() {
        String hostName = "localhost";
        try {
            hostName = InetAddress.getLocalHost().getCanonicalHostName();
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
        return hostName;
    }
}
```

And this is my simple Lambda handler:
```java
import com.amazonaws.serverless.proxy.internal.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.internal.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import org.glassfish.jersey.jackson.JacksonFeature;
import org.glassfish.jersey.server.ResourceConfig;

public class LambdaHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {
    private ResourceConfig jerseyApplication = new ResourceConfig()
            .packages("com.sapessi.testapi")
            .register(JacksonFeature.class);
    private JerseyLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler
            = JerseyLambdaContainerHandler.getAwsProxyHandler(jerseyApplication);

    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        return handler.proxy(awsProxyRequest, context);
    }
}
```

**Comment by davidmco65** [comment]
So adding the additional method under the /contacts resource made everything work!

Not sure I totally understand why, but as long as it works, I'm happy.

I'd also be interested in contributing to this project if you are looking for developers/maintainers.  Let me know.

Thanks,
David

**Comment by SAPessi** [comment]
Thanks David, I'm currently working on issues #15 and #16. However, if there are other features you need in the library, feel free to open a new issue and send a pull request. We are always looking for feedback on the library. 

I'm going to close this issue for now. thanks for all the help to debug this.
