### ISSUE TITLE
Exception when to create request via aws lambda invoke

### ISSUE THREAD

**Issue by dotekien** [awslabs/aws-serverless-java-container#171]
* Framework version: XX
* Implementations: Jersey / Spring / Spring Boot / Spark

## Scenario
Using  
aws lambda invoke \
--invocation-type RequestResponse \
--function-name SomeFunction \
--region us-east-1 \
--payload file://file-path/input.txt \
--profile adminuser \
outputfile.txt

## Expected behavior
Mapping the request which is NOT from API gateway proxy mode to Spring Request

## Actual behavior
Exception

## Full log output

```
com.amazonaws.serverless.proxy.internal.LambdaContainerHandler
stack_trace : "com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token^@ 
 at [Source: (lambdainternal.util.NativeMemoryAsInputStream); line: 1, column: 1412] (through reference chain: com.amazonaws.serverless.proxy.model.AwsProxyRequest[\"body\"])^@
\tat com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)^@
\tat com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)^@
\tat com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)^@
\tat com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)^@
\tat com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:63)^@
\tat com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)^@
\tat com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)^@
\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)^@
\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)^@
\tat com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)^@
\tat com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1188)^@
\tat com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:199)^@
\tat com.demo.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:46)^@
\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)^@
\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)^@
\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)^@
\tat java.lang.reflect.Method.invoke(Method.java:498)^@
\tat lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)^@
\tat lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)^@
\tat lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)^@
\tat lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)^@
\tat java.lang.Class.forName0(Native Method)^@
\tat java.lang.Class.forName(Class.java:348)^@
\tat lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)^@
```

**Comment by SAPessi** [comment]
What's the content of `file://file-path/input.txt` you are passing in? Is it a valid API Gateway proxy event object?

**Comment by dotekien** [comment]
Yeah, it sounds like the system I am working with has its own way to transform the request to event object and also expect the response in a specific format.

Do you have any interface which I can write a custom function to handle this input and output?

**Comment by SAPessi** [comment]
Yes, the event is slightly different from what API Gateway sends as proxy. The main issue with that event above is that there is no `parameters` property, it should be `queryStringParameters`. Also, `body` is a string, not a json object:

```json
{
    "resource": "/{proxy+}",
    "path": "/Seattle",
    "httpMethod": "POST",
    "headers": {
      "day": "Friday"
    },
    "queryStringParameters": {
      "time": "morning"
    },
    "pathParameters": {
      "proxy": "Seattle"
    },
    "stageVariables": null,
    "requestContext": {
      "path": "/{proxy+}",
      "accountId": "123456789012",
      "resourceId": "nl9h80",
      "stage": "test-invoke-stage",
      "requestId": "test-invoke-request",
      "identity": {
        "cognitoIdentityPoolId": null,
        "accountId": "123456789012",
        "cognitoIdentityId": null,
        "caller": "AIDXXX...XXVJZG",
        "apiKey": "test-invoke-api-key",
        "sourceIp": "test-invoke-source-ip",
        "accessKey": "ASIXXX...XXDQ5A",
        "cognitoAuthenticationType": null,
        "cognitoAuthenticationProvider": null,
        "userArn": "arn:aws:iam::123456789012:user/kdeding",
        "userAgent": "Apache-HttpClient/4.5.x (Java/1.8.0_131)",
        "user": "AIDXXX...XXVJZG"
      },
      "resourcePath": "/{proxy+}",
      "httpMethod": "POST",
      "apiId": "r275xc9bmd"
    },
    "body": "{ \"callerName\": \"John\" }",
    "isBase64Encoded": false
  }
```

**Comment by dotekien** [comment]
Do you have any guide to write a customized reader/writer to resolve the format issue?

**Comment by SAPessi** [comment]
The [`RequestReader`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/RequestReader.java) and [`ResponseWriter`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/ResponseWriter.java) are not particularly complicated to implement. However, my recommendation would be to take in your POJO and map it to an [`AwsProxyRequest`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java) object. Call the framework with the default `AwsProxyRequest`, it will save you a lot of heartache along the way.

Out of curiosity, why not use the default proxy mode in API Gateway? It also saves you a lot of configuration in the API.

I'll keep this issue open to track docs - I'll add a wiki page on writing custom readers/writers.

**Comment by dotekien** [comment]
Thanks. 
I do agree with your solution and waiting for your wiki page.
Where is the best place to map a POJO to an AwsProxyRequest object ?

**Comment by SAPessi** [comment]
I would do it inside the Lambda handler. Receive your custom event type, then have a utility method that can take the values out of your object and populate an AwsProxyRequest. Then you can just call the `proxy()` method of the `LambdaContainerHandler` with the new request.

**Comment by dotekien** [comment]
In LambdaContainerHandler, you have
public void proxyStream(InputStream input, OutputStream output, Context context) throws IOException. Is there anyway to override this method? Without modify the framework?

**Comment by SAPessi** [comment]
Use the [`proxy()`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java#L160) method directly. All framework implementations of the library support the proxy method.

**Comment by dotekien** [comment]
Does the framework has any RequestHandler for this kind of interface ResponseType handleRequest(Object obj, Context) ?

**Comment by SAPessi** [comment]
No, it only supports specific types. I envision you doing something like this (using Jersey as an example):

```java
public class MyLambdaHandler implements RequestHandler<CustomRequestType, CustomResponseType> {
    private static final ResourceConfig jerseyApplication = new ResourceConfig()
                                                             .packages("com.amazonaws.serverless.sample.jersey")
                                                             .register(JacksonFeature.class);
    private static final JerseyLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler
            = JerseyLambdaContainerHandler.getAwsProxyHandler(jerseyApplication);

    @Override
    public CustomResponseType handleRequest(CustomRequestType input, Context context)
            throws IOException {
        AwsProxyResponse resp = handler.proxy(this.translateRequest(input));

        // method implementation omitted for brevity
        CustomResponseType finalResp = this.translateResponse(resp);
        // just in case it wasn't closed by the mapper
        return finalResp;
    }

    private AwsProxyRequest translateRequest(CustomRequestType customReq) {
        AwsProxyRequest newReq = new AwsProxyRequest();
        newReq.setPath(customReq.getPath());
        ...
        return newReq;
    }
}
```

**Comment by dotekien** [comment]
Yes, I just implement something similar to your above guide for SpringBoot and it works.
Now, I am able to test in local like this sam local invoke -e event.json "DemoFunc" :D

**Comment by sapessi** [comment]
Resolving this since we have also created the [wiki guide](https://github.com/awslabs/aws-serverless-java-container/wiki/Custom-event-types).
