### ISSUE TITLE
NPE with Spring Boot Example 

### ISSUE THREAD

**Issue by ixidion** [awslabs/aws-serverless-java-container#172]
* Framework version: 1.13
* Implementations: Spring Boot

## Scenario
NPE with Spring Boot Example and calling default URL:
`curl -X GET https://xxx.execute-api.eu-west-1.amazonaws.com/Prod/pets`

## Expected behavior
10 Pets are returned. HTTP code 200.

## Actual behavior
Error - HTTP Code 500

## Steps to reproduce
I followed installation procedure and called the URL. For a local SpringBootTestcase (MockMvc) it works without any problems. The problem might be related to the ApiGateway -> Lambda infrastructure.

## Full log output

> 2018-07-06 12:47:13.521 ERROR 1 --- [ main] o.s.boot.web.support.ErrorPageFilter : Forwarding to error page from request [/pets] due to exception [null]
> 
> java.lang.NullPointerException: null
> at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.getQueryParamValue(AwsProxyHttpServletRequest.java:819)
> at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest.getParameterValues(AwsProxyHttpServletRequest.java:474)
> at org.springframework.web.context.request.ServletWebRequest.getParameterValues(ServletWebRequest.java:159)
> at org.springframework.web.method.annotation.RequestParamMethodArgumentResolver.resolveName(RequestParamMethodArgumentResolver.java:175)
> at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:103)
> at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
> at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:158)
> at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:128)
> at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
> at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
> at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
> at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
> at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
> at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
> at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
> at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
> at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager$ServletExecutionFilter.doFilter(FilterChainManager.java:351)
> at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84)
> at com.amazonaws.serverless.sample.springboot.filter.CognitoIdentityFilter.doFilter(CognitoIdentityFilter.java:60)
> at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84)
> at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
> at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84)
> at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
> at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
> at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
> at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
> at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84)
> at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:207)
> at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:154)
> at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:52)
> at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:168)
> at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:200)
> at com.amazonaws.serverless.sample.springboot.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:48)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
> at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
> at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
> at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
> at java.lang.Class.forName0(Native Method)
> at java.lang.Class.forName(Class.java:348)
> at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)

**Comment by SAPessi** [comment]
Hey @ixidion, the issue was addressed in #168 and the code is committed in the SNAPSHOT version in this repo. Since 1.2 release is close, I was planning to wait for it.
