### ISSUE TITLE
The Spring example is failing via the API Gateway straight out of the box.

### ISSUE THREAD

**Issue by jdinerstein** [awslabs/aws-serverless-java-container#174]
* Framework version: 1.1.3
* Implementations: Spring

## Scenario
I built the sample Spring example project.  I used the commands as given in the readme and deployed it. 
 This worked perfectly.

Then I tested the lambda directly from the lambda console, with the event posted here in another issue, directly and it worked correctly.  Lots of output with a statusCode of 200.

## Expected behavior
Hit the URL from my API Gateway from the CloudFormation stack.

Expected to see the same general payload as from the lambda directly.

## Actual behavior
https://<removed>.execute-api.us-east-1.amazonaws.com/Prod/pets

{"message":"Gateway timeout"}

## Steps to reproduce

Literally follow the steps from the Readme.md.

And then hit: https://<removed>.execute-api.us-east-1.amazonaws.com/Prod/pets

## Full log output

Here is the output from the mvn package:
[INFO] --- maven-shade-plugin:2.3:shade (default) @ serverless-spring-example ---
[INFO] Including com.amazonaws.serverless:aws-serverless-java-container-spring:jar:1.1.3 in the shaded jar.
[INFO] Including com.amazonaws.serverless:aws-serverless-java-container-core:jar:1.1.3 in the shaded jar.
[INFO] Including javax.servlet:javax.servlet-api:jar:3.1.0 in the shaded jar.
[INFO] Including javax.ws.rs:javax.ws.rs-api:jar:2.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.9.5 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.9.5 in the shaded jar.
[INFO] Including commons-fileupload:commons-fileupload:jar:1.3.3 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.2 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.25 in the shaded jar.
[INFO] Including com.amazonaws:aws-lambda-java-core:jar:1.2.0 in the shaded jar.
[INFO] Including org.springframework:spring-webmvc:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-aop:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-beans:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-core:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-jcl:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-expression:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-web:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-context:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-context-indexer:jar:5.0.3.RELEASE in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-core:jar:2.8.2 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-api:jar:2.8.2 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-slf4j-impl:jar:2.8.2 in the shaded jar.
[INFO] Including com.amazonaws:aws-lambda-java-log4j2:jar:1.1.0 in the shaded jar.
[INFO] Replacing original artifact with shaded artifact.

I included this just to show the versions of everything being pulled into the build.

And here is the CloudWatch log for this run:

NOTE: That there is a lovely null pointer exception.  This NPE seems to be down in Spring.  But since I didn't change anything in the source of the example it would seem to be an interaction between the aws-serverless-java-container and Spring.

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
START RequestId: 952fa4b9-8ca5-11e8-9d00-275373f127b0 Version: $LATEST
END RequestId: 952fa4b9-8ca5-11e8-9d00-275373f127b0
REPORT RequestId: 952fa4b9-8ca5-11e8-9d00-275373f127b0	Duration: 737.59 ms	Billed Duration: 800 ms Memory Size: 512 MB	Max Memory Used: 91 MB	
START RequestId: a444ba3e-8ca5-11e8-b6fe-b750c6e28de2 Version: $LATEST
05:19:28.893 [main] ERROR com.amazonaws.serverless.proxy.internal.LambdaContainerHandler - Error while handling request
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:986) ~[task/:?]
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870) ~[task/:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[task/:?]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855) ~[task/:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[task/:?]
at com.amazonaws.serverless.proxy.spring.LambdaSpringApplicationInitializer.dispatch(LambdaSpringApplicationInitializer.java:114) ~[task/:?]
at com.amazonaws.serverless.proxy.spring.LambdaSpringApplicationInitializer.service(LambdaSpringApplicationInitializer.java:205) ~[task/:?]
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager$ServletExecutionFilter.doFilter(FilterChainManager.java:351) ~[task/:?]
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84) ~[task/:?]
at com.amazonaws.serverless.sample.spring.filter.CognitoIdentityFilter.doFilter(CognitoIdentityFilter.java:61) ~[task/:?]
at com.amazonaws.serverless.proxy.internal.servlet.FilterChainHolder.doFilter(FilterChainHolder.java:84) ~[task/:?]
at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:207) ~[task/:?]
at com.amazonaws.serverless.proxy.spring.SpringLambdaContainerHandler.handleRequest(SpringLambdaContainerHandler.java:182) ~[task/:?]
at com.amazonaws.serverless.proxy.spring.SpringLambdaContainerHandler.handleRequest(SpringLambdaContainerHandler.java:42) ~[task/:?]
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:168) [task/:?]
at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:200) [task/:?]
at com.amazonaws.serverless.sample.spring.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:49) [task/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]

**Comment by jdinerstein** [comment]
On further review it appears that there are a couple of exceptions being thrown in this log.  I can post more of it here if it is needed.

**Comment by jdinerstein** [comment]
First thing this morning, after a bit of rest I decided to see if other versions proved out any differently.  In reviewing the pom.xml file last night before calling it I realized that the other libraries were all explicit versions. So the only one that would be changing was this one.

I rolled back to 0.9.1 as that seemed old enough and it failed to compile.  A result which was not entirely unexpected as it is pretty old.  Something in use in the demo code was calling on something no longer implemented.

I then rolled it forward to the old version 1.0.1.  Seemed like the next logical step.  And on this version, again 1.0.1, it worked properly!  The test from the lambda console executed correctly with the same output as before, and this time for the first time in this test the URL test to https://***.execute-api.us-east-1.amazonaws.com/Prod/pets returned the same payload of data.  So progress...

So for now something between 1.0.1 and 1.1.3 no longer plays well with others....  Trying to continue to narrow it down:
- 1.1 works
- 1.1.1 fails in the lambda console which is new and also from the URL
- 1.1.2 works in the lambda console again,  and also from the URL.

So it would seem to be something between the 1.1.2 and 1.1.3 builds that is impacting this sample.  Which I suppose makes sense...

**Comment by SAPessi** [comment]
Yes, I suspect this is the issue reported in #168. I'd suggest you use version 1.2-SNAPSHOT from the master branch. I'll publish a patch soon as 1.1.4

**Comment by jdinerstein** [comment]
OK.  Thanks for the response.  I will do so.

Thanks for the great project.

**Comment by SAPessi** [comment]
@jdinerstein I released 1.1.4 to maven central yesterday.
