### ISSUE TITLE
Build failed in the spring version

### ISSUE THREAD

**Issue by mac10046** [awslabs/aws-serverless-java-container#176]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:25 min
[INFO] Finished at: 2018-07-30T15:23:32+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aws-serverless-java-container-spring: Could not resolve dependencies for project com.amazonaws.serverless:aws-serverless-java-container-spring:jar:1.2-SNAPSHOT: Could not find artifact com.amazonaws.serverless:aws-serverless-java-container-core:jar:1.2-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by SAPessi** [comment]
Hey @mac10046 - 1.2-SNAPSHOT is not yet published on maven central. If you want to use it as a dependency for an application you'll have to install it manually on your local box:
1. Clone the `master` branch of this repository to your local box
2. From the project folder, run `mvn install`.
3. Try to compile your project again, it should pick 1.2-SNAPSHOT from your local installation
