### ISSUE TITLE
Maven package fails

### ISSUE THREAD

**Issue by sheltonn** [awslabs/aws-serverless-java-container#185]
* Framework version: 1.1
* Implementations: Jersey / Spring / Spring Boot / Spark

## Scenario
Run `mvn package` from the command line or within IntelliJ

## Expected behavior
The compile, test and package should complete successfully

## Actual behavior
The archetype child modules are unable to back-track to their parent

## Full log output

FIX PR https://github.com/awslabs/aws-serverless-java-container/pull/186

**Comment by sheltonn** [comment]
https://github.com/awslabs/aws-serverless-java-container/pull/186

**Comment by SAPessi** [comment]
Closing this since it was merged.
