### ISSUE TITLE
How to throw a springboot exception to lambda while using serverless java container

### ISSUE THREAD

**Issue by dotekien** [awslabs/aws-serverless-java-container#187]
* Framework version: any
* Implementations: Spring / Spring Boot

## Scenario
The exception is caught by org.springframework.boot.web.servlet.support.ErrorPageFilter.
In order to have SQS knowing that the sending message is failed, the exception needs to be caught by lambda.

**Comment by SAPessi** [comment]
Why use SpringBoot in a Lambda function that processes SQS messages? Seems overkill. 

You could use a [`@ControllerAdvice` class](https://www.baeldung.com/global-error-handler-in-a-spring-rest-api).

**Comment by SAPessi** [comment]
You will have to re-throw it form the `@ControllerAdvice` class and let it bubble up to the Lambda service.

**Comment by SAPessi** [comment]
Closing this issue.
