### ISSUE TITLE
AwsHttpServletResponse#setCharacterEncoding(String) is setting Content-Encoding

### ISSUE THREAD

**Issue by larmog** [awslabs/aws-serverless-java-container#188]
* Framework version: 1.1.4
* Implementations: Core

## Scenario
The `setCharacterEncoding`-method in `AwsHttpServletResponse` on row 337 is using the wrong HTTP header: `Content-Encoding` that should be used for [compression](https://en.wikipedia.org/wiki/HTTP_compression).

`response.setCharacterEncoding("UTF-8")`

## Expected behavior
For example:
`Content-type: application/json; charset=utf-8`
## Actual behavior
Header:
`Content-Encoding: UTF-8`

**Comment by SAPessi** [comment]
This is merged in the core branch. Closing the issue. Thank you so much for the contribution @larmog!
