### ISSUE TITLE
Springboot app restart randomly even though a cloudwatch warmer is scheduled every 5 minutes

### ISSUE THREAD

**Issue by dotekien** [awslabs/aws-serverless-java-container#195]
* Framework version: 1.1
* Implementations: Spring Boot

## Scenario
a cloudwatch warmer runs every 5 minutes but from the cloudwatch log, springboot application restarts randomly 10 times a day

## Expected behavior
Springboot should not restart randomly

**Comment by SAPessi** [comment]
Hey @dotekien, AWS Lambda recycles execution environments for maintenance regularly. For this reason, you may see existing environments go away and new ones be instantiated throughout the day.

**Comment by dotekien** [comment]
Thanks @SAPessi for your quick response.
