### ISSUE TITLE
Allow (or delegate to) other dispatcherServlets

### ISSUE THREAD

**Issue by benoitparis** [awslabs/aws-serverless-java-container#196]
* Implementation: Spring / Spring Boot

This is a feature request, also some kind of guidance request as well (would love to implement it myself)

## Scenario

I'm trying to use a SimpleGraphQLServlet from here:
https://github.com/graphql-java-kickstart/graphql-java-servlet

I get an "Only dispatcherServlet is supported" message at startup; which must come from here:
https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringBootLambdaContainerHandler.java

(On a non-lambda server) The logs are:
2018-10-10 20:32:30.061  INFO 46092 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-10-10 20:32:30.063  INFO 46092 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet simpleGraphQLServlet mapped to [/graphql/*]

The inheritance story is the following:

HttpServlet->HttpServletBean->FrameworkServlet->DispatcherServlet
HttpServlet->GraphQLServlet->SimpleGraphQLServlet

As someone well versed into Spring's entrails, how would one proceed so that he can serve some graphQL on AWS lambdas?

**Comment by SAPessi** [comment]
Could you use a `ServletRegistrationBean` in your application @benoitparis?

```java
@Bean
public ServletRegistrationBean servletRegistrationBean(){
    return new ServletRegistrationBean(new SimpleGraphQLServlet(),"/graphql/*");
}
```

**Comment by sapessi** [comment]
Resolving this since I have not heard back in a while.

**Comment by otbe** [comment]
Sorry for bringing back this quite old issue but Im faced with it now.

It tried your `ServletRegistrationBean` solution but the constructor of SimpleGraphQLServlet is private. Is there any other solution? 

Thank you!
