### ISSUE TITLE
Pass requestContext -> authorizer -> attribute to RESTendpoint method

### ISSUE THREAD

**Issue by securethings-amar** [awslabs/aws-serverless-java-container#213]
* Framework version: 1.1
* Implementations: Spring Boot

## Scenario
Before API Gateway pass request to lamda function, my custom authorizer kicked in and reads tenantId from authorization header. I want access to this tenantId attribute set in API Proxy request within @Controllers GET method so that I can return only tenant specific records.

Looking for a sample/example. Thanks

**Comment by sapessi** [comment]
Hey @securethings-amar, you can get the full API Gateway context (including authorizer context) from the `HttpServletRequest` object. We [write it in there as an attribute](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java#L45). Hopefully this helps.

**Comment by securethings-amar** [comment]
> 
> 
> Hey @securethings-amar, you can get the full API Gateway context (including authorizer context) from the `HttpServletRequest` object. We [write it in there as an attribute](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java#L45). Hopefully this helps.


Thanks Stefano for a quick turnaround! so does this mean, I should directly use HttpServletRequest as an argument into REST endpoint method of controller as follows?

`@RestController
public class PetsController {
        @RequestMapping("/pets", method = POST)
        public HttpServletResponse createPet(HttpServletRequest request) {
                    // Use request; withdraw attribute I want; use it
        }
}
`

**Comment by sapessi** [comment]
Yes, to access the API Gateway context you need to use the raw `HttpServletRequest`. However, there's nothing stopping from receiving two parameters in your `createPet` method, both the `HttpServletRequest` and the `Pet` object. Spring will take care of doing the injection/unmarshal.

**Comment by securethings-amar** [comment]
Thank you! And sorry it took so long to say two words.
