### ISSUE TITLE
Cast exception when start spring container 

### ISSUE THREAD

**Issue by isczh** [awslabs/aws-serverless-java-container#225]
* Framework version: 1.3
* Implementations: Spring

## Scenario
https://github.com/awslabs/aws-serverless-java-container/blob/97f4d3034ef9a84db0950ef36f248817a3618121/aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/LambdaSpringApplicationInitializer.java#L146

This listener will also listen refresh event and cause a cast exception. Even though it can be catch by spring 5(leave a debug log), but in lower version will cause error. And I think servletRequestHandledEvent is not invoked, we don't have to cast it here.

**Comment by sapessi** [comment]
I expected the application listener to be triggered only for the request handled events - otherwise what's the point of the generic there? Any idea how to avoid this? Should I have a separate listener for the refresh?

**Comment by sapessi** [comment]
I'm going to remove the listener altogether as it is no longer required for the response latch to be release. All unit tests still pass.

**Comment by sapessi** [comment]
Closing since version `1.3.1` is out.
