### ISSUE TITLE
StreamLambdaHandler  without Lambda Proxy

### ISSUE THREAD

**Issue by NRosenbergLoyaltyOne** [awslabs/aws-serverless-java-container#229]
The class StreamLambdaHandler  is using the SpringBootLambdaContainerHandler to initilize spring and pass the lambda request along. Is there a way to do the same without using the Aws Lambda proxy? So my Spring Boot rest endpoints can function the same as if I wasn`t using lambda?

Thank you.

**Comment by sapessi** [comment]
Can you explain more about what you are trying to achieve? The library defines a `RequestReader` and `ResponseWriter` interface that lets you support custom event types and outputs.

**Comment by NRosenbergLoyaltyOne** [comment]
So, when I create an API Gateway to access my lambda thru Rest, I have to mark the "Lambda Proxy" flag, that wraps the body of my request into the json mentioned here: https://github.com/awslabs/aws-serverless-java-container/issues/130#issuecomment-369674101.

My question would be, what if I don`t want to use the Lambda Proxy? If I want to be able to use a simple body, like if my Spring Boot app was running on a normal server, but I still want to have a unique handler for all the rest calls, instead of creating a separate one for each of my spring boot controllers, is there a way to do it?

SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class) routes my calls to the correct endpoint, which I want, but I don'`t want it to be wrapped in the Lambda Proxy.

Something like SpringBootLambdaContainerHandler<MyRequest, MyResponse> I guess.

Sorry if it's a dumb question or I'm not making much sense.

Thanks for the help

**Comment by sapessi** [comment]
If you don't use the proxy wrapper, your only alternative is to use mapping templates in API Gateway to generate a json event - if that's what you are looking for, then implementing customer RequestReaders and ResponseWriters is your best bet. Unless you have special requirements that force you to use mapping templates, I'd encourage you to stick with the proxy integration. Lambda cannot receive http requests directly like your clients send them to API Gateway.

**Comment by NRosenbergLoyaltyOne** [comment]
Got it. Thank you very much for the info.
