### ISSUE TITLE
Obtaining request body for PUT request

### ISSUE THREAD

**Issue by tedyu** [awslabs/aws-serverless-java-container#231]
We are using aws-serverless-java-container-jersey 1.3

I am looking for how request body (of text) can be obtained for PUT request (without using spring).
I have looked at src/test/java/com/amazonaws/serverless/proxy/jersey/EchoJerseyResource.java 
```
    public Response emptyStream(@PathParam("paramId") String paramId, @PathParam("param2") String param2) {
```
However, the above file doesn't seem to show example.

Suppose we have a method declared as:
```
    @Path("/status")
    @PUT
    @Consumes(MediaType.APPLICATION_JSON)
    public Response setLogsNeeded(@QueryParam("tenantId") String tenantId,
                                  final UploadStatus uploadStatus,
                                  @Context ContainerRequestContext context) {
```
where UploadStatus is a POJO containing an int and a String.
How would the json be formed for the UploadStatus POJO ?

Thanks

**Comment by sapessi** [comment]
Hey @tedyu, Jersey should be able to do that for you. See my [test code here](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/EchoJerseyResource.java#L172). The `SingleValueModel` in the parameter is automatically unmrashalled. See also a decent [example here](http://appsdeveloperblog.com/jersey-http-post-example/).

**Comment by sapessi** [comment]
Closing this issue since I've not heard back in a long time.
