### ISSUE TITLE
exception occurs when cookie value is empty

### ISSUE THREAD

**Issue by wangjl1110** [awslabs/aws-serverless-java-container#247]
* Framework version: 1.2 and above
* Implementations: Jersey / Spring / Spring Boot / Spark

## Steps to reproduce
Set the value of cookie to empty. Call req.getCookies().getName(), exception occurs

**Comment by sapessi** [comment]
[Release 1.3.2](https://github.com/awslabs/aws-serverless-java-container/releases/tag/aws-serverless-java-container-1.3.2) - which includes this fix - is on its way to maven central! Resolving this issue.
