### ISSUE TITLE
Logging Configuration

### ISSUE THREAD

**Issue by codescrawl** [awslabs/aws-serverless-java-container#249]
* Framework version: 1.3
* Implementations: Jersey

## Scenario
I cannot configure logging for my application although I have tried various combinations. I've added the following maven dependencies with log4j.version set in a property as 2.11.2 (I've tried a few variants):

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.8.0-beta2</version>
        </dependency>

## Expected behavior

Application logging to the console.

## Actual behavior

The following appears in the console when using SAM local:

log4j:WARN No appenders could be found for logger (com.amazonaws.serverless.proxy.internal.LambdaContainerHandler).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[32mSTART RequestId: a909c8ce-5c35-4775-9adf-04e2ec7c4b97 Version: $LATEST[0m
[32mEND RequestId: a909c8ce-5c35-4775-9adf-04e2ec7c4b97[0m
[32mREPORT RequestId: a909c8ce-5c35-4775-9adf-04e2ec7c4b97	Duration: 697.16 ms	Billed Duration: 700 ms	Memory Size: 512 MB	Max Memory Used: 10 MB	[0m

## Steps to reproduce

My log4j2.xml is super simple:

```<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns="http://logging.apache.org/log4j/2.0/config">
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss:SSS} [%t] %-5level %logger{36} - %msg%n" />
        </Console>
   ` </Appenders>
    <Loggers>
        <Root level="WARN">
            <AppenderRef ref="Console" />
        </Root>
    </Loggers>
</Configuration>
```

It is located in my java/main/resources directory and definitely getting into the zip file.

No matter what I've attempted I can't get rid of the warning or get any meaningful logging out of the application. Is there an example anywhere that can help me move forward?

Thanks!

**Comment by sapessi** [comment]
Hi @codescrawl, apologies for the delay. Have you tried including Lambda's implementation of the Log4j APIs? [Docs here](https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html).

**Comment by sapessi** [comment]
Did the Lambda Log4j library solve the issue @codescrawl? Can we close this?

**Comment by sapessi** [comment]
Assuming this issue is resolved. If you are still running into trouble feel free to re-open.
