### ISSUE TITLE
Jersey doesn't honor @Produces annotation.

### ISSUE THREAD

**Issue by feinstein** [awslabs/aws-serverless-java-container#250]
* Framework version: 1.3.1
* Implementations: Jersey 

I created a very simple project from the Jersey archetype and made only this modification:

```java
package com.example.resources;


import java.util.Map;
import java.util.HashMap;

import javax.ws.rs.*;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("/ping")
public class PingResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.TEXT_PLAIN)
    public Response ping(@QueryParam("message") String message) {
        Map<String, String> pong = new HashMap<>();
        pong.put("pong", "Hello, World!");
        if (message != null) {
            pong.put("message", message);
        } else {
            pong.put("message", "message is null");
        }
        return Response.status(Response.Status.OK).entity(pong).build();
    }

    @Path("/keepalive")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Consumes(MediaType.TEXT_PLAIN)
    public Response keepalive() {
        return Response.status(Response.Status.OK).build();
    }
}

```

So, basically, I have a `keepalive` endpoint that will generate a `text/plain` response.

When I invoke this using SAM Local, this is what I get:

![image](https://user-images.githubusercontent.com/8120472/54873119-a9354680-4dae-11e9-97f1-1f3cfe78b6ae.png)

I also tried this test case:

```java
@Test
public void should_RespondWithOK_WhenKeepalive() {
    InputStream requestStream = new AwsProxyRequestBuilder("/ping/keepalive", HttpMethod.GET)
            .header(HttpHeaders.ACCEPT, MediaType.TEXT_PLAIN)
            .buildStream();
    ByteArrayOutputStream responseStream = new ByteArrayOutputStream();

    handle(requestStream, responseStream);

    AwsProxyResponse response = readResponse(responseStream);
    assertNotNull(response);
    assertEquals(Response.Status.OK.getStatusCode(), response.getStatusCode());

    assertFalse(response.isBase64Encoded());

    assertTrue(response.getMultiValueHeaders().containsKey(HttpHeaders.CONTENT_TYPE));
    assertTrue(response.getMultiValueHeaders().getFirst(HttpHeaders.CONTENT_TYPE).startsWith(MediaType.TEXT_PLAIN));
}
```

Which fails at ` assertTrue(response.getMultiValueHeaders().containsKey(HttpHeaders.CONTENT_TYPE));`

**Comment by sapessi** [comment]
Hey @feinstein, have you tried running it in AWS using Lambda and API Gateway? I'd like to rule out SAM local as the culprit before we dig deeper into the code

**Comment by feinstein** [comment]
No, I didn't.

I wasted some time converting my setup to use SAM Local, and once I found it won't attend my needs, I am converting all back to GlasshFish for testing (probably automated Jetty shortly). 

Could you test it on AWS? I am not very much proficient on the `yaml` deployment, so in order for me to test, I would have to do it all by hand on the console, while you know all that `yaml` magic could (I think) deploy it and test it very quickly. 

Just run the jersey archetype, paste that code and call the `keepalive` endpoint. If you can't right now, it's fine, I will do it another day, when my project is ready for deployment.

**Comment by sapessi** [comment]
I'll run a test tomorrow

**Comment by sapessi** [comment]
The SAM CLI team has [implemented multiValueHeaders support](https://github.com/awslabs/aws-sam-cli/issues/735). It should be released shortly

**Comment by feinstein** [comment]
Although that's good to know, I don't think this is related to multi-value headers in SAM Local, as I got this behavior in a regular unit test.

Maybe `@Produces(MediaType.TEXT_PLAIN)` defaults to empty?

**Comment by sapessi** [comment]
Just tried to create a unit test for this and cannot replicate - this test succeeds for me.

**Method in my test resource:**
```java
@Path("/plain") @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Consumes(MediaType.APPLICATION_JSON)
    public Response plain() {
        return Response.status(200).entity("Hello!").build();
    }
```

**Unit test method:**
```java
@Test
    public void textPlainContent_plain_responseHonorsContentType() {
        AwsProxyRequest req = getRequestBuilder("/echo/plain", "GET")
                                            .nullBody()
                                            .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON)
                                            .header(HttpHeaders.ACCEPT, MediaType.TEXT_PLAIN)
                                            .build();

        AwsProxyResponse resp = handler.proxy(req, lambdaContext);
        assertEquals(200, resp.getStatusCode());
        assertTrue(resp.getMultiValueHeaders().containsKey(HttpHeaders.CONTENT_TYPE));
        assertEquals(MediaType.TEXT_PLAIN, resp.getMultiValueHeaders().get(HttpHeaders.CONTENT_TYPE).get(0));
    }
```

**Comment by feinstein** [comment]
Could you try the code I posted at the beginning? Otherwise I will test yours as soon as I get to my PC.

**Comment by sapessi** [comment]
Ah, figured it out. Unless you set an entity Jersey does not set the content type header since it's superfluous. It's not the framework that skips it, it's just not set to begin with.

**Comment by feinstein** [comment]
I was afraid this could be something about Jersey, but no-one at Jersey answered me, sorry to bother you with this and thank you for the support!

**Comment by sapessi** [comment]
No problem. I did some quick googling but can't find a way to force Jersey to add the content type header in a response. You may have to add the header manually when the body is empty.

**Comment by feinstein** [comment]
This is not an actual issue to me, I was just afraid the HTTP protocol was not being honored, but my APIs won't suffer from this. I was a little afraid this would impact others.

I guess setting an empty string to the body would do the trick as well.
