### ISSUE TITLE
Is there any way to get the Lambda context within the handler fuctions?

### ISSUE THREAD

**Issue by superbrown** [awslabs/aws-serverless-java-container#251]
The funtions in the SparkResources class, which are the REST controller funcitons, don't appear to have any means of getting a hold of the Lambda context object. (It isn't in the signature of the Route defined in the SparkResources class.)

Hopefully I'm wrong about that. If so, how can the context be accessed?

**Comment by sapessi** [comment]
Yes, the context is included in the `HttpServletRequest` as [an attribute](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java#L55) (alongside a few other teams).

**Comment by sapessi** [comment]
Did the suggestion solve your problem @superbrown? If so, can we close this issue.
