### ISSUE TITLE
Http response writer generating base64 encoded content for blob

### ISSUE THREAD

**Issue by otaviomedeiros** [awslabs/aws-serverless-java-container#257]
* Framework version: 1.3
* Implementations: Jersey 

## Scenario
I'm trying to download a zip file with jersey and aws api gateway with proxy integration.

```
@GET
@Path("/downloadfile")
@Consumes({ "application/json; charset=utf-8" })
@Produces({ "application/zip" })
public Response downloadZipFile(SecurityContext securityContext) {
        File zip = generateZipFile();
        return Response
                .ok(zip)
                .header("Content-Disposition", "attachment; filename=\"myZipFile.zip\"")
                .build();
    }
```

## Expected behavior
Response body with a blob.

## Actual behavior
Response body with base64 encoded content.

```
HTTP/2 200
content-type: application/zip
content-disposition: attachment; filename="myZipFile.zip"

UEsDBBQACAgIAGaerk4AAAAAAAAAAAAAAAAhAAAAT1AtVDEyMzUyMjI0OTkzOTAwMjcyNzI3OC5m
ZWF0dXJlc0tNLCktSrVSSEpJ4VIAAoeQ1OIS58TiVO/USlv/AN0QQyOweHByal5iUWY+QiUIwBnu
mWWpeQrhGUAiBEgAAFBLBwh4ziZyQAAAAFcAAABQSwECFAAUAAgICABmnq5OeM4mckAAAABXAAAA
IQAAAAAAAAAAAAAAAAAAAAAAT1AtVDEyMzUyMjI0OTkzOTAwMjcyNzI3OC5mZWF0dXJlUEsFBgAA
AAABAAEATwAAAI8AAAAAAA==
```
## Steps to reproduce
Add gradle dependency 
```
dependencies {
    compile 'com.amazonaws.serverless:aws-serverless-java-container-jersey:1.3'
}
```
and write a method like described in Scenario.

**Comment by sapessi** [comment]
Hi @otaviomedeiros, the framework uses the [list of binary content types from the `ContainerConfig` object](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletResponseWriter.java#L47) to decide whether to base64 encode a response. 

You should be able to set this by calling the `addBinaryContentTypes` from the handler constructor:
```java
LambdaContainerHandler.getContainerConfig().addBinaryContentTypes("application/zip");
```

**Comment by otaviomedeiros** [comment]
Hi @sapessi. Thanks for your quick answer.
Unfortunately it doesn't work and i can't find any example on how to get this working.
This is what i've done here...

```
public class MyHandler implements RequestStreamHandler {
    
    ....

    public MyHandler() {
        LambdaContainerHandler.getContainerConfig().addBinaryContentTypes("application/zip");
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException {
        ....
    }

}
```

**Comment by sapessi** [comment]
Hi @otaviomedeiros, I've been trying to replicate with a unit test in the framework but I see the expected output: ie the base64 encoded binary content and the `isBase64Encoded` parameter set to true. Based on this, I can only assume that the issue is the fact that API Gateway is not decoding the encoded body. Is `application/zip` [configured as a binary content type in API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html).

**Comment by otaviomedeiros** [comment]
@sapessi i can't convert the base64 encoded content to binary because i'm using proxy integration which doesn't provide a way to modify the content responded by the lambda function. The point is that  i'd like my lambda function responding with `isBase64Encoded` set to false and not base64 encoding the response content.

**Comment by sapessi** [comment]
@otaviomedeiros, Lambda cannot return a binary payload - Lambda only deals with JSON objects. This is why we base64-encode the response body. Once API Gateway receives this response, it automatically decodes it and returns it as binary. This behavior is controlled by the binary media types configuration in API Gateway. If you configure API Gateway to recognize `application/zip` as a binary media type, the `Content-Type` header of the response says `application/zip`, and the `isBase64Encoded` property of the Lambda output is set to `true`, API Gateway will automatically take the base64 content of the `body` property and decode it before sending the response back to the client - even if it is configured as a proxy.

As an aside, the same thing happens to binary requests. API Gateway recognizes the content as binary based on the `Content-Type` of the request and, if it is configured to integrate with Lambda, it base64 encodes the body before sending the event to the Lambda function.

**Comment by otaviomedeiros** [comment]
@sapessi you are completely right. I'm aware that i have to add the request `Accept` header to make it work as well as have configured Binary Media Types. I was trying to make it work without the need to add `Accept` header but it seems that it's not possible.
Thanks for all your help 😃
