### ISSUE TITLE
Superfluous ERROR log entry produced when no Content-Type header present

### ISSUE THREAD

**Issue by timbarker** [awslabs/aws-serverless-java-container#261]
* Framework version: 1.3.1
* Implementations: Spring Boot

## Scenario

When handling GET requests with no content-type header set (due to not having any content) a superfluous ERROR log entry is produced. e.g. 

> 2019-06-04 11:36:50,361 [main] ERROR c.a.s.p.i.s.AwsProxyHttpServletRequest - Called set character encoding to UTF-8 on a request without a content type. Character encoding will not be set

This results in noise in our applications logs from ALB heath-check requests which do not have a content-type header

[Link to offending log line](https://github.com/awslabs/aws-serverless-java-container/blob/e4f4d4de6016a60d3fe728181d24aa4d91e645ec/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java#L369)

## Expected behavior

No log is emitted at ERROR level, potentially just an INFO level message

## Actual behavior

An ERROR level log message is created

## Steps to reproduce

Create a Lambda using this project and send a GET request with no body or content-type header present. 

## Full log output

> 2019-06-04 11:36:50,361 [main] ERROR c.a.s.p.i.s.AwsProxyHttpServletRequest - Called set character encoding to UTF-8 on a request without a content type. Character encoding will not be set

**Comment by sapessi** [comment]
Thanks for the feedback @timbarker. you are right, I'll change this to `DEBUG` for the next release.

**Comment by sapessi** [comment]
[Release 1.3.2](https://github.com/awslabs/aws-serverless-java-container/releases/tag/aws-serverless-java-container-1.3.2) - which includes this fix - is on its way to maven central! Resolving this issue.
