### ISSUE TITLE
Custom headers not returning

### ISSUE THREAD

**Issue by Magicperf** [awslabs/aws-serverless-java-container#267]
* Framework version: XX
* Implementations: Jersey

## Scenario
When setting Response.header("MY_HEAD","TEST_HEAD") in my code, the header is not sent back as part of the response readers

## Expected behavior
Custom header set at lambda should be seen in the response header at API Gateway

## Actual behavior
Custom header not showing

## Steps to reproduce
Create any endpoint created with Jersey archtype and set a header in the Response builder. Call the lambda from proxy endpoint in API Gateway method Test. That header should be visible in the api gateway test log

## Full log output
Tue Jul 09 17:17:16 UTC 2019 : Endpoint response headers: {Date=Tue, 09 Jul 2019 17:17:16 GMT, Content-Type=application/json, Content-Length=591, Connection=keep-alive, x-amzn-RequestId=5c2f87cb-7d8b-4335-9557-4677c544a2f8, x-amzn-Remapped-Content-Length=0, X-Amz-Executed-Version=$LATEST, X-Amzn-Trace-Id=root=1-5d24cc1c-583696e025553b1544d9cdf5;sampled=0}

**Comment by sapessi** [comment]
Hi @Magicperf, the headers you pasted there are the headers returned by the Lambda service (the Lambda APIs), not the headers that the framework is trying to return. You should look at the response body from Lambda and the `multivalueHeaders` property.

**Comment by Magicperf** [comment]
You are correct. I see them now.

Thank you for the quick response
