### ISSUE TITLE
URLs in html getting encoded

### ISSUE THREAD

**Issue by gmaruti** [awslabs/aws-serverless-java-container#27]
I built a Spring MVC application and deployed on Lambda. I have a spring controller on Lamda which returns a HTML page. This page contains links as part of th:href attribute. But when rendered the link is not working as expected as URLs are getting encoded.

Looks some encoding filter getting applied on the content and encrypting all the URLs. This is happening even with the URL passed as "redirect:<url>"

Is there any configuration that i can go to avoid this issue.

For instance URL "maps.google.com?ll=40.447786,-80.001202&q=Alcoa+Corp" comng up as
%2F%2Fmaps.google.com%3Fll%3D40.447786%2C-80.001202%26q%3DAlcoa%2520Corp

**Comment by SAPessi** [comment]
The url there seems to be urlencoded. The framework itself does not do any url encoding, it simply returns the response body as a string: https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletResponseWriter.java#L42

Can you share some code on how the html is generated and returned? would be good to log some info along the way:
1. When the html is generated
2. Before the `AwsProxyResponse`is returned to API Gateway
3. What comes to the client

**Comment by gmaruti** [comment]
[PlaceListPage.txt](https://github.com/awslabs/aws-serverless-java-container/files/971836/PlaceListPage.txt)

Attached the HTML page (changed extension to .txt)

I have Spring Controller bean that returns the html

`
    @RequestMapping("/places")
    public String places() {
          ....
          String url = "PlacesListPage"; // PlacesListPage.html is present under templates directory
          return url;
     }
`

Above controller is called through API gateway. Right now the HTML page is being displayed to client but URLs with in the page are encoded.

In another scenario I have redirection to external URL

`
    @RequestMapping("/link")
    public String link() {
          ....
          String url = "redirect:<external URL>"; 
          return url;
     }
`
In this case on browser i see an encrypted URL and 404 message

Hope this helps to explain the issue more clear.

**Comment by SAPessi** [comment]
Thanks @gmaruti. Just to confirm, if you start the spring app on your local machine the url is returned correctly?

**Comment by gmaruti** [comment]
Yes, it does work in local...

**Comment by SAPessi** [comment]
Is there any chance I can get access to the demo app to replicate. I cannot find a place where the framework would be urlencoding something. The only place where we url encode is in the response here: https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java#L99

**Comment by SAPessi** [comment]
never mind. I managed to replicate the issue. I will look into it and let you know.

**Comment by SAPessi** [comment]
I located the issue in the `LinkExpression` class. When processing the link, it returns a URL encoded expression if the response is not null:

```java
return response != null?response.encodeURL(url):url;
```

I'll investigate this comparing how the embedded container in spring boot behaves.

**Comment by SAPessi** [comment]
@gmaruti are you using SpringBoot for the application or the plain spring framework?

**Comment by SAPessi** [comment]
@gmaruti  I have committed a fix to the servlet-improvements branch. This fixes the issue for me. If you can, clone the branch, mvn install in local, change your pom to use 0.5-SNAPSHOT and test if this fixes the issue for you.

**Comment by gmaruti** [comment]
Thanks,  I will check and let you know...

**Comment by gmaruti** [comment]
@SAPessi  I tested the code and it worked for me too!!.. Thanks for quick fix.

**Comment by SAPessi** [comment]
Nice. I will close this and merge
