### ISSUE TITLE
Invalid request type: Servlet3SecurityContextHolderAwareRequestWrapper. Only AwsProxyHttpServletRequest is supported

### ISSUE THREAD

**Issue by 1103036128** [awslabs/aws-serverless-java-container#275]
Hello, I have another problem, spring sercurity has made a mistake. I need your help.
* Framework version: 1.3.2
* Implementations: Spring Boot+Springsecurity

An error occurred when the loadUserByUsername to return user in the Security UserDetails Service
![image](https://user-images.githubusercontent.com/35803296/62820594-18aea580-bb99-11e9-868b-77943c720b90.png)
The CloudWatch error log are --
![image](https://user-images.githubusercontent.com/35803296/62820634-b904ca00-bb99-11e9-9d86-d36324a375a4.png)
![image](https://user-images.githubusercontent.com/35803296/62820645-d5a10200-bb99-11e9-92d4-6b919f000c53.png)
![image](https://user-images.githubusercontent.com/35803296/62820649-e81b3b80-bb99-11e9-83c5-8e1c13926d3e.png)
Please help me, thank you.

**Comment by 1103036128** [comment]
Here is my sercurity config --
![image](https://user-images.githubusercontent.com/35803296/62820895-0125eb80-bb9e-11e9-9546-d28efa489e6d.png)

**Comment by 1103036128** [comment]
It should be unable to forward requests.

**Comment by 1103036128** [comment]
![image](https://user-images.githubusercontent.com/35803296/62822951-9684a800-bbbd-11e9-9752-efc9660a93f7.png)
How to convert security requests into AwsProxyHttpServletRequest requests

**Comment by 1103036128** [comment]
Now I've removed the Spring Security redirection.

**Comment by sapessi** [comment]
Thanks for reporting this @1103036128. I'll look into it for the next release.

**Comment by sapessi** [comment]
Hi @1103036128 - I have implemented a fix for this in the `core` branch. Let me know if you can test and whether it works for you - that was a deep rabbit hole! Thanks again for the report

**Comment by sapessi** [comment]
Release 1.4 is out on maven central. The [release notes](https://github.com/awslabs/aws-serverless-java-container/releases/tag/aws-serverless-java-container-1.4) include a list of all the changes. Closing this issue.
