### ISSUE TITLE
Access context values passed from Custom Authorizer

### ISSUE THREAD

**Issue by dhcrees** [awslabs/aws-serverless-java-container#278]
Apologies for posting here, but I cant seem to find any help with this.   We are adding some context values in a custom authorizer and cant seem to retrieve the values within our Lambda.  So the context looks something like this:
},
"context": {
	"staffNo": "XXXXXX",
	"name": "test test"
}

We're using the Jersey flavour of the framework, but how do we get at the values from within our Lambda.. ?  Ideally from within a ContainerRequestFilter.

Any help would be much appreciated.

**Comment by dhcrees** [comment]
Managed to figure it out...

**Comment by sapessi** [comment]
Hey @dhcrees, glad you solved the issue. Was it caused by the serialization of the typed `proxy()` method instead of `proxyStream`? Perhaps I should make the documentation for this more visible?

**Comment by dhcrees** [comment]
Sorry, this is how I had it to work for me:  This is within a `ContainerRequestFilter`

`@Context`
`private HttpServletRequest httpServletRequest;`

```
AwsProxyRequestContext context = (AwsProxyRequestContext) httpServletRequest.getAttribute(API_GATEWAY_CONTEXT_PROPERTY);
String staffNo = context.getAuthorizer().getContextValue("staffNo");
String name = context.getAuthorizer().getContextValue("name");
```
Hope this helps someone else.

**Comment by sapessi** [comment]
Thanks for the update @dhcrees - I'll make sure that the section of the documentation about accessing these values is more visible. FYI the same values are also [copied to Jersey's `ContainerRequest`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyHandlerFilter.java#L143) object - you don't have to inject the `HttpServletRequest` if you don't want to.

**Comment by dhcrees** [comment]
Thanks @sapessi - Can you give me an example of how to get the values from the `ContainerRequest`, that was my first approach but it wasn't apparent how to get them.

**Comment by sapessi** [comment]
You should be able to use the `getProperty` method of the `ContainerRequest` just like you are using the `getAttribute` method of the `HttpServletRequest`

**Comment by dhcrees** [comment]
Got it, that's much simpler...  Thanks for all your help @sapessi.
