### ISSUE TITLE
Error when trying to register a container request filter through a lambda

### ISSUE THREAD

**Issue by alepeltier** [awslabs/aws-serverless-java-container#28]
Hello,

I'm currently working on an authentication filter with aws-serverless-java-container. I've created the filter and registered it in my Handler but when I try and run it in a lambda I get the following error message:

{
  "errorMessage": "A MultiException has 3 exceptions.  They are:\n1. java.lang.IllegalStateException: A descriptor SystemDescriptor(\n\timplementation=org.glassfish.jersey.server.internal.process.ServerProcessingBinder$UriRoutingContextFactory\n\tcontracts={org.glassfish.jersey.server.ExtendedUriInfo,javax.ws.rs.container.ResourceInfo,javax.ws.rs.core.UriInfo}\n\tscope=org.glassfish.jersey.process.internal.RequestScoped\n\tqualifiers={}\n\tdescriptorType=PROVIDE_METHOD\n\tdescriptorVisibility=NORMAL\n\tmetadata=\n\trank=0\n\tloader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@649d209a\n\tproxiable=true\n\tproxyForSameScope=false\n\tanalysisName=null\n\tid=16\n\tlocatorId=0\n\tidentityHashCode=1792845110\n\treified=true) requires a proxy, but the proxyable library is not on the classpath\n2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of test.AuthenticationFilter errors were found\n3. java.lang.IllegalStateException: Unable to perform operation: resolve on test.AuthenticationFilter\n",
  "errorType": "org.glassfish.hk2.api.MultiException"
}

I've previously registered a ContainerResponseFilter and that works perfectly fine. Is there any reason why my request filter isn't working the same way? I'm able to run the code locally and only get the error message when running it in a lambda. 

This is my handler, the filter I’m trying to register is called "AuthenticationFilter"

public class ApplicationHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse>  {
    private ResourceConfig jerseyApplication = new ResourceConfig()
            .packages("test")
            .register(AuthenticationFilter.class)
            .register(JacksonFeature.class)
            .register(CORSResponseFilter.class);
    private JerseyLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler
            = JerseyLambdaContainerHandler.getAwsProxyHandler(jerseyApplication);

    @Override
    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        return handler.proxy(awsProxyRequest, context);
    }
}

Any help will be appreciated.

**Comment by SAPessi** [comment]
The issue in this case is that the shaded jar did not include the `javassist` package that Jersey uses to do bytecode manipulation. When shading a jar, make sure to include `org.javassist:*`
