### ISSUE TITLE
AwsProxyHttpServletRequest#getParameterValues does not support multiple query string

### ISSUE THREAD

**Issue by yeDor** [awslabs/aws-serverless-java-container#280]
* Framework version: 1.3.2
* Implementations: Spring Boot 

## Scenario

http request is `<scheme>://<host>/<path>?state=xxx&state=yyy`
Function in controller is func(@RequestParam(value = "state", required = false) List<String> states)

## Expected behavior

Param states contains {"xxx", "yyy"}

## Actual behavior

Param states contains {"xxx"}

## Proposed fix

In AwsProxyHttpServletRequest#getParameterValues instead of using AwsProxyHttpServletRequest#getFirstQueryParamValue
use AwsProxyHttpServletRequest#getParameterValues

## Possible workaround 

request in form  `<scheme>://<host>/<path>?state=xxx,yyy` will work with spring

**Comment by yeDor** [comment]
As

**Comment by yeDor** [comment]
was closed by a miss click

**Comment by sapessi** [comment]
Thanks for the report @yeDor. I'm working on a fix and we'll push it out with the next release soon.
