### ISSUE TITLE
Lambda unable to invoke another lambda through Python SDK

### ISSUE THREAD

**Issue by nehaliacharya01** [awslabs/aws-serverless-java-container#292]
I am trying to invoke a lambda from another lambda using python SDK. Both the lambdas belong to the same VPC. The trigger lambda only contains a python script that invokes the second lambda (loader_development) and the code for that is as under:

```
from __future__ import print_function

import json
import logging
import os
from urllib2 import urlopen,Request,HTTPError
import boto3

logger = logging.getLogger()
logger.setLevel(logging.INFO)
region = os.environ['AWS_REGION']
     
def lambda_handler(event, context):
    invokeLambda = boto3.client('lambda', region_name = 'us-east-1')  
    request = {'resource':'/bucketstatus/latest','path':'/bucketstatus/latest','httpMethod':'GET'}
    invoke_response = invokeLambda.invoke(FunctionName='loader_development',
                                           InvocationType='RequestResponse',
                                           Payload=json.dumps(request))
    print(invoke_response['Payload'].read())
    
logger.info('Process Complete')
```
So `/bucketstatus/latest` is a GET request and this endpoint resides in the loader_development lambda's APIGateway (which is private). The loader_development lambda is a spring boot application whereas the trigger lambda is a standalone lambda that only has a python script to invoke an endpoint of the loader_development lambda to get the response. 

While testing this script, it gives a status of 500 and an Internal Server Error. The error is :
```
2019-10-09 10:09:09.279 ERROR 1 --- [ main] c.a.s.proxy.AwsProxyExceptionHandler : Called exception handler for:
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
10:09:09 at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:41)
10:09:09 at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:28)
10:09:09 at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:174)
10:09:09 at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:209)
10:09:09 at com.trimble.roadrunner.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:49)
10:09:09 at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
10:09:09 at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)
10:09:09 at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
10:09:09 at java.lang.Class.forName0(Native Method)
10:09:09 at java.lang.Class.forName(Class.java:348)
10:09:09 at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
```
The weird part is that when I try to invoke some other lambda (microservice), the request gets processed and I get a status of 200. The example lambda is also inside a VPC and has a private APIGateway. 

I am really not sure what I am missing. Any help would be greatly appreciated!

**Comment by sapessi** [comment]
In this case, I believe the exception is thrown because there is no [context property on the request object](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java#L45-L47). The request object needs to match closely the [AWS proxy event type](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format) - you can also use our [`AwsProxyRequest` model](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java) to guide you.

**Comment by nehaliacharya01** [comment]
This might be a silly question but how can I set the context property on the request object in PYTHON?

**Comment by sapessi** [comment]
You'd just declare a `requestContext` property that matches the format:

```python
 request = {
    'resource': '/bucketstatus/latest',
    'path':'/bucketstatus/latest',
    'httpMethod':'GET',
    'requestContext': {
      'accountId': "12345678912", # can be parsed from the function ARN
      "resourceId": "", # no need to include this
      "stage": "",
      "requestId": context.aws_request_id,
      "identity": {
        "cognitoIdentityPoolId": None,
        "accountId": None,
        "cognitoIdentityId": None,
        "caller": None,
        "apiKey": None,
        "sourceIp": "",
        "cognitoAuthenticationType": None,
        "cognitoAuthenticationProvider": None,
        "userArn": context.invoked_function_arn, #or whatever you'd like to use here
        "userAgent": "YourUserAgent/2.4.5",
        "user": null
      },
      "resourcePath":"/bucketstatus/latest",
      "httpMethod": "GET",
      "apiId": "No need"
    },
}
```

**Comment by nehaliacharya01** [comment]
Okay let me try that and get back if I get an error. Thanks 👍

**Comment by nehaliacharya01** [comment]
where can I find the requestId? Is it necessary to provide this?

**Comment by sapessi** [comment]
Not necessary but helpful, the request id available in the [Lambda context](https://docs.aws.amazon.com/lambda/latest/dg/python-context-object.html)

**Comment by nehaliacharya01** [comment]
Okay I understand and what is "userAgent": "YourUserAgent/2.4.5"?

**Comment by sapessi** [comment]
That value is taken from the HTTP `User-Agent` header. You don't really need to specify it, leave it blank.

**Comment by nehaliacharya01** [comment]
Thank you so much for your help. It worked. Been struggling with this for two days now!! Thanks 👍

**Comment by sapessi** [comment]
Great. I'll close the issue for now. Feel free to re-open it if you run into anything else.

**Comment by nehaliacharya01** [comment]
Hi. I have run into another issue now with the above code. So the trouble that I'm facing now is that this script is triggering the loader_development lambda more than once which is creating redundant entries in my database (for example: There should be only 6 entries in my database but probably due to multiple lambda invocations caused by the script, around 19 entries are getting created). 

From what I understood by analyzing the trigger's CloudWatch logs is that it creates a HTTPS connection with the loader lambda and waits for a response. If it doesn't receive a response, it again tries to create a new HTTPS connection. I could see this three times in a single log. I'll paste it here as well. 

Logs:
```
[DEBUG] 2019-10-25T16:00:05.155Z 0342a98d-1cee-474a-9147-b90c4a804c4c Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com:443
[DEBUG] 2019-10-25T16:01:05.298Z 0342a98d-1cee-474a-9147-b90c4a804c4c Event needs-retry.lambda.Invoke: calling handler <botocore.retryhandler.RetryHandler object at 0x7f8588337b90>
[DEBUG] 2019-10-25T16:01:05.299Z 0342a98d-1cee-474a-9147-b90c4a804c4c retry needed, retryable exception caught: Read timeout on endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/loader_development/invocations"
Traceback (most recent call last):
File "/var/runtime/botocore/retryhandler.py", line 269, in _should_retry
return self._checker(attempt_number, response, caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 317, in __call__
caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 223, in __call__
attempt_number, caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
ReadTimeoutError: Read timeout on endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/loader_development/invocations"
[DEBUG] 2019-10-25T16:01:05.316Z 0342a98d-1cee-474a-9147-b90c4a804c4c Retry needed, action of: 0.421144501955
[DEBUG] 2019-10-25T16:01:05.316Z 0342a98d-1cee-474a-9147-b90c4a804c4c Response received to retry, sleeping for 0.421144501955 seconds
[DEBUG] 2019-10-25T16:01:05.738Z 0342a98d-1cee-474a-9147-b90c4a804c4c Event request-created.lambda.Invoke: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f8587af6b90>>
[DEBUG] 2019-10-25T16:01:05.738Z 0342a98d-1cee-474a-9147-b90c4a804c4c Event choose-signer.lambda.Invoke: calling handler <function set_operation_specific_signer at 0x7f85887c8398>
```
The above set of logs appear **atleast 3 times** under the same log. How do I tell the script to not create a HTTPS connection more than once because this is causing multiple invocations and the loader_development lambda is busy most of the time trying to process older requests and because of that there are times when certain entities are not updated successfully in my database. Please let me know. Thanks!
