### ISSUE TITLE
Sam build does ont work with no modification

### ISSUE THREAD

**Issue by christianv2m** [awslabs/aws-serverless-java-container#293]
* Implementations: Spring Boot

## Scenario
Just download the example, rename sam.yml to template.yml and make a sam build.
It just gives error.

## Expected behavior
Build properly.

## Actual behavior
PS C:\Projectes\Fira\LeadRetrieval\i2> sam build
Building resource 'PetStoreFunction'
Running JavaGradleWorkflow:GradleBuild

Build Failed
Error: JavaGradleWorkflow:GradleBuild - Gradle Failed: Gradle build file not found: C:\Projectes\Fira\LeadRetrieval\i2\target\serverless-spring-boot-example-1.0-SNAPSHOT-lambda-package.zip\build.gradle
PS C:\Projectes\Fira\LeadRetrieval\i2>
## Steps to reproduce
1. download sample
2. rename sam.yml to template.yml
3. sun sam build

**Comment by sivaramit14** [comment]
I've been facing this issue as well.

**Comment by donhill** [comment]
Yep. same here changed codeUri . to . as it contains the pom.xml and build.gradle. The problem I am facing not is it can't find the handler when I run
sam build -t sam.yaml

then 
 sam local invoke 
...
sam local invoke 

START RequestId: e0a8de7b-e3cc-191d-e9b0-5b5a6443b92a Version: $LATEST
java.lang.ClassNotFoundException: my.service.StreamLambdaHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by sapessi** [comment]
Release 1.5 is making its way out to Maven central
