### ISSUE TITLE
Requests TRUNCATED on APIGateway

### ISSUE THREAD

**Issue by MounicaRamini** [awslabs/aws-serverless-java-container#294]
* Framework version
* Implementations: SpringBoot /AWS API Gateway

Scenario
AWS Console configurations(API Gateway, Lambda, S3, Permissions etc.,) has been configured using Terraform. When executing same service from AWS Lambda Console in LAMBDA_PROXY format, everything works fine - successfully brings up records from DB. But, when executing same service from AWS API Gateway Console, gives 404 error. I see on API Gateway Console that the end request being transformed get` [TRUNCATED] `before the body, and I don't see any logs related to the cause of this on Cloudwatch
 
Expected behavior
Process the request and pull records from DB hosted in AWS based on parameters sent in JSON body of request with some headers set

Actual behavior
Throwing 404 error on AWS API Gateway

@sapessi could you please help me on this issue

Full log output
```
Method request body before transformations: {
	"key1" : "value1" ,
	"key2" : "value2",
	"key3" : "value3"
}
Mon Oct 14 15:48:14 UTC 2019 : Endpoint request URI: Endpoint same as on AWS Console
Mon Oct 14 15:48:14 UTC 2019 : Endpoint request headers: {Authorization=--All Headers Specifies---- [TRUNCATED]
Mon Oct 14 15:48:14 UTC 2019 : Endpoint request body after transformations: {
	"resource":"/pathValue/resource",
	"path":"/pathValue/resource",
	"httpMethod":"POST",
	"headers":{"Accept":"application/json"},
	"multiValueHeaders":{"Accept":["application/json"]},
	"queryStringParameters":null,
	"multiValueQueryStringParameters":null,
	"pathParameters":null,
	"stageVariables":null,
	"requestContext":
		{"resourceId":"w2tvsr",
		"resourcePath":"/pathValue/resource",
		"httpMethod":"POST",
		"extendedRequestId":"Id=",
		"requestTime":"14/Oct/2019:15:48:14 +0000",
		"path":"/pathValue/resourc",
		"accountId":"AccountId",
		"protocol":"HTTP/1.1",
		"stage":"test-invoke-stage",
		"domainPrefix":"testPrefix",
		"requestTimeEpoch":1571068094171,
		"requestId":"requestId",
		"identity":{
			"cognitoIdentityPoolId":null,
			"cognitoIdentityId":null,
			"apiKey":"test-invoke-api-key",
			"principalOrgId":null,"
			cognitoAuthenticationType":null,
			"userArn":"arn:aws:sts::arn Value",
			"apiKeyId": `[TRUNCATED]`
			
Mon Oct 14 15:48:14 UTC 2019 : Sending request to Endpoint same as on AWS Console
Mon Oct 14 15:48:14 UTC 2019 : Received response. Status: 200, Integration latency: 46 ms
Mon Oct 14 15:48:14 UTC 2019 : Endpoint response headers: {Date=Mon, 14 Oct 2019 15:48:14 GMT, Content-Type=application/json, Content-Length=75, Connection=keep-alive, x-amzn-RequestId=9958d601-7249-48d1-86af-2d8723c98283, x-amzn-Remapped-Content-Length=0, X-Amz-Executed-Version=$LATEST, X-Amzn-Trace-Id=root=1-5da498be-2aea242599313e21140d4f71;sampled=0}
Mon Oct 14 15:48:14 UTC 2019 : Endpoint response body before transformations: {"statusCode":404,"multiValueHeaders":{},"body":"","isBase64Encoded":false}
Mon Oct 14 15:48:14 UTC 2019 : Method response body after transformations: 
Mon Oct 14 15:48:14 UTC 2019 : Method response headers: {X-Amzn-Trace-Id=Root=1-5da498be-2aea242599313e21140d4f71;Sampled=0}
Mon Oct 14 15:48:14 UTC 2019 : Successfully completed execution
Mon Oct 14 15:48:14 UTC 2019 : Method completed with status: 404
```
LAMBDA_PROXY format used to test on AWS Lambda Console
```
{
  "resource": "/resource",
  "path": "/resource",
  "httpMethod": "POST",
  "headers": {
      "Accept" : "application/json",
       "content-type": "application/json"
  }
  "multiValueHeaders": {},
  "queryStringParameters": null,
  "multiValueQueryStringParameters": null,
  "pathParameters": null,
  "stageVariables": null,
  "requestContext": {
    "resourcePath": "/resource",
    "httpMethod": "POST",
    "path": "//path/resource",
    "accountId": "accountIdNumber",
    "protocol": "HTTP/1.1",
    "stage": "test-invoke-stage",
    "domainPrefix": "testPrefix",
    "identity": {
      "cognitoIdentityPoolId": null,
      "cognitoIdentityId": null,
      "apiKey": "test-invoke-api-key",
      "principalOrgId": null,
      "cognitoAuthenticationType": null,
      "userArn": "actual arn with my userid",
      "apiKeyId": "test-invoke-api-key-id"
    }
  },
  "body": "{ \"Key1\": \"Value1\", \"Key2\": \"Value2\", \"Key3\": \"Vaue3\" }",
  "isBase64Encoded": "false"
}
```

**Comment by sapessi** [comment]
Hi @MounicaRamini - the `[TRUNCATED]` you see in the API Gateway logs is a red herring. API Gateway automatically hides sensitive information - such as an API key - and also truncates large log payloads to fit within the [limits of CloudWatch Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html). Lambda actually receives the full event. 

You function is running and responding with a `404` - ie it cannot find the request resource. What is the value of the `path` property being send by API Gateway? Does it match a resource in your application? What about the `httpMethod`, do you have that method in the resource? From your logs, is there a `/pathValue/resource` in your application that receives a `POST`?

**Comment by MounicaRamini** [comment]
Hi, the path property the APIGateway is sending is `/pathValue/resource`. . It's POST method and yes, that method is defined in resource. Yes, from logs it shows as "POST /pathValue/resourceHTTP/1.1" 404. But from AWS Lambda Console, I have only sent to `/resource` path and it worked.This is how it looks
from Lambda Console : "POST /viewLogs HTTP/1.1"
and from API Gateway Console : "POST /pathValue/resource HTTP/1.1".

On AWS Lambda Console, I have an option to send `"resource": "/resource"` as endpoint in the LAMBDA_PROXY Request. But in API Gateway, it automatically converts to `/pathValue/resource` as Endpoint

**Comment by sapessi** [comment]
Serverless Java Container does not use the value of the `resource` resource, only that of `path`. If your API Gateway is configured as a proxy integration to Lambda, the value of `path` is what you passed in the URL. For example, a request to `https://{restapi_id}.execute-api.{region}.amazonaws.com/{stage_name}/my/path`, would result in a path value of `/my/path`.

**Comment by MounicaRamini** [comment]
@sapessi Thanks, it was issue with Paths

**Comment by abdulrais** [comment]
Is there anyway I can pass authorization token in header. Whenever I am passing token, I am getting 401. I don't know why. Here is the request:

{
  "body": "eyJ0ZXN0IjoiYm9keSJ9",
  "resource": "/",
  "path": "/",
  "httpMethod": "GET",
  "headers": {
    "authorization": "Bearer token_name"
  },
  "multiValueHeaders": {},
  "requestContext": {
    "accountId": "123456789012",
    "resourceId": "123456",
    "stage": "prod",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "requestTime": "09/Apr/2015:12:34:56 +0000",
    "requestTimeEpoch": 1428582896000,
    "identity": {
      "cognitoIdentityPoolId": null,
      "accountId": null,
      "cognitoIdentityId": null,
      "caller": null,
      "accessKey": null,
      "sourceIp": "127.0.0.1",
      "cognitoAuthenticationType": null,
      "cognitoAuthenticationProvider": null,
      "userArn": null,
      "userAgent": "Custom User Agent String",
      "user": null
    },
    "path": "/",
    "resourcePath": "/",
    "httpMethod": "GET",
    "apiId": "1234567890",
    "protocol": "HTTP/1.1"
  }
}

This is the response:
{
  "statusCode": 401,
  "multiValueHeaders": {
    "Cache-Control": [
      "no-cache, no-store, max-age=0, must-revalidate"
    ],
    "Expires": [
      "0"
    ],
    "Pragma": [
      "no-cache"
    ],
    "Vary": [
      "Origin",
      "Access-Control-Request-Method",
      "Access-Control-Request-Headers"
    ],
    "WWW-Authenticate": [
      "Bearer"
    ],
    "X-Content-Type-Options": [
      "nosniff"
    ],
    "X-Frame-Options": [
      "DENY"
    ],
    "X-XSS-Protection": [
      "1; mode=block"
    ]
  },
  "body": "",
  "isBase64Encoded": false
}

Any help is appreciated.
