### ISSUE TITLE
API Gateway Timeout error

### ISSUE THREAD

**Issue by MounicaRamini** [awslabs/aws-serverless-java-container#295]
Implementations: Spring Boot / AWS Lambda Function/API Gateway

Expected behavior
Should process the requests and give response in 30 seconds when lambda is invoked from API Gateway

Actual behavior
Timeout Error for the first call made from API Gateway and gives response for the calls after

How to avoid timeout error on API Gateway and bring response in <10 seconds when using java framework ? To match time frame of API Gateway, I have increased memory_size of my lambda function to 1472 MB, out of which only 368 MB is used when executed.

@sapessi Could you please give some input on this

**Comment by sapessi** [comment]
Hi @MounicaRamini, are you using Async initialization? Also, looking at the logs, do you have any indication of how long the spring boot application actually takes to start?

**Comment by MounicaRamini** [comment]
Yes, am using Async initialization, and from logs I see what's below

```
16:13:27.941 [main] INFO com.amazonaws.serverless.proxy.AsyncInitializationWrapper - Async initialization will wait for 8863ms
16:13:27.943 [Thread-0] INFO com.amazonaws.serverless.proxy.AsyncInitializationWrapper - Starting async initializer
.
.
.
.
2019-10-16 16:13:36.805 INFO 1 --- [ main] c.a.s.proxy.AsyncInitializationWrapper : Initialization took longer than 10000, setting new CountDownLatch and continuing in event handler
.
.
.
2019-10-16 16:13:46.889 ERROR 1 --- [ main] c.a.s.p.internal.LambdaContainerHandler : Error while handling request

com.amazonaws.serverless.exceptions.ContainerInitializationException: Could not initialize framework within the 10000ms timeout
.
.
.
.
2019-10-16 16:13:46.889 ERROR 1 --- [ main] c.a.s.proxy.AwsProxyExceptionHandler : Called exception handler for:

com.amazonaws.serverless.exceptions.ContainerInitializationException: Could not initialize framework within the 10000ms timeout
.
.
.
.
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)
com.amazonaws.serverless.exceptions.ContainerInitializationException: Could not initialize framework within the 10000ms timeout
.
.
.
.
 Duration: 10132.39 ms Billed Duration: 10200 ms Memory Size: 1728 MB Max Memory Used: 344 MB Init Duration: 9786.61 ms
```

**Comment by sapessi** [comment]
Looks like you are getting into [this branch of the code](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java#L207). By default, the library first waits for 10 seconds for the framework to initialize during Lambda's init time. Then, if the framework initialization took longer than 10 seconds, it returns control to Lambda and waits in the request handling logic for a configurable timeout (`config.getInitializationTimeout()`). By [default](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/ContainerConfig.java#L19), this timeout is an additional 10 seconds. Sounds like your Spring Boot application is taking longer than 20 seconds to start. 

You could work around the issue by increasing the initialization timeout. In your handler, before starting the async initialization, set the configuration property

```java
public class LambdaHandler implements RequestStreamHandler {
    private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    
    public LambdaHandler() {
        try {
            long startTime = Instant.now().toEpochMilli();
            // by setting this value to 20_000 the framework will wait for an additional 20 seconds
            // on top of the default 10 initialization time.
            LambdaContainerHandler.getContainerConfig().setInitializationTimeout(20_000);

            handler = new SpringBootProxyHandlerBuilder()
                    .defaultProxy()
                    .asyncInit(startTime)
                    .springBootApplication(SlowTestApplication.class)
                    .buildAndInitialize();
        } catch (ContainerInitializationException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void handleRequest(InputStream input, OutputStream output, Context context) {
        return handler.proxyStream(input, output, context);
    }
}
```

This may solve your issue. However, I would recommend investigating why the application is taking so long to start and try to reduce that time. The Spring Boot guide includes some [optimization tips](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot#optimizing-cold-start-times).

**Comment by MounicaRamini** [comment]
Thanks, that resolved API Gateway timeout issue

**Comment by MounicaRamini** [comment]
> Looks like you are getting into [this branch of the code](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java#L207). By default, the library first waits for 10 seconds for the framework to initialize during Lambda's init time. Then, if the framework initialization took longer than 10 seconds, it returns control to Lambda and waits in the request handling logic for a configurable timeout (`config.getInitializationTimeout()`). By [default](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/ContainerConfig.java#L19), this timeout is an additional 10 seconds. Sounds like your Spring Boot application is taking longer than 20 seconds to start.
> 
> You could work around the issue by increasing the initialization timeout. In your handler, before starting the async initialization, set the configuration property
> 
> ```java
> public class LambdaHandler implements RequestStreamHandler {
>     private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
>     
>     public LambdaHandler() {
>         try {
>             long startTime = Instant.now().toEpochMilli();
>             // by setting this value to 20_000 the framework will wait for an additional 20 seconds
>             // on top of the default 10 initialization time.
>             LambdaContainerHandler.getContainerConfig().setInitializationTimeout(20_000);
> 
>             handler = new SpringBootProxyHandlerBuilder()
>                     .defaultProxy()
>                     .asyncInit(startTime)
>                     .springBootApplication(SlowTestApplication.class)
>                     .buildAndInitialize();
>         } catch (ContainerInitializationException e) {
>             e.printStackTrace();
>         }
>     }
> 
>     @Override
>     public void handleRequest(InputStream input, OutputStream output, Context context) {
>         return handler.proxyStream(input, output, context);
>     }
> }
> ```
> 
> This may solve your issue. However, I would recommend investigating why the application is taking so long to start and try to reduce that time. The Spring Boot guide includes some [optimization tips](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot#optimizing-cold-start-times).

**Comment by MounicaRamini** [comment]
> > Looks like you are getting into [this branch of the code](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java#L207). By default, the library first waits for 10 seconds for the framework to initialize during Lambda's init time. Then, if the framework initialization took longer than 10 seconds, it returns control to Lambda and waits in the request handling logic for a configurable timeout (`config.getInitializationTimeout()`). By [default](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/ContainerConfig.java#L19), this timeout is an additional 10 seconds. Sounds like your Spring Boot application is taking longer than 20 seconds to start.
> > You could work around the issue by increasing the initialization timeout. In your handler, before starting the async initialization, set the configuration property
> > ```java
> > public class LambdaHandler implements RequestStreamHandler {
> >     private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
> >     
> >     public LambdaHandler() {
> >         try {
> >             long startTime = Instant.now().toEpochMilli();
> >             // by setting this value to 20_000 the framework will wait for an additional 20 seconds
> >             // on top of the default 10 initialization time.
> >             LambdaContainerHandler.getContainerConfig().setInitializationTimeout(20_000);
> > 
> >             handler = new SpringBootProxyHandlerBuilder()
> >                     .defaultProxy()
> >                     .asyncInit(startTime)
> >                     .springBootApplication(SlowTestApplication.class)
> >                     .buildAndInitialize();
> >         } catch (ContainerInitializationException e) {
> >             e.printStackTrace();
> >         }
> >     }
> > 
> >     @Override
> >     public void handleRequest(InputStream input, OutputStream output, Context context) {
> >         return handler.proxyStream(input, output, context);
> >     }
> > }
> > ```
> > 
> > 
> > This may solve your issue. However, I would recommend investigating why the application is taking so long to start and try to reduce that time. The Spring Boot guide includes some [optimization tips](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot#optimizing-cold-start-times).

**Comment by MounicaRamini** [comment]
> Looks like you are getting into [this branch of the code](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java#L207). By default, the library first waits for 10 seconds for the framework to initialize during Lambda's init time. Then, if the framework initialization took longer than 10 seconds, it returns control to Lambda and waits in the request handling logic for a configurable timeout (`config.getInitializationTimeout()`). By [default](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/ContainerConfig.java#L19), this timeout is an additional 10 seconds. Sounds like your Spring Boot application is taking longer than 20 seconds to start.
> 
> You could work around the issue by increasing the initialization timeout. In your handler, before starting the async initialization, set the configuration property
> 
> ```java
> public class LambdaHandler implements RequestStreamHandler {
>     private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
>     
>     public LambdaHandler() {
>         try {
>             long startTime = Instant.now().toEpochMilli();
>             // by setting this value to 20_000 the framework will wait for an additional 20 seconds
>             // on top of the default 10 initialization time.
>             LambdaContainerHandler.getContainerConfig().setInitializationTimeout(20_000);
> 
>             handler = new SpringBootProxyHandlerBuilder()
>                     .defaultProxy()
>                     .asyncInit(startTime)
>                     .springBootApplication(SlowTestApplication.class)
>                     .buildAndInitialize();
>         } catch (ContainerInitializationException e) {
>             e.printStackTrace();
>         }
>     }
> 
>     @Override
>     public void handleRequest(InputStream input, OutputStream output, Context context) {
>         return handler.proxyStream(input, output, context);
>     }
> }
> ```
> 
> This may solve your issue. However, I would recommend investigating why the application is taking so long to start and try to reduce that time. The Spring Boot guide includes some [optimization tips](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot#optimizing-cold-start-times).

Hello @sapessi , I have followed optimization tips and have removed Asynchronuos Initialization Lambda Handler code. I have implemented the below LambdaHandler code with the optimaization tips mentioned in [optimization tips](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot#optimizing-cold-start-times) I still see that JVM takes 22-24 seconds or mostly 30 seconds for initialization and time outs when a request is sent from API Gateway or GUI.

Could you please help me with what can I do here to resolve this

LambdaHandler

`public class LambdaHandler implements RequestStreamHandler {
	
	private static SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
	
	@Override
	public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
			throws IOException {
		if (handler == null) {
			try {
				handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class);
			} catch (ContainerInitializationException e) {
				// if we fail here. We re-throw the exception to force another cold start
				e.printStackTrace();
				throw new RuntimeException("Could not initialize Spring Boot application", e);
			}
		}
		handler.proxyStream(inputStream, outputStream, context);
	}
}
`

**Comment by sapessi** [comment]
You should definitely used the asynchronous initialization handler from the static context or constructor (as per my initial example). Initializing the library from the handler method will cause it to be much slower.

**Comment by MounicaRamini** [comment]
> You should definitely used the asynchronous initialization handler from the static context or constructor (as per my initial example). Initializing the library from the handler method will cause it to be much slower.

Even if I use asynchronous initialization with timeout set to 20000 sec, I still get timeout error for the very first request. For second, third requests, responses are pretty quick

**Comment by MounicaRamini** [comment]
> > You should definitely used the asynchronous initialization handler from the static context or constructor (as per my initial example). Initializing the library from the handler method will cause it to be much slower.
> 
> Even if I use asynchronous initialization with timeout set to 20000 sec, I still get timeout error for the very first request. For second, third requests, responses are pretty quick

**Comment by sapessi** [comment]
Make sure that you start the async initializer from the constructor of your class, not the `handleRequest` method.

**Comment by MounicaRamini** [comment]
> Make sure that you start the async initializer from the constructor of your class, not the `handleRequest` method.

Hello @sapessi , this is what I have followed like you said above and before. But, I still get timeout error with async initialization
```
public class LambdaHandler implements RequestStreamHandler {
	
	private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
	
	public LambdaHandler() {
		
		try{
			long startTime = Instant.now().toEpochMilli();
			LambdaContainerHandler.getContainerConfig().setInitializationTimeout(20_000);
			handler = new SpringBootProxyHandlerBuilder()
					.defaultProxy()
					.asyncInit(startTime)
					.springBootApplication(Application.class)
					.buildAndInitialize();
		}catch (ContainerInitializationException e){
			e.printStackTrace();
		}
	}
	
	@Override
	public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
			throws IOException {
		handler.proxyStream(inputStream, outputStream, context);
	}

}
```

**Comment by sapessi** [comment]
Hi @MounicaRamini, sounds like your Spring app is genuinely taking a really long time to initialize - your options at this point are to either increase the Lambda timeout or reduce the number of dependencies or things that Spring needs to load - perhaps the log will tell you what's taking a long time to load.

**Comment by MounicaRamini** [comment]
@sapessi Thanks for your input

**Comment by sapessi** [comment]
To further address this, we also increased the default async initialization timeout to 20 seconds and made the timeout configurable through the `ContainerConfig` object

**Comment by sapessi** [comment]
Release 1.5 is making its way out to Maven central

**Comment by shaklenahmad** [comment]
hi i am getting error in this section of code  springBootApplication (Line 30).. may i am importing the classes wrong ?can u please help me ?? 


package com.marketplaceupdater.jimintegration;


import com.amazonaws.serverless.exceptions.ContainerInitializationException;
import com.amazonaws.serverless.proxy.internal.LambdaContainerHandler;
import com.amazonaws.serverless.proxy.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler;
import com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestStreamHandler;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.time.Instant;

public class StreamLambdaHandler implements RequestStreamHandler {

    private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;

    public StreamLambdaHandler() {

        try{
            long startTime = Instant.now().toEpochMilli();
            LambdaContainerHandler.getContainerConfig().setInitializationTimeout(20_000);
            handler = new SpringBootProxyHandlerBuilder()
                    .defaultProxy()
                    .asyncInit(startTime)

>                     .springBootApplication(JimIntegrationApplication.class)


                    .buildAndInitialize();
        }catch (ContainerInitializationException e){
            e.printStackTrace();
        }
    }


    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException {

        handler.proxyStream(inputStream, outputStream, context);
    }
}

**Comment by shaklenahmad** [comment]
![Screenshot 2023-03-02 110514](https://user-images.githubusercontent.com/40139587/222342043-2f431f46-b57b-49fd-aacf-9d4c85e54147.png)

**Comment by shaklenahmad** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/40139587/222342403-d4003e4b-fb2f-4a0a-83d1-72252dbb3e73.png)

**Comment by Dasaradharamreddy** [comment]
handler = new SpringBootProxyHandlerBuilder<AwsProxyRequest>()


> ![Screenshot (1)](https://user-images.githubusercontent.com/40139587/222342403-d4003e4b-fb2f-4a0a-83d1-72252dbb3e73.png)
