### ISSUE TITLE
Inyect ServletContext and HttpServletResponse automatically

### ISSUE THREAD

**Issue by ggallotti** [awslabs/aws-serverless-java-container#30]
Having hundrerds of Jersey endpoints where ServletContext and HttpServletResponse is inyected, when using 'aws-serverless-java-container'  I have to modify the code in order to obtain the Servlet context from the Request.

Could be simpler if the ServletContext and HttpServletResponse could be inyected as HttpServletRequest is.

```
@Context
   private ServletContext myContext;
   @Context
   private javax.servlet.http.HttpServletRequest myServletRequest;
   @Context
   private javax.servlet.http.HttpServletResponse myServletResponse;
   @POST
   @Consumes({MediaType.APPLICATION_JSON})
   @Produces({MediaType.APPLICATION_JSON + ";charset=UTF-8"})
   public Response execute( com.awslambdatest.simpletest_RESTInterfaceIN entity )
   {
..
..
}
```

I'm already inyecting HttpServletRequest this way: 
https://github.com/awslabs/aws-serverless-java-container#jersey-servlet-request

**Comment by SAPessi** [comment]
This was fixed in the last commit. Closing this now and will merge into master once I have confirmation that #27 is also resolved.

**Comment by ggallotti** [comment]
It's working. Thanks!
