### ISSUE TITLE
How can I test the spring boot application local like sam build and sam local start-api

### ISSUE THREAD

**Issue by abhinav-jain09** [awslabs/aws-serverless-java-container#310]
* Framework version: XX
* Implementations: Jersey / Spring / Spring Boot / Spark

## Scenario

I downloaded this code but I dont know how to test it locally . something line sam build and then sam local start-api and then run the request from the postman

## Expected behavior
it should be testable from local
## Actual behavior 
sam build needed template.yaml but we have sam.yaml
## Steps to reproduce
download the code and do sam build and it fails saying that no template.yaml found

**Comment by abhinav-jain09** [comment]
i found the solution I must use the --template paramater to specify the template file as sam.yaml

**Comment by sapessi** [comment]
This is related to #293 - we'll use the original issue to track fixes to the sample so that they work out of the box with the SAM cli.
