### ISSUE TITLE
[Question] How can I use Runtime.getRuntime().exec in Lambda

### ISSUE THREAD

**Issue by AlexanderPrendota** [awslabs/aws-serverless-java-container#313]
* Framework version: `com.amazonaws.serverless:aws-serverless-java-container-springboot2:1.4`
* Implementations: Spring Boot 

Hello! Thanks for the great library. 
I use `aws-serverless-java-container` for [compiling and executing Kotlin code](https://github.com/AlexanderPrendota/kotlin-compiler-server).
I need to store .class files in `/tmp` directory and execute the [process](https://github.com/AlexanderPrendota/kotlin-compiler-server/blob/247da86a91e5188fbdb4e9ef17afe25969a5dbab/src/main/kotlin/com/compiler/server/executor/JavaExecutor.kt#L23) with`java -cp ....` 

Is it possible to do this? 

Thank you!

**Comment by AlexanderPrendota** [comment]
I just have problems with java security policy.  
It works, sorry. 
=)

**Comment by sapessi** [comment]
So sorry for the delay in responding. Thanks for the update. Let us know if you have a Kotlin sample you'd like to share

**Comment by AlexanderPrendota** [comment]
Hey @sapessi . Thanks for the answer. Sure, please have a look [at class](https://github.com/AlexanderPrendota/kotlin-compiler-server/blob/master/src/main/kotlin/com/compiler/server/executor/JavaExecutor.kt#L23).

```kotlin
return Runtime.getRuntime().exec(args.toTypedArray()).use { ... }
```

 I use `aws-java-serverless-container` for compiling and executing Kotlin code. Examples [here](https://play.kotlinlang.org/). And it works awesome!

So, but I'm so dissapoited that AWS Lambda still not support streaming. :(
