### ISSUE TITLE
Unable to mvn build sample application

### ISSUE THREAD

**Issue by lyle-partsavatar** [awslabs/aws-serverless-java-container#325]
* Framework version: XX
* Implementations: Spring Boot

## Scenario

Attempting to test Lambda functionality using quick start instructions in wiki.

## Expected behavior

When I run `mvn clean install`, the application should build itself into a jar and/or zip file ready to upload to Lambda.

## Actual behavior

Maven gives the following error on build:

`Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project <artifactId-name>: The packaging for this project did not assign a file to the build artifact -> [Help 1]`

## Steps to reproduce

1. Run the command in the wiki:

```
mvn archetype:generate -DgroupId=my.service -DartifactId=my-service -Dversion=1.0-SNAPSHOT \
       -DarchetypeGroupId=com.amazonaws.serverless.archetypes \
       -DarchetypeArtifactId=aws-serverless-springboot-archetype \
       -DarchetypeVersion=1.4
```

2. cd into the created directory where the pom.xml file is stored.
3. Run `mvn clean install`.

**Comment by sapessi** [comment]
Thanks for the report @lyle-partsavatar - we'll look into it for the next release. Does `mvn clean package` work?

**Comment by lyle-partsavatar** [comment]
Yeah, mvn clean package worked.  Once I read the README and actually did it then it worked XD . Sorry for being dumb.

**Comment by sapessi** [comment]
No problem. I'll leave this issue open to make sure that we fix `mvn install` in the archetypes for the next release.

**Comment by sapessi** [comment]
Switched this to `wontfix` since it doesn't make sense to enable install for applications such as these. We'll update the documentation to clarify that the command is `mvn clean package`.
