### ISSUE TITLE
Java.lang.NullPointerException when implementing basic SpringBoot sample

### ISSUE THREAD

**Issue by venkatmarepalli** [awslabs/aws-serverless-java-container#328]
* Framework version: XX
* Implementations:  Spring Boot

## Scenario
Trying to implement the following basic example
https://github.com/awslabs/aws-serverless-java-container/tree/master/samples/springboot/pet-store

## Expected behavior
When we invoke 
curl -X GET https://6ttodgqe44.execute-api.eu-west-2.amazonaws.com/Prod/pets
Exptected some: <OutputValue>

## Actual behavior
{"message": "Internal server error"}

## Steps to reproduce
Follow the steps here: https://github.com/awslabs/aws-serverless-java-container/tree/master/samples/springboot/pet-store

## Full log output
Exception in thread "main" java.lang.Error: java.lang.NullPointerException
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:65)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)

**Comment by msailes** [comment]
Hi Venkatesh,

I just checked out this code and followed the steps in the README.md. When I executed the curl command you mentioned I got a list of pets. 

Do you have any other information about the error you're having?

**Comment by sapessi** [comment]
Hi @venkatmarepalli - we are trying to reproduce this issue and we need a little bit more information.
* Were you running this in the cloud or with SAM local?
* Can you share your Lambda function configuration? 
* Also some info on the deployment package would be useful (zip or jar? size? any chance you can share the file?)

**Comment by venkatmarepalli** [comment]
Thanks for the quick responses. I tried doing it from a different machine and it is working, I can share the zip file for debugging the issue with the current setup.

[serverless-spring-boot-example-1.0-SNAPSHOT-lambda-package.zip](https://github.com/awslabs/aws-serverless-java-container/files/4319876/serverless-spring-boot-example-1.0-SNAPSHOT-lambda-package.zip)

**Comment by sapessi** [comment]
I couldn't replicate the issue. Please re-open if this happens again @venkatmarepalli  and we'll dig into it further.
