### ISSUE TITLE
When the url contains . and i use @Pathvariable to accept param, it can't work

### ISSUE THREAD

**Issue by davidhua94** [awslabs/aws-serverless-java-container#333]
* Framework version: SpringBoot 2.1.1.RELEASE 、aws-serverless-java-container-spring 1.3.1              
* Implementations: SpringBoot

## Scenario
I used aws ApiGateway and integration with lambda. I use this url to test Https://xxx/{stage}/ping/test.test.test. But i got 
```json
{
    "timestamp": 1586246231077,
    "status": 500,
    "error": "Internal Server Error",
    "message": "File path not allowed: /file.test",
    "path": "/ping/test.test.test"
}
```

## Expected behavior
![image](https://user-images.githubusercontent.com/57469343/78644548-9c679000-78e8-11ea-9293-f14426eaf4b1.png)
It shoud be return 
```json
{
"pong":"test.test.test"
}
```

**Comment by sapessi** [comment]
Hi @davidhua94 - I have added a unit test to replicate this in the next release (branch `v1.5` of this repo) and I couldn't replicate the issue. Can you test with the latest version: `aws-serverless-java-container-springboot2` version 1.4?

**Comment by davidhua94** [comment]
@sapessi  I created a new project using the following script in [Quick Start With Spring Boot2 ](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot2)
```
mvn archetype:generate -DgroupId=my.service -DartifactId=my-service -Dversion=1.0-SNAPSHOT \
       -DarchetypeGroupId=com.amazonaws.serverless.archetypes \
       -DarchetypeArtifactId=aws-serverless-springboot2-archetype \
       -DarchetypeVersion=1.4
```

Only changed the code in PingController
```
@RestController
@EnableWebMvc
public class PingController {
    @RequestMapping(path = "/ping/{message}", method = RequestMethod.GET)
    public Map<String, String> ping(@PathVariable String message) {
        Map<String, String> pong = new HashMap<>();
        pong.put("pong", message);
        return pong;
    }
}
```
It works fine locally， but when i upload the package to AWS Lambda , i got this
![image](https://user-images.githubusercontent.com/57469343/78765721-f769b780-79ba-11ea-9e52-72d3fcbb1ab9.png)

**Is it possible that the configuration of the Api Gateway is incorrect**？

**Comment by sapessi** [comment]
@davidhua94 The 406 status code is returned by Spring when it cannot negotiate the content type for the response. What happens if you send the `Accept` header set to `application/json`?

**Comment by davidhua94** [comment]
@sapessi 
I do a unit test in my.service.StreamLambdaHandlerTest.ping_streamRequest_respondsWithHello()
and change the url to "/ping/test.test.test"
![image](https://user-images.githubusercontent.com/57469343/79035333-156c2d80-7bf0-11ea-9344-df8c49b57762.png)

**Comment by sapessi** [comment]
Do you see the same result if you put a string in the url? The 406 status code means that [the Spring controller is not capable of producing the content type your client requested](https://stackoverflow.com/questions/7462202/spring-json-request-getting-406-not-acceptable). Can you try and specify the `produces = { "application/json" }` in your `@RequestMapping` annotation?

**Comment by davidhua94** [comment]
1. Do you see the same result if you put a string in the url?
change url to  "/ping/hello" and got 200 
![image](https://user-images.githubusercontent.com/57469343/79061348-05bd1980-7cc2-11ea-8961-fc20ee6a06ab.png)

2. Can you try and specify the produces = { "application/json" } in your @RequestMapping annotation?
added produce in @RequestMapping annotation and use url "/ping/test.test.test"
![image](https://user-images.githubusercontent.com/57469343/79061406-9bf13f80-7cc2-11ea-913b-534c4357f79d.png)


![image](https://user-images.githubusercontent.com/57469343/79061411-aa3f5b80-7cc2-11ea-8369-54938d3236cb.png)

**Comment by sapessi** [comment]
I have a unit test replicating this that passes. The commit changes are [here](https://github.com/awslabs/aws-serverless-java-container/commit/778af718151d7d12c82591ea8b9a0056d6224d3c). Are you including the `activation` library? So far as I can tell, When Spring Boot receives a path that could be a file, it first asks the embedded container for the mime type of the file - we use the `activation` library to do this. If it cannot determine the mime type it will not proceed with request processing and assume it failed the content negotiation. Try and add the `activation` dependency and see if it makes a difference. Perhaps we just need to build it into the library:

```xml
<!-- https://mvnrepository.com/artifact/javax.activation/activation -->
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
    <scope>test</scope>
</dependency>
```

**Comment by davidhua94** [comment]
Is the code you tested based on this [Quick Start With Spring Boot2](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot2)，i found that it's a snapshot version.

**Comment by sapessi** [comment]
I've done some debugging and it turns out Spring was failing to route the request altogether. I have sent you a pull request that includes the required Spring configuration to ignore dots in the path.

**Comment by davidhua94** [comment]
@sapessi  I merged your pull request and do a unit test use my.service.StreamLambdaHandlerTest#ping_streamRequest_respondsWithHello(), 406 status disappeared. But i found when url is  ```/ping/test.test.test```,  the response is ```{"pong":"test.test"}```, it should be ```{"pong":"test.test.test"}```

**Comment by sapessi** [comment]
This is inside Spring - seems to be stripping out what it thinks is the extension. perhaps try to declare the message like this "/ping/{message:.*}". I'm no Spring expert so I can be of limited assistance here.

**Comment by davidhua94** [comment]
Thank you anyway. : )

**Comment by onema** [comment]
>I've done some debugging and it turns out Spring was failing to route the request altogether. I have sent you a pull request that includes the required Spring configuration to ignore dots in the path.

@sapessi do you mind sharing what you changed in the PR? the repo is not available anymore and I'm experiencing a similar issue, where `@PathVariables` that contain a `.` in them are not routed to the controller.
