### ISSUE TITLE
[Question] Does `aws-serverless-java-container` support StreamingResponseBody by Spring Boot

### ISSUE THREAD

**Issue by AlexanderPrendota** [awslabs/aws-serverless-java-container#334]
* Framework version: 1.5
* Implementations: Spring / Spring Boot

## Scenario
I would like to compile & execute Java/Kotlin code and use [StreamingResponseBody](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/StreamingResponseBody.html) for the return value form controller.

**Comment by sapessi** [comment]
Hi @AlexanderPrendota - Yes, you can use `StreamingResponseBody`. However, the response won't actually be streamed as AWS Lambda does not support streaming or responses. Instead, the framework should accumulate your output and return from the Lambda function once you actually close the output stream.

**Comment by AlexanderPrendota** [comment]
Thanks for the answer. Do you know, folks from the AWS team have any plans to implement stream responses?

**Comment by sapessi** [comment]
We have received the same feedback from other customers so streaming is already on our list. However, there is no timeline for support. The alternative would be to use API Gateway's WebSockets to push responses to clients. We have an issue open on this framework to explore WebSocket support (#277)

**Comment by AlexanderPrendota** [comment]
It's so sad. will be waiting for streaming on the AWS Lambda side. Thanks for the help!
