### ISSUE TITLE
AwsProxyHttpServletResponseWriter 

### ISSUE THREAD

**Issue by argenstijn** [awslabs/aws-serverless-java-container#339]
* Framework version: XX
* Implementations: Jersey / Spring / Spring Boot / Spark

## Scenario

Lambda in combination with ALB should not use base 64 RFC2045 for encoding binary content

## Expected behavior

 responseString = Base64.getEncoder().encodeToString(containerResponse.getAwsResponseBodyBytes());
                awsProxyResponse.setBase64Encoded(true);

## Actual behavior
Base64.getMimeEncoder().encodeToString(containerResponse.getAwsResponseBodyBytes());
                awsProxyResponse.setBase64Encoded(true);

It;s possible to configure the base 64 encoder to use for creating the response?

**Comment by sapessi** [comment]
Hi @argenstijn - it is not possible today. However, we can add this as a fix for the next release. What is the issue you are running into? What's the output from the ALB?

**Comment by argenstijn** [comment]
you will receive a 502 Bad Gateway.

**Comment by argenstijn** [comment]
by the ALB

**Comment by sapessi** [comment]
I have tested this and for some reason I cannot seem to return binary content from an ALB no matter what I do - even without using the MIME encoder. This works fine with API Gateway. I will check-in with the ALB team to dive deeper on the issue

**Comment by argenstijn** [comment]
Hi, i have a working version. Will add it IT tomorrow.
Cheers mark
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by argenstijn** [comment]
See config below:

/**
 * Same functionality as {@link AwsProxyHttpServletResponseWriter} but uses 
 * the default BASE64 encoder when detecting binary data.
 * 
 */
public class DefaultBase64EncoderAwsProxyHttpServletResponseWriter extends ResponseWriter<AwsHttpServletResponse, AwsProxyResponse> {

    @Override
    public AwsProxyResponse writeResponse(AwsHttpServletResponse containerResponse, Context lambdaContext)
            throws InvalidResponseObjectException {
       
        AwsProxyResponse awsProxyResponse = new AwsProxyResponse();
        if (containerResponse.getAwsResponseBodyString() != null) {
            String responseString;

            if (!isBinary(containerResponse.getContentType()) && isValidUtf8(containerResponse.getAwsResponseBodyBytes())) {
                responseString = containerResponse.getAwsResponseBodyString();
            } else {
                responseString = Base64.getEncoder().encodeToString(containerResponse.getAwsResponseBodyBytes());
                awsProxyResponse.setBase64Encoded(true);
            }

            awsProxyResponse.setBody(responseString);
        }
        awsProxyResponse.setMultiValueHeaders(containerResponse.getAwsResponseHeaders());

        awsProxyResponse.setStatusCode(containerResponse.getStatus());

        if (containerResponse.getAwsProxyRequest().getRequestSource() == AwsProxyRequest.RequestSource.ALB) {
            awsProxyResponse.setStatusDescription(containerResponse.getStatus() + " " + Response.Status.fromStatusCode(containerResponse.getStatus()).getReasonPhrase());
        }
       
        return awsProxyResponse;
    }

    private boolean isBinary(String contentType) {
            
        if(contentType != null) {
            int semidx = contentType.indexOf(';');
            if(semidx >= 0) {
                return LambdaContainerHandler.getContainerConfig().isBinaryContentType(contentType.substring(0, semidx));
            }
            else {
                return LambdaContainerHandler.getContainerConfig().isBinaryContentType(contentType);
            }
        }
        return false;
    }
}

Then you should use this class and make sure that you also add the binary you try to send:

 JerseyLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> newHandler =
        new JerseyLambdaContainerHandler<>(AwsProxyRequest.class, AwsProxyResponse.class,
            new AwsProxyHttpServletRequestReader(),
            new DefaultBase64EncoderAwsProxyHttpServletResponseWriter(),
            new AwsProxySecurityContextWriter(), new AwsProxyExceptionHandler(), app);

 
    newHandler.initialize();  
String[] BINARTY_CONTENT_TYPES = {"application/pdf"};  
    LambdaContainerHandler.getContainerConfig().addBinaryContentTypes(BINARTY_CONTENT_TYPES});    

In this example you should be able to download a PDF

**Comment by sapessi** [comment]
1.5.2 has now hit maven central. Closing this issue.

**Comment by swagsb** [comment]
Hi,

I am still facing this issue using 1.5.2  . My scenario :

I am simply trying to download a zip which has an xml file.  My controller 

 @GetMapping("/downloadZip")
    public void downloadFile(HttpServletResponse response) {

        response.setContentType("application/octet-stream");
        response.setHeader("Content-Disposition", "attachment;filename=download.zip");
        response.setStatus(HttpServletResponse.SC_OK);

        try (ZipOutputStream zippedOut = new ZipOutputStream(response.getOutputStream())) {
                Resource resource = new ClassPathResource("logback.xml");
                ZipEntry e = new ZipEntry(resource.getFilename());
                e.setSize(resource.contentLength());
                e.setTime(System.currentTimeMillis());
                // etc.
                zippedOut.putNextEntry(e);
                // And the content of the resource:
                StreamUtils.copy(resource.getInputStream(), zippedOut);
                zippedOut.closeEntry();

            zippedOut.finish();
        } catch (Exception e) {
            // Exception handling goes here
        }
    }

This downloads the zip fine on local.  On aws , it downloads the zip , but cant extract it . Its corrupted.  Windows says invalid.
I tested it by putting breakpoint on AwsProxyHttpServletResponseWriter , line no 38 , here :
if (!this.isBinary(containerResponse.getContentType()) && this.isValidUtf8(containerResponse.getAwsResponseBodyBytes())) {
                responseString = containerResponse.getAwsResponseBodyString();
            } else {
                responseString = Base64.getEncoder().encodeToString(containerResponse.getAwsResponseBodyBytes());
                awsProxyResponse.setBase64Encoded(true);
            }

I can see that its going to the else block and using Base 64 encoder.  
Any idea why this still doesnt work on ALB ? Should I check this with AWS then ?
