### ISSUE TITLE
Content-Type header in the wrong place during the response

### ISSUE THREAD

**Issue by mbayou** [awslabs/aws-serverless-java-container#344]
* Framework version: 1.5
* Implementations: Spring Boot 2.1.8

## Scenario

A Lambda with a GET resource that returns a list of object. Content-Type is application/json; charset=UTF-8. 

The lambda is behind an API Gateway. /{proxy+}

Do a GET on the resource and get the list of the object as JSON.

## Expected behaviour

Getting the objects with their content as expected.

## Actual behaviour

Everything is working fine until we have strings with "special" characters in it, like this one:
"‘’’’"
we are retrieving this: "ââââ"

After investigation and test with another lambda it appears that the header content-type is set in the `multiValueHeaders ` when it should just be in `headers`

looking at the code of `AwsProxyHttpServletResponseWriter` it seems like there is no possibility to set the header at the right place.

Thank you for your help

**Comment by sapessi** [comment]
Hi @mbayou, this is unlikely to be related to the header field - API Gateway reads the `multiValueHeaders` field in the response just fine. I suspect it may be a bug in the content encoding not using the header value.

[By default, we use `ISO-8859-1` as the charset](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/ContainerConfig.java#L27). Does it work if you change the default charset in the constructor method of your Lambda handler class:

```java
LambdaContainerHandler.getContainerConfig().setDefaultContentCharset("UTF-8");
```

**Comment by mbayou** [comment]
Hi @sapessi ,

**Comment by mbayou** [comment]
Hi @sapessi ,

Thank you this solution is working perfectly!

However, I do think there is a problem [here](https://github.com/awslabs/aws-serverless-java-container/blob/253910f3fb414844db30d22f346783d5ec48a43c/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletResponseWriter.java#L56)

I think we should be able from our code to set the normal headers and not only the multiValueHeaders. We have done multiple tests with a small lambda example and if the content-type is not in the normal header it is being ignored.

**Comment by sapessi** [comment]
It seems to be a bug, but I think the bug is deeper in the stack of this library. I'll leave this open as a bug and dig into it for the next release.

**Comment by sapessi** [comment]
Release `1.5.1` is making its way to maven central and should be available later today. 🚀
