### ISSUE TITLE
API Gateway(lambda integration) + Spring Boot2 serveerless FW => Wrong context path

### ISSUE THREAD

**Issue by 1tkd** [awslabs/aws-serverless-java-container#346]
Framework version: aws-serverless-java-container-springboot2 1.4
Implementations: Spring Boot2 (2.1.8)

## Scenario
Deployed Spring boot2 Web application to API Gateway stage "default".
Accessed http://(host)/default/login

Controller class is like...
```
@Controller
@EnableWebMvc
public class LoginController {	
	@RequestMapping(value = "/login", method = RequestMethod.GET, produces = "text/plain;charset=UTF-8")
	public String getLogin(HttpServletRequest request) {
```

## Expected behavior
In controller class
```
request.getContextPath() => /default
request.getRequestURI() => /default/login
request.getServletPath() => /login
request.getRequestURL()) => http://(host)/default/login
```

## Actual behavior
In controller class
```
equest.getContextPath() => ""
request.getRequestURI() => /login
request.getServletPath() => ""
request.getRequestURL()) => http://(host)/login
```

**Comment by sapessi** [comment]
The `ContainerConfig` object lets you tell the framework to [use the stage as the servlet path](https://github.com/awslabs/aws-serverless-java-container/wiki#container-configuration): `useStageAsServletPath`.

```java
LambdaContainerHandler.getContainerConfig().setUseStageAsServletPath(true);
```

**Comment by 1tkd** [comment]
I'm sorry.
I overlooked the description.
My problem is solved with your answer.
