### ISSUE TITLE
Springboot2 sample returns incorrect content type header when using with ALB

### ISSUE THREAD

**Issue by nytins** [awslabs/aws-serverless-java-container#347]
* Framework version: 1.5
* Implementations: Spring Boot

## Scenario
Create a lambda REST API using aws-serverless-java-container-springboot2 and used it as a target in Application Load Balancer. 

## Expected behavior
Returns response with header `content-type: application/json`.

## Actual behavior
Returns response with header `content-type: application/octet-stream`

## Steps to reproduce
1. Create jar file from the sample springboot2 pet-store applicaton
    mvn clean package -P shaded-jar
1. Deploy this lambda, create a ALB, Target Group and connect to this lambda
1. Invoke with a curl command

**Comment by sapessi** [comment]
@nytins This library only reads/writes the `multiValueHeader` property. Have you [enabled multi-value headers](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#enable-multi-value-headers) in the ALB configuration?

**Comment by nytins** [comment]
@sapessi Oh that was it. It returned the correct `content-type: application/json` header once I enabled multi value headers. Thanks a lot. I will close this as it is not as issue.

**Comment by sapessi** [comment]
Thanks for the update @nytins - I'll keep this open to remind me to update the documentation because this issue comes up quite a bit.

**Comment by sapessi** [comment]
Added an ALB section to the wiki docs. Closing this issue.
