### ISSUE TITLE
ALB Springboot2 mapping failure to post request

### ISSUE THREAD

**Issue by JamesD777** [awslabs/aws-serverless-java-container#348]
* Framework version: version 1.5 on java 8
* Implementations: Spring Boot2

## Scenario

Currently trying to hit an endpoint in a spring boot application on a lambda, through an ALB. I don't see too much in the quickstart about going through an ALB instead of API gateway so I was hoping for some clarification on what I could be missing. 

The request I send is through postman with a json body that the post request uses. The path to is locally is /services/lineage. Through the alb i'm hitting the url <alb cname>/lineage/services/lineage 

## Expected behavior

@PostMapping(value = "lineage", consumes = "application/json", produces = "application/json")
public ResponseEntity<String> elementGenerate(

Sending a request to the above spring controller endpoint. I'd expect it to reach this and run the code.

## Actual behavior
2020-05-13 07:30:06.013 INFO 1 --- [ main] c.a.s.p.internal.LambdaContainerHandler : 127.0.0.1 null- null [13/05/2020:07:30:06Z] "POST /lineage/services/lineage null" 404 - "-" "PostmanRuntime/7.220" combined
## Steps to reproduce
I'm using the current handler code:

import com.amazonaws.serverless.exceptions.ContainerInitializationException;
import com.amazonaws.serverless.proxy.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.springSpringBootLambdaContainerHandler;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestStreamHandler;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class StreamLambdaHandler implements RequestStreamHandler {
  private static SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;

  static {
    try {
      handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(EnvoyLineageApplication.class);
    } catch (ContainerInitializationException e) {
      // if we fail here. We re-throw the exception to force another cold start
      e.printStackTrace();
      throw new RuntimeException("Could not initialize Spring Boot application", e);
    }
  }

  @Override
  public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
      throws IOException {
    handler.proxyStream(inputStream, outputStream, context);
  }
}

## Full log output
2020-05-13 07:30:06.013 INFO 1 --- [ main] c.a.s.p.internal.LambdaContainerHandler : 127.0.0.1 null- null [13/05/2020:07:30:06Z] "POST /lineage/services/lineage null" 404 - "-" "PostmanRuntime/7.220" combined

**Comment by sapessi** [comment]
Is the ALB doing some routing for you? ie. what path is this services associated with on the ALB? You could use the [`stripBasePath` method of `LambdaContainerHandler`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java#L168). For example, if your Spring service expects the request to come to `/lineage`, but the ALB receives a request to `/lineage/services/lineage` and passes that exact path to your application you can use that method to strip out the first `/lineage/services` part.

```java
static {
    try {
        handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(EnvoyLineageApplication.class);
        handler.stripBasePath("/lineage/services");
    } catch (ContainerInitializationException e) {
        // if we fail here. We re-throw the exception to force another cold start
        e.printStackTrace();
        throw new RuntimeException("Could not initialize Spring Boot application", e);
    }
}
```

**Comment by sapessi** [comment]
Closing since we haven't heard back
