### ISSUE TITLE
New thread never executes in AWS Lambda java container

### ISSUE THREAD

**Issue by arsalans** [awslabs/aws-serverless-java-container#350]
* Framework version: aws-serverless-java-container-springboot2 V1.5
* Implementations: Spring Boot

## Scenario
I need to initiate a call back after some time delay. I am able to do it when I run locally on my intellij IDE on Tomcat, but when I deploy to AWS Lambda it doesn't work. I want to do it using executor service (new thread) so that the main thread is not blocked.

## Expected behavior
The new thread runs and provides result.

## Actual behavior
The scheduled call back task never executes.

## Steps to reproduce
Deploy this project [CallBackService](https://github.com/arsalans/ifttt-callbackservice), invoke the requestCallBack request. The code is in CallBackController.

## Full log output
No errors in the log.

**Comment by sapessi** [comment]
Hi @arsalans, AWS Lambda freezes the environment in-between invocations which means it is not possible to execute a background thread. The moment you return from the handler Lambda freezes everything. The equivalent of spawning a background thread in the Serverless world is invoking another Lambda function asynchronously.

**Comment by arsalans** [comment]
@sapessi I was afraid someone is going to say something like that. I was after free cloud hosting that lambda provides, some million calls a month. Any other free hosting ideas on AWS using the free tier where I can run this code?

**Comment by sapessi** [comment]
Have you considered [Fargate](https://aws.amazon.com/fargate/)? Otherwise you could create a separate Lambda function and invoke it with the AWS SDK instead of using a background thread.

**Comment by arsalans** [comment]
Thank you @sapessi, I will close this issue for now.
