### ISSUE TITLE
Missing Fields from Payload Version Format v2.0

### ISSUE THREAD

**Issue by michaeljfazio** [awslabs/aws-serverless-java-container#358]
* Framework version: 1.5
* Implementations: Jersey

## Scenario

Setup Jersey Lambda handler for HttpApiV2 using ```JerseyLambdaContainerHandler.getHttpApiV2ProxyHandler```

Deploy to AWS.
Invoke lambda.

## Expected behavior

Lambda successfully executes for path specified.

## Actual behavior

Jackson deserialization error:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "pathParameters" (class com.amazonaws.serverless.proxy.model.HttpApiV2ProxyRequest), not marked as ignorable (11 known properties: "requestContext", "rawQueryString", "body", "queryStringParameters", "isBase64Encoded", "routeKey", "version", "stageVariables", "rawPath", "cookies", "headers"])
```

## Steps to reproduce

Deploy lambda using ```JerseyLambdaContainerHandler.getHttpApiV2ProxyHandler``` to AWS environment and invoke with valid request via ApiGateway.

**Comment by michaeljfazio** [comment]
HttpApiV2ProxyRequest model does not seem to conform to the actual specification as [documented here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html).

**Comment by sapessi** [comment]
You are 100% right, `pathParameters` is missing. I'll add it to the next patch release. For the time being, I would recommend using the v1 payload. It is still the preferred method because it makes it easy to correctly parse multi-value headers and query string parameters. If you are using SAM, [you can set the payload format version in the configuration](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/jersey/pet-store/template.yml#L25).

**Comment by michaeljfazio** [comment]
> You are 100% right, `pathParameters` is missing. I'll add it to the next patch release. For the time being, I would recommend using the v1 payload. It is still the preferred method because it makes it easy to correctly parse multi-value headers and query string parameters. If you are using SAM, [you can set the payload format version in the configuration](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/jersey/pet-store/template.yml#L25).

No worries. I'm indeed already working around the issue with v1.0 payloads. Thanks @sapessi.

**Comment by sapessi** [comment]
Release `1.5.1` is making its way to maven central and should be available later today. 🚀
