### ISSUE TITLE
ArrayIndexOutOfBounds when parsing query string with no value

### ISSUE THREAD

**Issue by sapessi** [awslabs/aws-serverless-java-container#363]
* Framework version: 1.5
* Implementations: Any

## Scenario
When sending a request that contains a query string parameter with no value `AwsHttpApiV2ProxyHttpServletRequest` throws an `ArrayIndexOutOfBoundsException`

## Expected behavior
Parses the query string correctly and sets a null value for the parameter name

## Steps to reproduce
Create an application that receives a query string parameter behind AWS HTTP APIs and send a request with the parameter, the `=` value separator, and no value:
`curl https://sample-api/params?user=

## Full log output
```
ERROR 1 --- [main] c.a.s.p.internal.LambdaContainerHandler  : Error while handling request
java.lang.ArrayIndexOutOfBoundsException: 1
at com.amazonaws.serverless.proxy.internal.servlet.AwsHttpApiV2ProxyHttpServletRequest.parseRawQueryString(AwsHttpApiV2ProxyHttpServletRequest.java:492)
```

**Comment by srp321** [comment]
@sapessi seems that you already raised and fixed the bug I was opening (which I had reported to AWS support a few hour back).
I'll close the one I had raised.
Also, is there any timeline as to when the fixed version will be available for usage?

**Comment by sapessi** [comment]
Yeah @srp321 - I created this because support contacted me. I hope to have a 1.5.1 path release out today - latest tomorrow. I'll update this issue once it's done.

**Comment by srp321** [comment]
> Yeah @srp321 - I created this because support contacted me. I hope to have a 1.5.1 path release out today - latest tomorrow. I'll update this issue once it's done.

that's great news!
Thanks for the prompt fix

**Comment by sapessi** [comment]
Release `1.5.1` is making its way to maven central and should be available later today. 🚀
