### ISSUE TITLE
Small improvement on Jersey implementation

### ISSUE THREAD

**Issue by argenstijn** [awslabs/aws-serverless-java-container#366]
*Serverless Java Container version*: `1.5.1`

*Implementations:* `Jersey`

*Framework version:* `2.31`

*Frontend service:* `REST API / HTTP API / ALB`

*Deployment method:* `CDK'

## Scenario
It's not better to set these properties to true in order to speed up jersey startup a little bit:

property(ServerProperties.FEATURE_AUTO_DISCOVERY_DISABLE,true);
 property(ServerProperties.WADL_FEATURE_DISABLE,true);
property(ServerProperties.METAINF_SERVICES_LOOKUP_DISABLE,true);
  property(ServerProperties.BV_FEATURE_DISABLE,true);
    property(ServerProperties.JSON_PROCESSING_FEATURE_DISABLE,true);
    property(ServerProperties.MOXY_JSON_FEATURE_DISABLE,true);

**Comment by sapessi** [comment]
Thanks for the tip @argenstijn - I'll make the updates in the archetype and samples for the next release.

**Comment by argenstijn** [comment]
Thanks

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by deki** [comment]
Finally added the properties.
