### ISSUE TITLE
need assistance

### ISSUE THREAD

**Issue by vardans6** [awslabs/aws-serverless-java-container#376]
I am having serverless spring-boot service running in lambda, want to know can I use RDS Database, which is in another aws  account?

Can service access that?

**Comment by sapessi** [comment]
This is not really a question for this forum since it is not related to Serverless Java Container.

You could look into [peering the VPCs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/peer-with-vpc-in-another-account.html).
