### ISSUE TITLE
Response headers not working in HttpAPI PayloadFormat V2 

### ISSUE THREAD

**Issue by lbeuster** [awslabs/aws-serverless-java-container#377]
Currently it seems that the serverless container doesn't really support HttpApi with PayloadFormat V2 (with is the default in HttpApi). All headers (even with V2ProxyHandler) are written into the multiheader field but multiheaders are not supported anymore in V2: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

I could reproduce this with a simple spring-boot2 lambda. And also with a simple non-serverless container lambda using the aws-lambda-java-events:APIGatewayV2HTTPResponse class (which still contains the multiheader field). Headers written to the header field were exposed, multiheaders not.

Best regards
Lars

**Comment by sapessi** [comment]
Hi @lbeuster - are you referring to the response headers? Our [HTTP API request object](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/HttpApiV2ProxyRequest.java) does not have a multivalue headers field.

**Comment by lbeuster** [comment]
Yes, the response headers.

**Comment by sapessi** [comment]
I just checked with the API Gateway team. This is the answer:
* If customer is using 1.0 of the lambda proxy format, api gw reads those on the response.
* If customer is using 2.0 of the lambda proxy format,  api gw does NOT read those on the response.

We'll mark this as a bug and address it with the next release

**Comment by masch712** [comment]
As a workaround, I created an anonymous ResponseWriter instance that concatenates the values in multiHeaderValues with their corresponding header value, if one exists.  Here's how I build my lambda handler:
```java
      handler = new SpringBootProxyHandlerBuilder<HttpApiV2ProxyRequest>()
          .springBootApplication(Blah.class)
          .defaultHttpApiV2Proxy()
          .responseWriter(
              new AwsProxyHttpServletResponseWriter() {
                @Override
                public AwsProxyResponse writeResponse(AwsHttpServletResponse containerResponse,
                    Context lambdaContext) throws InvalidResponseObjectException {
                  final AwsProxyResponse awsProxyResponse = super
                      .writeResponse(containerResponse, lambdaContext);
                  final Headers multiValueHeaders = awsProxyResponse.getMultiValueHeaders();
                  if (multiValueHeaders != null) {
                    Map<String, String> headers;
                    if (awsProxyResponse.getHeaders() == null) {
                      headers = new HashMap<>();
                    } else {
                      headers = awsProxyResponse.getHeaders();
                    }
                    multiValueHeaders.entrySet().forEach(entry -> {
                      headers.compute(entry.getKey(), (key, existingValue) ->
                      {
                        final String commaDelimitedMultiValueHeader = String
                            .join(",", entry.getValue());
                        return existingValue != null && !existingValue.isBlank()
                            ? (existingValue + "," + commaDelimitedMultiValueHeader)
                            : commaDelimitedMultiValueHeader;
                      });
                    });
                    awsProxyResponse.setMultiValueHeaders(null);
                    awsProxyResponse.setHeaders(headers);
                  }
                  return awsProxyResponse;
                }
              }
          )
          .buildAndInitialize();

**Comment by lbeuster** [comment]
Thanks, but payload format version 1.0 is also a good workaround for the moment ;)

**Comment by sapessi** [comment]
1.5.2 has now hit maven central. Closing this issue.
