### ISSUE TITLE
org.springframework:spring-web:5.2.5.RELEASE:jar has vulerabilities, can u plz upgrade spring version

### ISSUE THREAD

**Issue by jabhijeet** [awslabs/aws-serverless-java-container#380]
*To help us debug your issue fill in the basic information below using the options provided*
org.springframework:spring-web:5.2.5.RELEASE:jar has vulerabilities, can u plz upgrade spring version
 https://snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-1009832

*Serverless Java Container version*: `eg. 1.5` 
1.5.1

*Implementations:* `Jersey / Spring / Spring Boot / Spring Boot 2 / Spark`
SpringBoot

*Framework version:* `eg SpringBoot 2.2.6.RELEASE`
SpringBoot 2.2.6.RELEASE

*Frontend service:* `REST API / HTTP API / ALB`
REST
*Deployment method:* `eg SAM, Serverless Framework, Console`

## Scenario
*Describe what you are trying to accomplish*
org.springframework:spring-web:5.2.5.RELEASE:jar has vulerabilities, can u plz upgrade spring version

## Expected behavior
*Describe how you would expect the application to behave*
fixed in pull request https://github.com/awslabs/aws-serverless-java-container/pull/381

## Actual behavior
*Describe what you are seeing instead*

## Steps to reproduce
*Provide code samples we can use to reproduce the issue as part of our integration tests. If there is a public repository for the misbehaving application link to it here*

## Full log output
*Paste the full log output from the Lambda function's CloudWatch logs*

```
logs
```

**Comment by jabhijeet** [comment]
fixed in PR https://github.com/awslabs/aws-serverless-java-container/pull/381

**Comment by sapessi** [comment]
1.5.2 has now hit maven central. Closing this issue.
