### ISSUE TITLE
CLass org.springframework.boot.autoconfigure.cloud.CloudServiceConnectorsAutoConfiguration not found While upgrading spring-boot version to 2.3.X

### ISSUE THREAD

**Issue by sayan22** [awslabs/aws-serverless-java-container#382]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `1.5.1`

*Implementations:* `Spring Boot`

*Framework version:* `SpringBoot 2.3.2.RELEASE`

*Frontend service:* `REST API`

*Deployment method:* `SAM`

## Scenario
I am deploying a spring boot rest application as AWS Lambda with the following pom.xml
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.sam</groupId>
  <artifactId>aws-spring-boot-lambda-api-demo</artifactId>
  <version>1.0.0</version>
  
  <properties>
    <start-class>com.SpringCloudAwsApplication</start-class>
    <spring-cloud>2.2.1.RELEASE</spring-cloud>
    <org.projectlombok.version>1.18.10</org.projectlombok.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>com.amazonaws.serverless</groupId>
      <artifactId>aws-serverless-java-container-springboot2</artifactId>
      <version>1.5.1</version>
    </dependency>
 <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
    </dependency>
     <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-aws</artifactId>
        <version>${spring-cloud}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <profiles>
    <profile>
      <id>boot</id>
      <activation>
        <property>
          <name>boot</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>default</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
              <source>1.8</source>
              <target>1.8</target>
              <annotationProcessorPaths>
                <path>
                  <groupId>org.projectlombok</groupId>
                  <artifactId>lombok</artifactId>
                  <version>${org.projectlombok.version}</version>
                </path>
              </annotationProcessorPaths>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>2.3</version>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
            </configuration>
            <executions>
              <execution>
                <phase>package</phase>
                <goals>
                  <goal>shade</goal>
                </goals>
                <configuration>
                  <artifactSet>
                    <excludes>
                      <exclude>org.apache.tomcat.embed:*</exclude>
                    </excludes>
                  </artifactSet>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
```
Now when I updated the spring-cloud version to 2.2.4.RELEASE from existing 2.2.1.RELEASE, it is not getting deployed any more. it is giving following error.
`java.lang.IllegalStateException: Unable to read meta-data for class org.springframework.boot.autoconfigure.cloud.CloudServiceConnectorsAutoConfiguration
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/boot/autoconfigure/cloud/CloudServiceConnectorsAutoConfiguration.class] cannot be opened because it does not exist`
I guess the issue is with the version. While I am using spring-cloud-aws with version 2.2.1.RELEASE, spring-boot version is 2.2.2.RELEASE. But if I upgrade the spring-cloud-aws to version 2.2.4.RELEASE, spring-boot version becomes 2.3.2.RELEASE and the class **org.springframework.boot.autoconfigure.cloud.CloudServiceConnectorsAutoConfiguration** is no longer exist in spring-boot 2.3.x onwards. Hence the issue.

## Full log output
*java.lang.IllegalStateException: Unable to read meta-data for class org.springframework.boot.autoconfigure.cloud.CloudServiceConnectorsAutoConfiguration
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/boot/autoconfigure/cloud/CloudServiceConnectorsAutoConfiguration.class] cannot be opened because it does not exist*

```
logs
```

**Comment by sapessi** [comment]
Wonder if the class/library is just not getting packaged with the application. Are you using `sam build`? Do you use Gradle or Maven? Can you share your build configuration?

**Comment by sayan22** [comment]
I am deploying a spring boot rest application as AWS Lambda with the following pom.xml
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.sam</groupId>
  <artifactId>aws-spring-boot-lambda-api-demo</artifactId>
  <version>1.0.0</version>
  
  <properties>
    <start-class>com.SpringCloudAwsApplication</start-class>
    <spring-cloud>2.2.1.RELEASE</spring-cloud>
    <org.projectlombok.version>1.18.10</org.projectlombok.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>com.amazonaws.serverless</groupId>
      <artifactId>aws-serverless-java-container-springboot2</artifactId>
      <version>1.5.1</version>
    </dependency>
 <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
    </dependency>
     <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-aws</artifactId>
        <version>${spring-cloud}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <profiles>
    <profile>
      <id>boot</id>
      <activation>
        <property>
          <name>boot</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>default</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
              <source>1.8</source>
              <target>1.8</target>
              <annotationProcessorPaths>
                <path>
                  <groupId>org.projectlombok</groupId>
                  <artifactId>lombok</artifactId>
                  <version>${org.projectlombok.version}</version>
                </path>
              </annotationProcessorPaths>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>2.3</version>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
            </configuration>
            <executions>
              <execution>
                <phase>package</phase>
                <goals>
                  <goal>shade</goal>
                </goals>
                <configuration>
                  <artifactSet>
                    <excludes>
                      <exclude>org.apache.tomcat.embed:*</exclude>
                    </excludes>
                  </artifactSet>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>`
Now when I updated the spring-cloud version to 2.2.4.RELEASE from existing 2.2.1.RELEASE, it is not getting deployed any more. it is giving following error.
 I guess the issue is with the version. While I am using spring-cloud-aws with version 2.2.1.RELEASE, spring-boot version is 2.2.2.RELEASE. But if I upgrade the spring-cloud-aws to version 2.2.4.RELEASE, spring-boot version becomes 2.3.2.RELEASE and the class org.springframework.boot.autoconfigure.cloud.CloudServiceConnectorsAutoConfiguration is no longer exist in spring-boot 2.3.x onwards. Hence the issue.

**Comment by sayan22** [comment]
@sapessi Updated the build configuration above.

**Comment by deki** [comment]
@sayan22 does it work with the latest 1.6 release?

**Comment by deki** [comment]
No further feedback, closing outdated issue. 

We updated to the latest Spring Boot version, most people will use it together with https://awspring.io.
