### ISSUE TITLE
No auto configuration classes found in META-INF/spring.factories. 

### ISSUE THREAD

**Issue by markthegrea** [awslabs/aws-serverless-java-container#384]
Serverless Java Container version*: `eg. 1.5`
*Implementations: Spring Boot 2
*Framework version:SpringBoot 2.3.4.RELEASE`
*Frontend service: HTTP API
*Deployment method: cloud formation

## Scenario
*Get a Rest service running.

## Actual behavior
*Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.*

## Steps to reproduce
I used the instructions you provided and the maven-shade-plugin (vs. 3.2.4)  

java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct. | java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom pac

This is a common problem but what about Lambda?  What Pom.xml should I use?

**Comment by sapessi** [comment]
For Lambda in general I would recommend building a zip file with the assembly plugin. Take a look at [the example](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/springboot2/pet-store/pom.xml#L79-L127), it loads the zip configuration from [the `src/assembly/bin.xml` file](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/springboot2/pet-store/src/assembly/bin.xml)

**Comment by markthegrea** [comment]
Thanks for the tip, but we have never done it that way and we have hundreds of lambdas in prod.  Also, does that take care of the Spring problem?  I have always had trouble using spring without their builder.

**Comment by markthegrea** [comment]
Fixed it with this Pom.xml:

` <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.2.4</version>
        <dependencies>
          <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <version>${spring.version}</version>
          </dependency>
        </dependencies>
        <configuration>
          <createDependencyReducedPom>false</createDependencyReducedPom>
          <filters>
            <filter>
              <artifact>*:*</artifact>
              <excludes>
                <exclude>**/Log4j2Plugins.dat</exclude>
              </excludes>
            </filter>
          </filters>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer
                  implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/spring.handlers</resource>
                </transformer>
                <transformer
                  implementation="org.springframework.boot.maven.PropertiesMergingResourceTransformer">
                  <resource>META-INF/spring.factories</resource>
                </transformer>
                <transformer
                  implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/spring.schemas</resource>
                </transformer>
                <transformer
                  implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
              </transformers>
              <artifactSet>
                <excludes>
                  <exclude>org.apache.tomcat.embed:*</exclude>
                </excludes>
              </artifactSet>
            </configuration>
          </execution>
        </executions>
      </plugin>`
