### ISSUE TITLE
Field "path" not in AwsProxyRequest

### ISSUE THREAD

**Issue by davidmco65** [awslabs/aws-serverless-java-container#39]
When trying to deserialize the AwsProxyRequest within a StreamHandler-derived class, I get:

`Unrecognized field "path" (class com.amazonaws.serverless.proxy.internal.model.ApiGatewayRequestContext), not marked as ignorable (9 known properties: "resourcePath", "apiId", "accountId", "resourceId", "requestId", "identity", "httpMethod", "stage", "authorizer"])
`
From:

`AwsProxyRequest request = mapper.readValue(input, AwsProxyRequest.class);`

Thanks,
David

**Comment by SAPessi** [comment]
Fixed with the latest pull request. This will go out with 0.6
