### ISSUE TITLE
Actuator not working in default project generated by MVN command

### ISSUE THREAD

**Issue by jabhijeet** [awslabs/aws-serverless-java-container#390]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `1.5.2`

*Implementations:* `Spring Boot 2` 

*Framework version:* `SpringBoot 2.2.9.RELEASE`

*Frontend service:* `ALB`

*Deployment method:* `Console`

## Scenario
Trying to enable actuator in spring boot

## Expected behavior
<alb-path>/actuator/<info/health> should work

## Actual behavior
404 response on actuator URLs

## Steps to reproduce
https://github.com/jabhijeet/aws-lambda-springboot
upload built jar to s3 
point lambda to this jar
alb should have lambda as target group
hit actuator urls

## Full log output
2020-10-15 04:59:58.499  WARN 1 --- [           main] o.s.web.servlet.PageNotFound             : No mapping for GET /actuator/info

```
logs
```

**Comment by deki** [comment]
Hi @jabhijeet,
I just noticed no one responded so far, sorry for the late reply. Looking at your GitHub project you are missing the `spring-boot-starter-actuator` dependency (documented here https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.enabling). I added it and received a response afterwards.

Feel free to reopen this issue if you need additional support.
