### ISSUE TITLE
asyncInit() stopped working on release 1.5

### ISSUE THREAD

**Issue by vinilanzoni** [awslabs/aws-serverless-java-container#391]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `1.5`

*Implementations:* `Spring Boot 2`

*Framework version:* `SpringBoot 2.2.7.RELEASE`

*Frontend service:* `HTTP API`

*Deployment method:* `CloudFormation`

## Scenario
I'm trying to implement a new application using SpringBoot 2.2.7. But when I use `asyncInit()` i get the error `Cannot resolve method 'springBootApplication' in 'ServletLambdaContainerHandlerBuilder'`

```
                ContainerConfig lambdaContainerConfig = LambdaContainerHandler.getContainerConfig();
                lambdaContainerConfig.setInitializationTimeout(20_000);
                lambdaContainerConfig.setDefaultContentCharset(StandardCharsets.UTF_8.name());
                // For applications that take longer than 10 seconds to start, use the async builder:
                long startTime = Instant.now().toEpochMilli();
                handler = new SpringBootProxyHandlerBuilder()
                        .defaultProxy()
                        .asyncInit()
                        .springBootApplication(Application.class)         // Here I get the error Cannot resolve method 'springBootApplication' in 'ServletLambdaContainerHandlerBuilder'
                        .buildAndInitialize();
```
This only happens when I use version **1.5**, when I downgrade to **1.4** the error stop showing. 
`asyncInit()` returns `ServletLambdaContainerHandlerBuilder` on version **1.5** but on version **1.4** it returns `SpringBootProxyProxyHandlerBuilder`.
Furthermore, why `asyncInit(Long startTime)` is deprecated on version greater than **1.5**?

## Expected behavior
Not showing error `Cannot resolve method 'springBootApplication' in 'ServletLambdaContainerHandlerBuilder'`

**Comment by Y00sh00** [comment]
I'm running into similar issues.

**Comment by jabhijeet** [comment]
i am using 1.5.2 and no issues there

**Comment by Intelligent2013** [comment]
I have this issue for both 1.5 and 1.5.2.

COMPILATION ERROR :
```
my.example.StreamLambdaHandler.java:[37,17] cannot find symbol
  symbol:   method springBootApplication(java.lang.Class<my.example.Application>)
  location: class com.amazonaws.serverless.proxy.internal.servlet.ServletLambdaContainerHandlerBuilder
```

From pom.xml:
```xml
        <dependency>
            <groupId>com.amazonaws.serverless</groupId>
            <artifactId>aws-serverless-java-container-spring</artifactId>
            <version>1.5.2</version>
        </dependency>
```

I get the source code from https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot#asynchronous-initialization

**Comment by deki** [comment]
Fixed code sample and wiki documentation
