### ISSUE TITLE
Remove dependency to Apache HttpCore

### ISSUE THREAD

**Issue by joain946** [awslabs/aws-serverless-java-container#394]
*Serverless Java Container version*: `1.5.2`

*Implementations:* `Jersey`

*Framework version:* `Jersey 2.30.1`

*Frontend service:* `HTTP API`

*Deployment method:* `SAM`

## Scenario
I want to minimize the number of dependencies used by my Lambda. Apache HttpCore is used in four classes, three of these are only used for testing. The fourth class is the `AwsHttpServletRequest` which only instantiates one class from Apache HttpCore but never uses it: https://github.com/awslabs/aws-serverless-java-container/blob/4380cc05fb96ccc61f8a76ff6f6381bb3ab75260/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java#L110

## Expected behavior
I want to be able to exclude Apache HttpCode ("httpcomponents-core") in my pom file.

## Actual behavior
The class is needed.

**Comment by deki** [comment]
Thanks for reporting this issue. For now I've removed the unused `BasicHeaderValueParser` and marked the dependency as optional in the pom.
In the future we could move `AwsProxyRequestBuilder` to a separate test-jar.
