### ISSUE TITLE
Missing Fields from Payload Version Format v2.0

### ISSUE THREAD

**Issue by rockey5520** [awslabs/aws-serverless-java-container#409]
Framework version: 1.5.2
Implementations: Spring Boot 2
Scenario
Setup springboot Lambda handler for HttpApiV2 using SpringBootLambdaContainerHandler.getHttpApiV2ProxyHandler

Deploy to AWS.
Invoke lambda.

Expected behavior
Lambda successfully executes for resource specified.

Actual behavior
Jackson deserialization error:

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "resource" (class com.amazonaws.serverless.proxy.model.HttpApiV2ProxyRequest), not marked as ignorable (12 known properties: "requestContext", "rawQueryString", "body", "queryStringParameters", "isBase64Encoded", "routeKey", "version", "stageVariables", "rawPath", "cookies", "headers", "pathParameters"])

Steps to reproduce
Deploy lambda using JerseyLambdaContainerHandler.getHttpApiV2ProxyHandler to AWS environment and invoke with valid request via ApiGateway.

Full log output

**Comment by srp321** [comment]
@rockey5520 what's the trigger to your lambda?

**Comment by rockey5520** [comment]
This lambda is wired to http API gateway for invocation

**Comment by srp321** [comment]
HttpApiV2ProxyRequest request model only accepts requests coming from the API gateway of type HTTP and will always throw this exception when the request is coming from any other source.

**Comment by rockey5520** [comment]
But requests are made via http in my case

**Comment by srp321** [comment]
use any logger/converter and check what data is coming to the lambda in the input stream, it might help.
Additionally, just to be sure check the payload version that u are setting when defining in apigw

**Comment by deki** [comment]
I agree with @srp321, see https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html for Payload version 2.0 and 1.0. Resource sounds like version 1.0 and in this case `getHttpApiV2ProxyHandler` is the wrong method.
Therefore I'm closing this issue for now, feel free to reopen with additional information.
