### ISSUE TITLE
Provide example of using raw HttpServletRequest

### ISSUE THREAD

**Issue by dmcg** [awslabs/aws-serverless-java-container#41]
I'm trying to work out how to have a raw service(httpServletRequest, httpServletResponse) lambda method called. There is no documentation to help!

**Comment by SAPessi** [comment]
What do you mean by raw service? Are you using Spring, Jersey, or Spark?

**Comment by dmcg** [comment]
None of these. I was assuming that I'd be able to map service() of an HttpServlet as the lambda handler and have it called with an HttpServletRequest

**Comment by SAPessi** [comment]
The library is not a full implementation of the servlet specs - it's just meant to act as a wrapper for spring, jersey, or spark applications. 

Technically you could use the core objects to receive an `AwsProxyRequest` event, instantiate a new `AwsProxyHttpServletRequest` from it, and then pass it in directly to your servlet. However, you should not expect the servlet context and filters to work.

**Comment by dmcg** [comment]
I appreciate that large chunks of the servlet spec are not there - just looking for a route (no pun intended) to have my code run in either Jetty or Lambda. Thanks for the pointer.
