### ISSUE TITLE
Support for Spark 2.6.0

### ISSUE THREAD

**Issue by SAPessi** [awslabs/aws-serverless-java-container#42]
There are some breaking changes in the embedded server interface.

**Comment by mkjois** [comment]
For reference, their changelog is here: http://sparkjava.com/news#spark-26-released

**Comment by dmcg** [comment]
Should you be looking for inspiration, this would be a really useful feature for us!

**Comment by SAPessi** [comment]
@dmcg I'll try to make this available in 0.6 at the end of the month. I'll start testing next week.

**Comment by SAPessi** [comment]
@dmcg @mkjois I've looked through the changes, they are minor but still breaking. I have two options:
1. Upgrade to spark 2.6.0 for all
2. Add a new module specifically for spark2.6.0

What would your preference be?

**Comment by mkjois** [comment]
My preference would be to upgrade to spark 2.6.0 for all, either in version 0.6 or 0.7.

I can understand option 2 but if you do go with it I think this module should continue to mature with Spark, while you can introduce a new module for staying with 2.5.3

**Comment by SAPessi** [comment]
Thanks @mkjois - I will publish 0.6 as is since I have a bug fix for the servlet specs that should be included in all releases. From 0.7-SNAPSHOT I will upgrade to spark 2.6.0 for all.

**Comment by SAPessi** [comment]
Hey @mkjois, I just pushed a commit to the `spark-upgrade` branch that supports 2.6.0. If you get a chance, can you give it a try?

**Comment by SAPessi** [comment]
Merged upgraded changes into master. Closing this issue.

**Comment by mkjois** [comment]
@SAPessi Sorry didn't get to test, I'm pretty swamped at work this week.

Thanks for the upgrade though! Might want to update the readme with a note about these versions as well

**Comment by helloalleo** [comment]
Could you provide an example?

**Comment by helloalleo** [comment]
Nevermind. I got it working the problem which I got was in included `compile 'com.sparkjava:spark-debug-tools:0.5'`

**Comment by SAPessi** [comment]
hey @helloalleo, what problem were you running into? Was there a specific exception?

**Comment by helloalleo** [comment]
I got this error when included `compile 'com.sparkjava:spark-debug-tools:0.5'`

```spark.SparkInstance cannot be cast to spark.Service: java.lang.ClassCastException
java.lang.ClassCastException: spark.SparkInstance cannot be cast to spark.Service
at com.amazonaws.serverless.proxy.spark.SparkLambdaContainerHandler.<init>(SparkLambdaContainerHandler.java:120)
at com.amazonaws.serverless.proxy.spark.SparkLambdaContainerHandler.getAwsProxyHandler(SparkLambdaContainerHandler.java:92)
at com.workingbit.article.LambdaHandler.handleRequest(LambdaHandler.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```
