### ISSUE TITLE
com.amazonaws.serverless.proxy.internal.servlet.AwsHttpServletRequest constructor is package private

### ISSUE THREAD

**Issue by adrian-baker** [awslabs/aws-serverless-java-container#422]
Based on the comments in this class, I believe it's intended to have protected access, which would allow it to be extended by classes outside this package (eg if implementing custom request/response data types other than API GW requests).

**Comment by deki** [comment]
Hi Adrian,
sorry for the late feedback. We can change it to protected. Do you want to create a PR for this? Otherwise I can make the change.

**Comment by deki** [comment]
I've just commited the change, will be part of the next release.
