### ISSUE TITLE
AwsServletContext requiring Context in ctor is a pain

### ISSUE THREAD

**Issue by dmcg** [awslabs/aws-serverless-java-container#44]
I know that this isn't your use-case, but...

... I'm using the Servlet interfaces to build a binding between Lambda and web-abstractions that overlay routing on top of a single servlet.

So I need an AwsServletContext to pass to the init() of their servlet. But I can't have one until the first request is made, because AwsServletContext needs Context. But only for logging, which doesn't seem a good coupling to me.

Could you break this dependency somehow?

**Comment by SAPessi** [comment]
Yes, this is definitely on the cards for release 0.6 - it will come together with #21

**Comment by dmcg** [comment]
Excellent, I'll close this given #21

**Comment by SAPessi** [comment]
@dmcg Better late than never, I've addressed this in the latest commit. it's on the `servlet-improvements` branch
