### ISSUE TITLE
Help: Is this specifically for creating APIs

### ISSUE THREAD

**Issue by ShyamVeerapallyTR** [awslabs/aws-serverless-java-container#466]
Hi,
   I am looking to integrate an existing spring boot project with lambda and the intention is to invoke one of the methods present in the spring boot project from the requesthandler class and not to expose any API end points.  Can we use this aws serverless java container for that purpose?

Ex: Something like as below

public class App implements RequestHandler<Input, Output> {

    public Output handleRequest(final Input input, final Context context) {
        //Call the class that is present in spring boot project directly and no APIs like restcontroller methods.
         return  myspringbootclass.method(); 
    }
}

And also looks like there is spring cloud function available. Just wondering which one would work better for this specific scenario.

https://spring.io/projects/spring-cloud-function

Thanks,
Shyam

**Comment by deki** [comment]
Hi Shyam,
how do you plan to trigger/ invoke the Lambda function?

**Comment by deki** [comment]
@ShyamVeerapallyTR can you please share more information or close this if you no longer need advise?

**Comment by ShyamVeerapallyTR** [comment]
@deki : We are planning to invoke the lambda function through step function.

**Comment by deki** [comment]
@ShyamVeerapallyTR ok in this case you don't need to wrap into http but should rather work with event objects directly. Spring Cloud Functions is the better choice for this.

You can also check a related new workshop that we run with customers: https://catalog.workshops.aws/java-on-aws-lambda/en-US/01-migration/02-optimizations/handler

Let me know if you have other questions.

**Comment by ShyamVeerapallyTR** [comment]
@deki That's the question that I had when I initially did the research and spring cloud function looked to be better. Thanks for confirmation and providing the related link.
