### ISSUE TITLE
Understanding API Gateway Lambda Proxy versions - Gateway using V1, serverless java container uses V2?

### ISSUE THREAD

**Issue by v79** [awslabs/aws-serverless-java-container#467]
I am attempting to implement a simple lambda function using Javalin 4.6.4 (from #425), but I think my problem isn't related to Javalin. Using version 1.8.2 of the java container.

I have set up a simple API Gateway resource, GET "/", and have enabled "Use Lambda Proxy Integration". It calls my Lambda function. But the proxy cannot deserialise the request, with this exception:

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "resource" (class com.amazonaws.serverless.proxy.model.HttpApiV2ProxyRequest), not marked as ignorable (12 known properties: "requestContext", "rawQueryString", "body", "queryStringParameters", "isBase64Encoded", "routeKey", "version", "stageVariables", "rawPath", "cookies", "headers", "pathParameters"])
```

I can see clearly that the `HttpApiV2ProxyRequest` class doesn't have a `resource` field.

But the API Gateway Documentation clearly states that the API Gateway Lambda Proxy integration does have a `resource` field, and others too: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

```json
{
  "version": "1.0",
  "resource": "/my/path",
  "path": "/my/path",
  "httpMethod": "GET",
  "headers": {
    "header1": "value1",
    "header2": "value2"
  },
//... etc
```

I think it's a version problem - but I've no idea why API Gateway is using version 1.0. Of course, if I turn off Lambda Proxy Integration, nothing works there either:

```
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid HTTP API v2 proxy request
```

I'm sure it's my error, I just don't know how to fix it.

**Comment by v79** [comment]
Ah. I had chosen "REST" API because all my other lambdas are on REST APIs, and it describes it as working for "Lambda, HTTP, AWS Services" - definitely a cooler, longer list than the "HTTP API" option.

V2 is much less overtly helpful than V1. Deployed and I think I have a route, but GET / returns an Internal Server Error and the logs show this:

```
{
    "requestId": "VAyFqhInrPEEJVA=",
    "ip": "92.233.89.72",
    "requestTime": "09/Jul/2022:18:34:12 +0000",
    "httpMethod": "GET",
    "routeKey": "GET /{proxy+}",
    "status": "500",
    "protocol": "HTTP/1.1",
    "responseLength": "35"
}
```

Does that look right?

**Comment by v79** [comment]
I think I prefer V1, but it's (probably) working now. Closing this.

**Comment by deki** [comment]
Hi @v79,
we are supporting both V1 and V2 so you can pick whatever you prefer (see https://github.com/awslabs/aws-serverless-java-container/wiki#lambda-handler-classes).
