### ISSUE TITLE
graalvm-lambda-build Not Found

### ISSUE THREAD

**Issue by urmichm** [awslabs/aws-serverless-java-container#468]
*Docker Not Found*

## Scenario
running
```
./docker-build.sh
```

## Expected behaviour
*Build the docker*

## Actual behavior
*Unable to find image graalvm-lambda-build*
## Full log output

```
Unable to find image 'graalvm-lambda-build:latest' locally
docker: Error response from daemon: pull access denied for graalvm-lambda-build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**Comment by urmichm** [comment]
please inform if there is an alternative docker image to be used

**Comment by deki** [comment]
Hi @urmichm,
I assume you are referring to the Micronaut pet-store sample. This one is outdated so it's best to pick a different example until we updated it. This one may help you: https://github.com/aws-samples/serverless-java-frameworks-samples/tree/main/micronaut

Best,
Dennis

**Comment by urmichm** [comment]
Thank you very much

**Comment by urmichm** [comment]
@deki 
Thank you again for your response. I have followed your advice, but face a different issue with building graalvm native. Could you please have a look at this issue?
https://github.com/aws-samples/serverless-java-frameworks-samples/issues/4
