### ISSUE TITLE
Is it any way to inject bean to rest controller?

### ISSUE THREAD

**Issue by andrii142** [awslabs/aws-serverless-java-container#47]
Got out of memory error as it is now

**Comment by SAPessi** [comment]
I assume you are talking about Spring. This should work normally. Java (and Spring) are pretty memory hungry, if you look at the Lambda logs it should tell you how much memory it consumed, what do you see there? Have you tried to increase the memory available to the Lambda function?

**Comment by SAPessi** [comment]
Did increasing the amount of memory available to the function help? Can I close this issue?

**Comment by SAPessi** [comment]
I'm closing this issue since we haven't heard back in 27 days
