### ISSUE TITLE
Contributing a version compatible with the Jakarta namespace

### ISSUE THREAD

**Issue by farazhv** [awslabs/aws-serverless-java-container#477]
*Implementations:* `Jersey`

*Frontend service:* `HTTP API / ALB`

*Deployment method:* `SAM`

## Scenario
*Describe what you are trying to accomplish*

We have upgraded the AWS Serverless Java Container library and it is now compatible with the Jakarta namespace. However, we have not been able to implement the multipart functionality. We would like to contribute this work.

**Comment by deki** [comment]
@farazhv great to hear that, that will be definitely helpful for other users as well. Can you create a pull request with your changes?

**Comment by dsvensson** [comment]
Significant parts of the Java echo system have moved forward towards Jakarta by now. Dropwizard, JOOQ, hibernate and the list goes on. Would be great so see this PR merged and released. Some, but not all, projects have opted for providing two major versions during a transition window, one with javax, and one with jakarta to not have to think about compatibility.

**Comment by deki** [comment]
Absolutely, we are already working on it.
