### ISSUE TITLE
Spring Boot 2 sample is broken

### ISSUE THREAD

**Issue by taasjord** [awslabs/aws-serverless-java-container#484]
*Serverless Java Container version*: `1.9`

*Implementations:* `Spring Boot 2`

In commit https://github.com/awslabs/aws-serverless-java-container/commit/0b92c8ec9c6d8955ee6e311e668282a754d80d7d the API gateway and stack output was commented out, replaced by function URL. 

Problems:
1) Readme/deploy instructions and sample code no longer matching. 
2) Attempting to call the function URL results in "Internal server error" and exception:
`com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer`

While I was able to fix it by uncommenting the template resources, but not a pleasant sample application experience testing this for the first time. I don't know if the intention was to actually change to function URLs, but it looks like some code needs to be changed as well.

**Comment by deki** [comment]
Of course, samples must always work :-)
