### ISSUE TITLE
UnsupportedOperationException on addMappingForServletNames following the Spring Boot 2 sample

### ISSUE THREAD

**Issue by lancekf** [awslabs/aws-serverless-java-container#485]
*Serverless Java Container version*: `1.9`

*Implementations:* `Spring Boot 2`

*Framework version:* `SpringBoot 2.7.5.RELEASE`

*Frontend service:* `ALB`

*Deployment method:* `Console`

## Scenario
Following the sample for Spring Boot 2 with the exception of using the SAM CLI which isn't available for use within my company. I am building manually and am confident in the final artifact as the appropriate handler is executed.

## Expected behavior
1. Follow Spring Boot 2 sample
2. Build with `mvn package`
3. Upload with `aws lambda update-function-code ...`
4. Browse to `/`
5. Content at `/` is returned to the browser

## Actual behavior
1. Follow Spring Boot 2 sample
2. Build with `mvn package`
3. Upload with `aws lambda update-function-code ...`
4. Browse to `/`
5. Timeout due to buried `UnsupportedOperationException`

## Steps to reproduce
1. Follow Spring Boot 2 sample
2. Build with `mvn package`
3. Upload with `aws lambda update-function-code ...`
4. Browse to `/`

## Full log output
Unfortunately I'm doing this at work and my company doesn't allow pasting snippets to the internet, however the stack trace follows:

```
Error loading class <>.StreamLambdaHandler: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
...
Caused by: ApplicationContextException: Unable to start web server; nested exception is java.lang.UnsupportedOperationException
....
Caused by: UnsupportedOperationException
    at FilterHolder$Registration.addMappingForServletNames(FilterHolder.java:281)
```

It appears that addMappingForServletNames() simply throws UnsupportedOperationException(). Should that method even be getting called? If no, any clues as to where I've gone wrong from the sample?

**Comment by deki** [comment]
Hi @lancekf,
thanks for reporting this issue. I'm unable to reproduce it so far. 

* How did you create the Lambda function and the API-Gateway? Can you please share all commands to reproduce it from scratch?
* What happens if you make a request to `/pets`? Do you see the same issue there?
* In addition could you please add a full stack trace to see where `addMappingForServletNames` is called (if it's not shown, you could add logging using `Thread.currentThread().getStackTrace()` before `throw new UnsupportedOperationException();`)?

**Comment by lancekf** [comment]
Hi @deki, thanks for the reply.

> * How did you create the Lambda function and the API-Gateway? Can you please share all commands to reproduce it from scratch?

This is an ALB and Lambda created via Terraform modules supplied by my company. For testing, I've been sending ALB request events directly to the Lambda as modeled here: https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html

> * What happens if you make a request to `/pets`? Do you see the same issue there?

Yes.

> * In addition could you please add a full stack trace to see where `addMappingForServletNames` is called (if it's not shown, you could add logging using `Thread.currentThread().getStackTrace()` before `throw new UnsupportedOperationException();`)?

Unfortunately I can't provide a full stack trace as I'm posting this from my personal machine. I did realize yesterday the calling method prior to `addMappingForServletNames()` would've been helpful but then got sidetracked and forgot to add it... that is:
```
Caused by: UnsupportedOperationException: null
    at FilterHolder$Registration.addMappingForServletNames(FilterHolder.java:281)
    at AbstractFilterRegistrationBean.configure(AbstractFilterRegistrationBean:242)
    at AbstractFilterRegistrationBean.configure(AbstractFilterRegistrationBean:46)
```

Some of the differences with my setup I should point out:
1. I'm not using the `CognitoIdentifyFilter`. I've commented out the `handler.onStartup()` registration.
2. I'm packaging this according to a standard maven layout within my company, however this layout still includes using the maven-shade-plugin to create a shaded jar. Would a packaging issue be causing it to blow up on the servlet configuration?
3. I'm deploying my jar to the Lambda using the aws lambda CLI instead of the SAM CLI. I don't think this is a problem.'

Thanks again!

**Comment by lancekf** [comment]
FWIW, I tried adding in the assembly-zip profile from the sample, uploaded the created zip, and... same issue :confused:

**Comment by deki** [comment]
Hmm can you find out which filter is triggering the registration?

I also did a deployment using AWS CLI this morning and it worked fine. Used API-Gateway and not ALB though, need to rerun my test.

**Comment by lancekf** [comment]
> Hmm can you find out which filter is triggering the registration?

I think you're on to something here... I'm not the best at deciphering spring output but I believe it's trying to load these filters:
```
corsFilter
excludeFontVaryHeaderFilter
mdcFilter
dispatcherPerfLoggingFilter servlets=[dispatcherServlet]
requestLoggingFilter servlets=[dispatcherServlet, jerseyServlet]
requestContextFilter
```
Some of these are no doubt from some auto configuration applied by the standard project layout from my company that I'm using... my guess is it's a problem with the filters that have servlets=[] associated with them and I need to figure out how to disable them? Very much appreciate your help!

**Comment by lancekf** [comment]
Yep, I managed to disable those logging filters and I can now GET a 200 from /pets, however I get an empty response body:
```
{
    "statusCode": 200,
    "statusDescription": "200 OK",
    "multiValueHeaders": (),
    "body": "",
    "isBase64Encoded": false
}
```

So that's a new problem... for the original filter registration issue, could there be any improvements to aws-serverless-java-container to better handle that? Ex. somehow check to see if any filters are registered for a servlet and unregister the servlet or disable the filter?

**Comment by lancekf** [comment]
Coming back to the new problem... I've disabled all autoconfiguration and I'm still only getting an empty response body at GET /pets. I don't think it's mapping the request to the PetsController at all... I do see this at startup:
```
servlet.HandlerMapping.Mappins:
PetsController:
{GET [/pets/{petId}]}: listPets()
{GET [/pets]}: listPets(Optional, Principal)
{POST [/pets]}: createPet(Pet)
```

... but I'm seeing no indication that the request is actually processed through that controller. Which part of code is responsible for scanning for any `@RestController` endpoints?

**Comment by lancekf** [comment]
Okay, so in addition to disabling some autoconfiguration, I also used the assembly zip packaging from the sample, and that seems to work. I still have lots of things to figure out with this setup and I'm happy to contribute how I can but please feel free to close this as a non-issue. Thank you very much for your time!

**Comment by deki** [comment]
Ok, let me know if there is something that we can improve to streamline the experience.
