### ISSUE TITLE
Add ELB Context to HttpApiV2Request

### ISSUE THREAD

**Issue by driverpt** [awslabs/aws-serverless-java-container#489]
*Serverless Java Container version*: `1.9`

*Implementations:* `Micronaut`

*Framework version:* `Micronaut AWS master branch`

*Frontend service:* `HTTP API / ALB`

*Deployment method:* SAM`

## Scenario
*Describe what you are trying to accomplish*
Implement https://github.com/micronaut-projects/micronaut-aws/issues/1317

## Expected behavior
Payload V2 working with both HTTP API and ALB

## Actual behavior
Cannot differentiate HTTP API from ALB Request via `requestContext`

## Steps to reproduce
N/A

## Full log output
N/A

**Comment by driverpt** [comment]
cc @msailes

**Comment by deki** [comment]
Released as part of version 1.9.1.
