### ISSUE TITLE
 Web application could not be started as there was no ...ServletWebServerFactory bean defined in the context.

### ISSUE THREAD

**Issue by urmichm** [awslabs/aws-serverless-java-container#490]
Has anyone faced this issue? Would appreciate some help here, please :) 

## Local run output
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Web application could not be started as there was no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

Action:

Check your application's dependencies for a supported servlet web server.
Check the configured web application type.


Process finished with exit code 1
```

**Comment by urmichm** [comment]
@deki thank you for your reply, I guess I got a common issue with a simple fix, but I am blind to see it. 

I am using SpringBoot2, this [quick start](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot2)

## Scenario
I just try to run springboot locally using IntelliJ.  I am just expecting to run the project on localhost. It is easy for debugging and local tests.

## Actual behaviour
It fails. The logs are below, the problem as I see no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

## Steps to reproduce
I might misconfigured something or incorrectly set up InteliJ. All the steps I did is _Maven archetype_ from a quick start above.

## Logs

```
2022-12-05 18:29:53.448  WARN 20371 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.context.MissingWebServerFactoryBeanException: No qualifying bean of type 'org.springframework.boot.web.servlet.server.ServletWebServerFactory' available: Unable to start AnnotationConfigServletWebServerApplicationContext due to missing ServletWebServerFactory bean
2022-12-05 18:29:53.486 ERROR 20371 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web application could not be started as there was no org.springframework.boot.web.servlet.server.ServletWebServerFactory bean defined in the context.

Action:

Check your application's dependencies for a supported servlet web server.
Check the configured web application type.


Process finished with exit code 1

```
 
I shall note that ```sam local start-api``` and Unit Tests are running fine.

**Comment by deki** [comment]
Alright, thanks for adding the details. If you want to run locally, you need to remove the exclusions for embedded tomcat because otherwise there is no server environment to run on.

**Comment by urmichm** [comment]
I thought about it too. 
I commented the exclusion in the pom.xml file as below
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.springframework.boot</groupId>-->
<!--                    <artifactId>spring-boot-starter-tomcat</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
        </dependency>
```
Unfortunately, it did not help.
I also tried to comment the exclusion in the _shaded-jar_ but I think it is not related since this profile is not a default one. 

Am I missing something here ?

**Comment by deki** [comment]
Exactly, it's enough to just remove that exclusion. In IDEs like IntelliJ you need to make sure that dependencies are reloaded.
As an alternative you can run it from the command line using `mvn spring-boot:run`
I just tried both options using the pet-store sample and it's working.

**Comment by urmichm** [comment]
```
mvn spring-boot:run
```
works fine, i believe the problem was with my Run Configurations in InteliJ
