### ISSUE TITLE
Spring Boot 3 Support

### ISSUE THREAD

**Issue by h1alexbel** [awslabs/aws-serverless-java-container#493]
Is there will be Spring Boot 3 support?

**Comment by deki** [comment]
Thanks for your question. Please follow the existing issue #487.

**Comment by deki** [comment]
If you are looking to run Spring Boot 3 on Lambda before we finish the work on this issue, this sample may be helpful for you: https://github.com/maschnetwork/aws-lambda-spring-boot-3
