### ISSUE TITLE
There is a Dependency convergence within your project

### ISSUE THREAD

**Issue by franciscodominguez** [awslabs/aws-serverless-java-container#50]
I am working with your jersey samples and I have been notices some Dependency convergence issues:
Dependency convergence error for javax.ws.rs:javax.ws.rs-api:2.1-m01 paths to dependency are:
  +-com.amazonaws.serverless:aws-serverless-java-container-jersey:0.5.1
    +-com.amazonaws.serverless:aws-serverless-java-container-core:0.5.1
      +-javax.ws.rs:javax.ws.rs-api:2.1-m01
and
  +-com.amazonaws.serverless:aws-serverless-java-container-jersey:0.5.1
    +-org.glassfish.jersey.core:jersey-server:2.24
      +-org.glassfish.jersey.core:jersey-client:2.24
        +-javax.ws.rs:javax.ws.rs-api:2.0.1
and
+-com.sunrun.fem.interval:fem-interval-rest:1.0.0-SNAPSHOT
  +-com.amazonaws.serverless:aws-serverless-java-container-jersey:0.5.1
    +-org.glassfish.jersey.core:jersey-server:2.24
      +-javax.ws.rs:javax.ws.rs-api:2.0.1

I think it would be fixed if in your https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/pom.xml#L36e

would refer to version: 
```
<dependency>
    <groupId>javax.ws.rs</groupId>
    <artifactId>javax.ws.rs-api</artifactId>
    <version>2.1-m05</version>
</dependency>
```
and  if the following line would refer to the library:
https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/pom.xml#L19
```
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-client</artifactId>
    <version>2.26-b03</version>
</dependency>
```
there are also some Dependency convergence issues with the samples as well. I will submit an issue if i can find a simple solution. The latest version does not work since org.glassfish.hk2.api.Factory is no longer present.

**Comment by SAPessi** [comment]
Thanks. I'll fix this for the next commit!

**Comment by franciscodominguez** [comment]
@SAPessi 
i updated my comment. The latest version does not work since org.glassfish.hk2.api.Factory is no longer present. I have not done the research to figure out the migration path for that class.

**Comment by franciscodominguez** [comment]
@SAPessi 
upgrading past 2.26-b03 could be problematic as the org.glassfish.hk2:hk2-api is no longer org.glassfish.jersey.core:jersey-server it is just a separate jar. I tried just including the latest hk2-api as a dependency but that failed. you may not want to change this until the direction of jersey is solidified.

**Comment by SAPessi** [comment]
I'm rolling the core back to re-api:2.0.1 - and updating jersey to 2.25.1. Once Jersey2.26 is out of beta I will update all dependencies and add support.

**Comment by SAPessi** [comment]
Addressed in the latest commit. If you have time try and clone 0.6-SNAPSHOT from the `servlet-improvements` branch and let me know if it works for you

**Comment by SAPessi** [comment]
Resolving this and about to merge changes into master
