### ISSUE TITLE
Feature Request - Allow to run locally 

### ISSUE THREAD

**Issue by eranation** [awslabs/aws-serverless-java-container#54]
I managed to make it run on Tomcat as a WAR file with some playing with maven profiles, but it's not exactly the same as the ApiGatewayRequestContext is not available in an offline / local war deployment. It will be nice if there was a built in way to run the app locally as a Spring application with similar RequestContext behavior as in a lambda deployment.

**Comment by SAPessi** [comment]
@eranation I'm wondering if we should do some research on how to run applications written with this library using the new sam-local: https://github.com/awslabs/aws-sam-local - what do you think?

**Comment by mkbrv** [comment]
For the Spring Boot project I easily made a new submodule with a simple class and a dependency to my lambda module. The class looks like: 

```
@EnableAutoConfiguration
@ComponentScan("com.xxx.xxx.xxx.xxx")
public class XXXAppplication {

    public static void main(String[] args) {
        SpringApplication.run(XXXAppplication.class, args);
    }

}

```
I also added a dependency to spring boot so I can run it from the main in a tomcat: 
```
  <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>1.5.6.RELEASE</version>
        </dependency>
```

It works just fine.

**Comment by SAPessi** [comment]
All 3 supported frameworks can be started locally with an embedded container, this allows you to test your application. To emulate API Gateway and Lambda's behavior you are definitely better off using the [aws-sam-local](https://github.com/awslabs/aws-sam-local) project. The sample applications included in this repo have a basic SAM template you can just re-use.

I'm closing this issue for now.
