### ISSUE TITLE
Update archetypes to use JUnit 5

### ISSUE THREAD

**Issue by deki** [awslabs/aws-serverless-java-container#561]
The archetypes are still using an old JUnit version, see Jersey for example:
https://github.com/awslabs/aws-serverless-java-container/blob/660dd8dbf88298bf31cc604b574ac283f2558fa2/aws-serverless-jersey-archetype/src/main/resources/archetype-resources/pom.xml#L68
https://github.com/awslabs/aws-serverless-java-container/blob/660dd8dbf88298bf31cc604b574ac283f2558fa2/aws-serverless-jersey-archetype/src/main/resources/archetype-resources/build.gradle#L24

The dependency declarations and StreamLambdaHandlerTest classes should be updated to use JUnit 5.

**Comment by salmansharifov** [comment]
Hi @deki. can I take this issue?

**Comment by deki** [comment]
Sure, looking forward to your contribution!
