### ISSUE TITLE
Spring exception message missing in API gateway response

### ISSUE THREAD

**Issue by Fefbug** [awslabs/aws-serverless-java-container#57]
Hi,
When you throw an exception with @ResponseStatus(value = HttpStatus.INTERNAL_SERVER_ERROR) annotation.
API gateway answer with the right status code but the exception message is gone.

sample code to reproduce :
```
@RestController
@EnableWebMvc
class MyController {
   @RequestMapping(path = "Hello", method = RequestMethod.GET)
    public void coucou() {
        throw new YourException("Hello");
    }
}

@ResponseStatus(value = HttpStatus.INTERNAL_SERVER_ERROR)
public class YourException extends RuntimeException {
    public YourException(String message) {
        super(message);
    }
}

```

**Comment by SAPessi** [comment]
Thanks @Fefbug - I'll investigate this week and give you an update here.

**Comment by SAPessi** [comment]
Hey @Fefbug, I've looked into this and the library is doing the right thing, it never receives a body from Spring. Unless you declare an exception handler, Spring will only set the status code in the response and not the body. Take a look at the [tutorial here](http://www.baeldung.com/exception-handling-for-rest-with-spring).

This is a decent exception handler sample for a REST API:

```java
@ControllerAdvice
class ExceptionHandlerAdvice {
    @ExceptionHandler
    @ResponseBody
    ResponseEntity<SingleValueModel> handle(Exception exception) {
        SingleValueModel body = new SingleValueModel();
        body.setValue(resolveAnnotatedExceptionReason(exception));
        HttpStatus responseStatus = resolveAnnotatedResponseStatus(exception);
        return new ResponseEntity<>(body, responseStatus);
    }

    HttpStatus resolveAnnotatedResponseStatus(Exception exception) {
        ResponseStatus annotation = findMergedAnnotation(exception.getClass(), ResponseStatus.class);
        if (annotation != null) {
            return annotation.value();
        }
        return HttpStatus.INTERNAL_SERVER_ERROR;
    }

    String resolveAnnotatedExceptionReason(Exception exception) {
        ResponseStatus annotation = findMergedAnnotation(exception.getClass(), ResponseStatus.class);
        if (annotation != null && !"".equals(annotation.reason())) {
            return annotation.reason();
        }
        return exception.getLocalizedMessage();
    }
}
```

I've added a unit test to the spring implementation that uses this exception handler to make sure the output is correct.

**Comment by Fefbug** [comment]
I just try your sample it works like a charm !
I close the issue Thanks!

**Comment by SAPessi** [comment]
Great. Thanks @Fefbug - only one more thing to pay attention to, the `@ExceptionHandler` annotation can receive a list of classes. My recommendation would be to specify which custom exception classes you want to handle with this and let Spring deal with the rest with its default settings.
