### ISSUE TITLE
Urgent help needed pls - Lambda handler issue

### ISSUE THREAD

**Issue by JonathanGladwin** [awslabs/aws-serverless-java-container#604]
Hi Everyone,

 I’m working on spring boot service deploying as AWS lambda function. I am trying to deploy my simple (which has 2 end points) spring boot service into lambda. I am facing issue after deploying in lambda. Pls help me. As I recently saw that you wrote lot of sample GitHub deploying spring boot on lambda.

Could you pls help me to solve this? As it’s high priority for me to immediately complete for my company. I am already too late.

I explained the issue in detail here:

https://stackoverflow.com/questions/76577207/spring-boot-deployed-in-lambda-throws-nosuchmethoderror

Appreciate your help.

**Comment by deki** [comment]
Hi Jonathan,
if it's that urgent it's probably best to go through your AWS contact and schedule a call with one of our experts. In case you don't have a contact yet, you can also go through: https://aws.amazon.com/contact-us/

We'll take a look at your post anyway...

**Comment by deki** [comment]
Closing as per comment on Stackoverflow (wrong dependency version was in use).
