### ISSUE TITLE
Jersey HttpServletResponse Injection

### ISSUE THREAD

**Issue by ScottWinkler** [awslabs/aws-serverless-java-container#62]
From the docs, I can inject an HttpServletRequest using the following:
```
ResourceConfig app = new ResourceConfig()
    .packages("com.amazonaws.serverless.proxy.test.jersey")
    .register(new AbstractBinder() {
        @Override
        protected void configure() {
            bindFactory(AwsProxyServletRequestFactory.class)
                .to(HttpServletRequest.class)
                .in(RequestScoped.class);
            bindFactory(AwsProxyServletContextFactory.class)
                .to(ServletContext.class)
                .in(RequestScoped.class);
        }
    });
```

And I can access the HttpServletRequest using:
```
@Path("/my-servlet") @GET
public String echoServletHeaders(@Context HttpServletRequest context) {
    Enumeration<String> headerNames = context.getHeaderNames();
    while (headerNames.hasMoreElements()) {
        String headerName = headerNames.nextElement();
    }
    return "servlet";
}
```

However, I have not found a way to inject the HttpServletResponse. It would be nice to bind a factory method like:

```
bindFactory(AwsProxyServletResponseFactory.class)
                .to(HttpServletResponse.class)
                .in(RequestScoped.class);
```

So that I can access the HttpServletResponse using the @Context object, e.g. something like: 

```
@Path("/my-servlet") @GET
public String echoServletHeaders(@Context HttpServletRequest request, @Context HttpServletResponse) {
//stuff
}
```

If this is not possible, is there another way to inject the HttpServletResponse? I tried using the @Context above the @Path, but the HttpServletResponse always returns null. Here is a snippet of what I tried:

```
@Context private ServletContext myContext;
    @Context private HttpServletResponse httpResponse;
    @Path("/saml")
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public Response processSAML(@Context HttpServletRequest httpRequest) {
//httpResponse is null
```

**Comment by SAPessi** [comment]
Hi @ScottWinkler, at the moment we only have a Factory implementation for the [request](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/factory/AwsProxyServletRequestFactory.java) and [context](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/factory/AwsProxyServletContextFactory.java) objects. I can definitely look at adding one for the servlet response. I'll mark this issue as an enhancement and look into it in the next few days.

**Comment by SAPessi** [comment]
This is merged into master and have added a unit test for it.
