### ISSUE TITLE
HTTP API is supported?

### ISSUE THREAD

**Issue by seanlee10** [awslabs/aws-serverless-java-container#692]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `aws-serverless-java-container-springboot3:2.0.0-M2`

*Implementations:* `Spring Boot`

*Framework version:* `SpringBoot 3.0.6.RELEASE`

*Frontend service:* `HTTP API`

*Deployment method:* `CLI`

## Scenario
I want to use Amazon API Gateway HTTP API to invoke a lambda function wrapped in a StreamLambdaHandler

## Expected behavior
200 OK

## Actual behavior
```
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
```

## Steps to reproduce
You create a lambda function and integrate it with both REST API and HTTP API. 
REST API works as expected but HTTP API returns `{"message":"Internal Server Error"}` and when I dig through the logs I find 
```
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
```

## Full log output
```
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
```

**Comment by deki** [comment]
Hello @seanlee10,
HTTP APIs are supported. In your `StreamLambdaHandler` you need to change the code to `getHttpApiV2ProxyHandler` as described here: https://github.com/awslabs/aws-serverless-java-container/wiki#lambda-handler-classes

**Comment by seanlee10** [comment]
> Hello @seanlee10, HTTP APIs are supported. In your `StreamLambdaHandler` you need to change the code to `getHttpApiV2ProxyHandler` as described here: https://github.com/awslabs/aws-serverless-java-container/wiki#lambda-handler-classes

OMG it was right there in the documentation. thank you so much for your guidance!
