### ISSUE TITLE
Spring Boot is not handling the request

### ISSUE THREAD

**Issue by jordiperendreu** [awslabs/aws-serverless-java-container#72]
Hi,

I followed the documentation about Spring Boot, I have:

LambdaHandler:
```
public class LambdaHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {
    SpringLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler

    private static final Logger LOG = Logger.getLogger(LambdaHandler.class);

    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        LOG.info("received: " + awsProxyRequest.dump());
        return handler.proxy(awsProxyRequest, context);
    }

    public LambdaHandler(){
        long milis = System.currentTimeMillis()
        SpringApplication springBootApplication = new SpringApplication(AppsApplication.class);
        springBootApplication.setWebEnvironment(false);
        springBootApplication.setBannerMode(Banner.Mode.OFF);

        // create a new empty context and set the spring boot application as a parent of it
        ConfigurableWebApplicationContext wrappingContext = new AnnotationConfigWebApplicationContext();
        wrappingContext.setParent(springBootApplication.run());

        // now we can initialize the framework with the wrapping context
        handler = SpringLambdaContainerHandler.getAwsProxyHandler(wrappingContext);
        LOG.info("Loading time: " + (System.currentTimeMillis()-milis) )
    }
}
```

My controller code:
```
@RequestMapping("/apps/{id}")
public App getApp(@PathVariable String id) {
        appService.get(id)
        return appService.get(id)
}
```

I get on logs:
`2017-10-25 18:23:29.361  WARN 20596 --- [           main] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/apps/1] in DispatcherServlet with name 'aws-servless-java-container'`

But removing: springBootApplication.setWebEnvironment(false);

I have on logs:
`2017-10-25 18:23:28.644  INFO 20596 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/apps/{id}]}" onto public AppController.getApp(java.lang.String)`

And it's working, any help?

Thank you!

**Comment by SAPessi** [comment]
Hi @jordiperendreu, we have added a [SpringBootLambdaContainerHandler](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringBootLambdaContainerHandler.java) in the latest release, can you try with this object?

**Comment by axdsilva** [comment]
I have also being trying to use it.

@jordiperendreu when I removed springBootApplication.setWebEnvironment(false : I got the following exception: 


**Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.: org.springframework.context.ApplicationContextException
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)**

@SAPessi  I tried using the https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringBootLambdaContainerHandler.java but I got the initial issue of not being able to have my service uri mapped.

**Comment by axdsilva** [comment]
Here is my Lambda handler code:

package com.nike.pdh.test.lambda;

import com.amazonaws.serverless.exceptions.ContainerInitializationException;
import com.amazonaws.serverless.proxy.internal.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.internal.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.spring.SpringLambdaContainerHandler;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.nike.pdh.test.TestApplication;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.web.context.ConfigurableWebApplicationContext;
import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;

/**
 * Created by adsil2 on 12/18/17.
 */
public class LambdaHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {
    private SpringLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    private Logger log = LoggerFactory.getLogger(LambdaHandler .class);


    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        if (handler == null) {
            try {

                SpringApplication springBootApplication = new SpringApplication(TestApplication.class);
 //               springBootApplication.setWebEnvironment(false);
                springBootApplication.setBannerMode(Banner.Mode.OFF);

                ConfigurableWebApplicationContext wrappingContext = new AnnotationConfigWebApplicationContext();
                wrappingContext.setParent(springBootApplication.run());


                handler = SpringLambdaContainerHandler.getAwsProxyHandler(wrappingContext);

         //       handler = SpringLambdaContainerHandler.getAwsProxyHandler(TestApplication.class);


            } catch (ContainerInitializationException e) {
                log.error("Cannot initialize spring handler in lambda", e);
                return null;
            }
        }
        return handler.proxy(awsProxyRequest, context);
    }
}

**Comment by axdsilva** [comment]
`package com.nike.pdh.test.lambda;

import com.amazonaws.serverless.exceptions.ContainerInitializationException;
import com.amazonaws.serverless.proxy.internal.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.internal.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.spring.SpringLambdaContainerHandler;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.nike.pdh.test.TestApplication;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.web.context.ConfigurableWebApplicationContext;
import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;

/**
 * Created by adsil2 on 12/18/17.
 */
public class LambdaHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {
    private SpringLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    private Logger log = LoggerFactory.getLogger(LambdaHandler .class);


    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        if (handler == null) {
            try {

                SpringApplication springBootApplication = new SpringApplication(TestApplication.class);
 //               springBootApplication.setWebEnvironment(false);
                springBootApplication.setBannerMode(Banner.Mode.OFF);

                ConfigurableWebApplicationContext wrappingContext = new AnnotationConfigWebApplicationContext();
                wrappingContext.setParent(springBootApplication.run());


                handler = SpringLambdaContainerHandler.getAwsProxyHandler(wrappingContext);

         //       handler = SpringLambdaContainerHandler.getAwsProxyHandler(TestApplication.class);


            } catch (ContainerInitializationException e) {
                log.error("Cannot initialize spring handler in lambda", e);
                return null;
            }
        }
        return handler.proxy(awsProxyRequest, context);
    }
}`

**Comment by axdsilva** [comment]
```
package com.nike.pdh.test.lambda;

import com.amazonaws.serverless.exceptions.ContainerInitializationException;
import com.amazonaws.serverless.proxy.internal.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.internal.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.spring.SpringLambdaContainerHandler;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.nike.pdh.test.TestApplication;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.web.context.ConfigurableWebApplicationContext;
import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;

/**
 * Created by adsil2 on 12/18/17.
 */
public class LambdaHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {
    private SpringLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    private Logger log = LoggerFactory.getLogger(LambdaHandler .class);


    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        if (handler == null) {
            try {

                SpringApplication springBootApplication = new SpringApplication(TestApplication.class);
 //               springBootApplication.setWebEnvironment(false);
                springBootApplication.setBannerMode(Banner.Mode.OFF);

                ConfigurableWebApplicationContext wrappingContext = new AnnotationConfigWebApplicationContext();
                wrappingContext.setParent(springBootApplication.run());


                handler = SpringLambdaContainerHandler.getAwsProxyHandler(wrappingContext);

         //       handler = SpringLambdaContainerHandler.getAwsProxyHandler(TestApplication.class);


            } catch (ContainerInitializationException e) {
                log.error("Cannot initialize spring handler in lambda", e);
                return null;
            }
        }
        return handler.proxy(awsProxyRequest, context);
    }
}
```

**Comment by axdsilva** [comment]
Here is the latest code I have --still not working with 0.8
```
package com.nike.pdh.test.lambda;

import com.amazonaws.serverless.proxy.internal.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.internal.model.AwsProxyResponse;
import com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.nike.pdh.test.TestApplication;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Created by adsil2 on 12/18/17.
 */
public class LambdaHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {

    private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    private Logger log = LoggerFactory.getLogger(LambdaHandler.class);

    public LambdaHandler() throws Exception {
        /*
        long milis = System.currentTimeMillis();
        SpringApplication springBootApplication = new SpringApplication(TestApplication.class);
        springBootApplication.setWebEnvironment(false);
        springBootApplication.setBannerMode(Banner.Mode.OFF);
        
        // create a new empty context and set the spring boot application as a parent of it
        ConfigurableWebApplicationContext wrappingContext = new AnnotationConfigWebApplicationContext();
        wrappingContext.setParent(springBootApplication.run());
        
        // now we can initialize the framework with the wrapping context
        handler = SpringLambdaContainerHandler.getAwsProxyHandler(wrappingContext);
        */
        handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(TestApplication.class);
//        log.info("Loading time: " + (System.currentTimeMillis() - milis));
    }

    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        log.info("received: " + awsProxyRequest);
        return handler.proxy(awsProxyRequest, context);
    }


}
```

**Comment by axdsilva** [comment]
Here is my sprint boot application:
```
package com.nike.pdh.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.support.SpringBootServletInitializer;

@SpringBootApplication
public class TestApplication extends SpringBootServletInitializer {

	public static void main(String[] args) {
		SpringApplication.run(TestApplication.class, args);
	}

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(TestApplication.class);
	}
}
```

**Comment by axdsilva** [comment]
Here is the controller

```
package com.nike.pdh.test;

import com.nike.pdh.test.web.TestProcessor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * Created by adsil2 on 9/7/17.
 */

@RestController
@RequestMapping(value = "/v1")
public class TestController {


    private Logger log = LoggerFactory.getLogger(TestController.class);

    @Autowired
    TestProcessor testProcessor;

    @RequestMapping(value = "/echo", produces = {"application/json"}, method = RequestMethod.GET)
    public ResponseEntity<String> echo ( @RequestParam("input1") String input1, @RequestParam("input2") String input2) {



        String output = testProcessor.generateOutput(input1,input2);


        log.info(" Invoke the restful application controller: " + output);


        return new ResponseEntity<String>(output, HttpStatus.OK);

    }

	@GetMapping(value = "/add", produces = {"application/json"})
	public ResponseEntity<String> add ( @RequestParam("num1") String num1,  @RequestParam("num2") String num2) {

		int sum = Integer.parseInt(num1) + Integer.parseInt(num2);

        String output = "Sum of the numbers is " + sum;

        return new ResponseEntity<String>(output, HttpStatus.OK);

    }


}
```

**Comment by adsil2** [comment]
I got my stuff to work. I chnaged from building lambda from a shadow jar to a zip and it worked just fine. Please ignore the above.... Nice work on this.

**Comment by SAPessi** [comment]
Closing this issue.
