### ISSUE TITLE
Spring Boot unable to load ServletContext

### ISSUE THREAD

**Issue by HRHDaniel** [awslabs/aws-serverless-java-container#73]
Taking the PetStore example and updating it with the suggestions from the readme to launch spring-boot, the springBootApplication.run() line continues to fail with "A ServletContext is required to configure default servlet handling".  I've tried multiple various configurations and continue to get this exception.  Could we get a working example of spring-boot included in the checked in examples?

**Comment by SAPessi** [comment]
Thanks Daniel, I will add a spring boot-specific sample soon!

**Comment by SAPessi** [comment]
Hey @HRHDaniel, have you tried the [SpringBootLambdaContainerHandler](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringBootLambdaContainerHandler.java)?

**Comment by axdsilva** [comment]
@SAPessi  Can you please add a springboot working sample please? This is great functionality if it works as intended.

**Comment by SAPessi** [comment]
New spring boot sample is ready. In the `servlet-improvements` branch at the moment but will merge into master soon.
