### ISSUE TITLE
Spring "Model" not being loaded

### ISSUE THREAD

**Issue by Bart1909** [awslabs/aws-serverless-java-container#78]
I'm trying to move my Spring MVC application to lambda. 
I've got a method:
`
@RequestMapping(value = "/saveFavorites", method = RequestMethod.POST)
public String action(Model model, HttpServletResponse response, @ModelAttribute("favoritenForm") FavoritenForm favoritenForm,@CookieValue(value = "myApplicationCookie", defaultValue = "") String token) 
throws JsonParseException, JsonMappingException, ClientProtocolException, UnsupportedEncodingException, IOException { 
//code
return "redirect:/favorites";
}
`

But the method is not being invoked, I think, that depends on the parameters.

Someone know a solution for this?

Thanks

Tobi

**Comment by SAPessi** [comment]
Hi @Bart1909, can you confirm that the Lambda function is executed (check CloudWatch logs)? Are there no exceptions in the logs?

Couple things I would look at first:
1. Exceptions in CW Logs
2. Make sure that the integration configuration between API Gateway and Lambda is set to proxy

If you find an exception please share it here.

**Comment by SAPessi** [comment]
Hey @Bart1909, any update on this?

**Comment by Bart1909** [comment]
Hi @SAPessi,

the problem was solved. I had some missing dependencies in my pom.xml

Now it is working fine!

**Comment by SAPessi** [comment]
Great to hear! Thanks!
