### ISSUE TITLE
SpringBootLambdaContainerHandler doesn't set the contextPath

### ISSUE THREAD

**Issue by agibalov** [awslabs/aws-serverless-java-container#84]
Spring provides [a nice mechanism to build URLs](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/MvcUriComponentsBuilder.html) by referencing controller classes and their handler methods:

```
URI personUri = fromMethodCall(on(PersonsController.class)
  .getPerson(123))
  .build().toUri();
```

Internally, this mechanism relies on the current `ServletRequest` and namely its `getContextPath()` method.

I see that while my `AwsProxyRequest` has these details:

* `getPath(): /hello`
* `getRequestContext().getPath(): /Dummy/hello`
* `getResource(): /{proxy+}`

`SpringBootLambdaContainerHandler` creates the `ServletRequest` object like this:

* `getPathInfo(): /hello`
* `getPathTranslated(): null`
* `getContextPath(): `
* `getServletPath(): /hello`
* `getServletContext().getContextPath(): /`

As a result, when I build the URL, the API Gateway's "stage" part is lost ("Dummy" is a stage) and instead of `http://apigw/Dummy/hello`, I get `http://apigw/hello`.

We're using `aws-serverless-java-container-spring:0.8` with `spring-boot-starter-web:1.5.3.RELEASE`.

**Comment by SAPessi** [comment]
Thanks for the feedback @loki2302 - I believe older versions of the library set the content path from the stage. We removed this because it was causing issues in other places. I'll test again to figure out what was happening, if possible I'll add the stage back in the context path.

**Comment by SAPessi** [comment]
Hey @agibalov, I went back to explore this. The reason why I stayed away from including the stage name in the path is that stages don't necessarily map to servlets. Further, if you configure a custom domain name in API Gateway and point it directly to a stage the base path goes away. One change I'm contemplating is:

1. Include the stage name as the context path
2. Include the actual request path only in the PathInfo

With these changes, you will need to set the strip base path and base path properties in the [`ContainerConfig`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/ContainerConfig.java) object to make it work with custom domain names - from the Lambda function I have no information on what the endpoint uri is.

**Comment by SAPessi** [comment]
I've looked a bit deeper into this. There is no easy way for me to claim that the context path is the stage (see custom domain name issue above). Instead, I'm relying on the `ContainerConfig` object to tell me whether the stage should be included or not in the context path, same story for the base path you can strip. The `getContextPath()` method changes to:

```java
@Override
public String getContextPath() {
    if (config.isUseStageAsServletContext()) {
        String contextPath = cleanUri(request.getRequestContext().getStage());
        if (config.getServiceBasePath() != null) {
            contextPath += cleanUri(config.getServiceBasePath());
        }

        return contextPath;
    } else {
        return "" + (config.getServiceBasePath() != null ? cleanUri(config.getServiceBasePath()) : "");
    }
}
```

To get the desired effect, you can initialize the container handler with:

```java
SpringLambdaContainerHandler.getContainerConfig().setUseStageAsServletContext(true);

AwsProxyResponse output = handler.proxy(request, lambdaContext);
```

**Comment by SAPessi** [comment]
Closing this issue as it should be resolved in the latest commit

**Comment by agibalov** [comment]
@SAPessi I've just upgraded to 0.9 and removed all the custom code I had to write to make Spring MVC URL builder functionality work in 0.8. Thanks!
