### ISSUE TITLE
[Question] shade plugin vs combined jar

### ISSUE THREAD

**Issue by JonasJurczok** [awslabs/aws-serverless-java-container#85]
Hi,
I just started experimenting with Lambda and was wondering why everyone is using the shade plugin for assembling the final jar. I'm asking because the [best practices](http://docs.aws.amazon.com/lambda/latest/dg/best-practices.html) state that you should create a zip file with a lib folder in it (bullet point 6).

Is there a specific reasoning for not doing this? Or am I just missing a point? :)

Thanks and happy holidays!

**Comment by SAPessi** [comment]
Hey @JonasJurczok, a jar file is not that different from a zip. The reason why I used the maven shade plugin is that it makes it easier to automate packaging and deployments. Instead of creating a custom script to package the zip file, I can just run mvn package from my build process.

**Comment by JonasJurczok** [comment]
The difference is in the way dependencies are packed (extracted, pure
classes vs complete jars in a lib folder). And according to the docs the
latter one is better. That's why I asked :)

And yes I see the packaging aspect, but you can also achieve this with
other plugins (even the default ones)

Am 22.12.2017 19:17 schrieb "Stefano Buliani" <notifications@github.com>:

**Comment by SAPessi** [comment]
I think the difference may be more around jar size than anything else - makes cold starts faster because the code file to download is smaller. In the samples, I use the shade plugin for the sake of simplicity. Have you tried with other plugins? Something I should consider for the samples?

**Comment by JonasJurczok** [comment]
I was hoping you could tell me :D I just started with this and was confused about the difference between best practices and what everyone is doing. It feels like everyone is just copying the one example code snippet that is done with the shade plugin (for the sake of simplicity) but then no one is changing this anymore for the remainder of the project :D

**Comment by SAPessi** [comment]
Closing this one.
