### ISSUE TITLE
Duplicate values in the AwsProxyHttpServletRequest.getParameterMap()

### ISSUE THREAD

**Issue by avinashbitra** [awslabs/aws-serverless-java-container#86]
<img width="515" alt="screen shot 2017-12-30 at 12 42 12 pm" src="https://user-images.githubusercontent.com/5384557/34456554-edb998b2-ed5e-11e7-92c7-aff9924a3c73.png">

File: AwsProxyHttpServletRequest

 @Override
 public Map<String, String[]> getParameterMap() {
        Map<String, String[]> output = new HashMap<>();
        Map<String, List<String>> params = urlEncodedFormParameters 
.....
                if (params.containsKey(entry.getKey())) {
                    params.get(entry.getKey()).add(entry.getValue());
                } 
.....

urlEncodedFormParameters are initialized in the constructor and getParameterMap whenever invoked keeps adding to the same Map which ends up in having duplicate values.

Map<String, List<String>> params = this.getFormUrlEncodedParametersMap();
should reset the params map.

**Comment by SAPessi** [comment]
Hey @avinashbitra, can you share what the original request you sent looks like?

**Comment by avinashbitra** [comment]
its just a regular http request GET request with query parameters
http://hostname/api?foo=bar&academicYear=2018

**Comment by avinashbitra** [comment]
@SAPessi issue here is inside the spring framework while using spring rest repositories and making a http get request with query parameters, framework is trying to map the request parameters to method parameters.

While framework is trying to map the parameters, it makes multiple request.getParameterMap() invocations and because of the above code we are seeing duplicate values for a parameter.

**Comment by avinashbitra** [comment]
@SAPessi Is there any update on this.

**Comment by SAPessi** [comment]
Hey @avinashbitra, I'll try to get this fixed for the next release of the framework. I'm at home on Paternity leave for the next 2 weeks.

**Comment by avinashbitra** [comment]
Thanks @SAPessi

**Comment by SAPessi** [comment]
The latest commit addresses this issue. I'm closing this for the time being.
