### ISSUE TITLE
@Async support for Spring Boot on AWS Lambda

### ISSUE THREAD

**Issue by davidbellem** [awslabs/aws-serverless-java-container#87]
I wanted to add asynchronous processing to my spring boot app on AWS Lambda. 

The obvious way to do it (spring standard @async as described here https://spring.io/guides/gs/async-method/) did not work. It looks like the Lambda function is stopped as soon as a response is returned and does not even go into the @Async method. Without the Async annotation it works as expected.

Is there a way to make this work?

**Comment by SAPessi** [comment]
Hey @davidbellem, there isn't a way to make this work. Lambda will freeze your container as soon as the handler method returns. At the moment, with Lambda and API Gateway you can only support synchronous request/response patterns. 

What are you trying to achieve? If this is a process that just needs to run in the background to complete a task and no information is returned in the response, consider moving the business logic to a separate Lambda function and [invoke that second function asynchronously](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html).

**Comment by davidbellem** [comment]
I have a very strict timelimit on how fast the lambda function needs to return a result (3 seconds) but I need to make some http calls that all together take up to 10 seconds. I have a way to return the result by calling an external url. (Btw: This is for a slackbot in case you were wondering). Just that I make sure I understand you correctly: You are suggesting to create a second lambda function that I invoke using the AWS SDK, specifically com.amazonaws.services.lambda.invoke?

**Comment by davidbellem** [comment]
I forgot to mention: Thanks for the fast response!

**Comment by SAPessi** [comment]
Understood.

Lambda simply waits for the handler to return, I often use an ExecutorService to complete multiple tasks at the same time and have the main thread (the handler one) wait for it.

In your case, since your code needs to run for longer than the handler itself, you are better off moving it to a separate function.

**Comment by SAPessi** [comment]
Closing this issue for now. If anything else comes up, feel free to re-open.

**Comment by sharipsg** [comment]
@sapessi Is `@Async` supported in the latest version?
