### ISSUE TITLE
Activate Spring profile support for SpringBootLambdaContainerHandler

### ISSUE THREAD

**Issue by adsil2** [awslabs/aws-serverless-java-container#88]
I have integrated my Spring boot application into the lambda runtime using this library.  How do I support multiple profiles of runtime execution. I know this is possible in the SpringLambdaContainerHandler:

   SpringLambdaContainerHandler.getAwsProxyHandler().activateSpringProfiles("dev");

Here is example of my code:
```
public class LambdaHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {

    private SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    private Logger log = LoggerFactory.getLogger(LambdaHandler.class);

    public LambdaHandler() throws Exception {

        long milis = System.currentTimeMillis();
        handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(TestApplication.class);
        log.info("Loading time: " + (System.currentTimeMillis() - milis));
    }

    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        log.info("*************** Handling REQUEST -LAMBDA  *********** received: " + awsProxyRequest.toString());
        log.info("*************** Handling REQUEST -LAMBDA  ***********  context: " + context.toString());
        log.info("*************** Handling REQUEST -LAMBDA  *********** endpoint path: " + awsProxyRequest.getPath());
        log.info("*************** Handling REQUEST -LAMBDA  *********** endpoint method : " + awsProxyRequest.getHttpMethod());
        log.info("*************** Handling REQUEST -LAMBDA  *********** endpoint paremeters: " + awsProxyRequest.getQueryStringParameters());
        log.info("*************** Handling REQUEST -LAMBDA  *********** endpoint resource: " + awsProxyRequest.getResource());
        return handler.proxy(awsProxyRequest, context);
    }


}
```

**Comment by SAPessi** [comment]
I'll look into this. Let me flag it as an enhancement request.

**Comment by adsil2** [comment]
Thank you very much!

**Comment by SAPessi** [comment]
Quick question. Have you tried setting the active profile directly in your application?

```java
@Autowired
private ConfigurableEnvironment env;
...
env.setActiveProfiles("someProfile");
```

**Comment by adsil2** [comment]
No . Let me try and get back to you shortly.

**Comment by SAPessi** [comment]
Hey @adsil2, any update on this?

**Comment by adsil2** [comment]
Hi @SAPessi -- Is it possible to autowire this in my LambdaHandler class? (see above) I can get stage from APIGateway stage variable and then call  the above?

**Comment by SAPessi** [comment]
Not sure Spring will autowire something from the handler class. I have not tried. You can get the stage value any time by extracting the api gateway context from the request - take a look at the sample here: https://github.com/awslabs/aws-serverless-java-container/wiki#security-and-api-gateway-context

**Comment by adsil2** [comment]
Once I get the stage in the LambdaHandler how do I get it into the ConfigurableEnvironment instance, since it cannot be autowired -i.e. it is running outside Spring. Do you see what I mean?

**Comment by SAPessi** [comment]
Hey @adsil2, in the latest commit I've added an `activateSpringProfiles(String... profiles)` method to the `SpringBootLambdaContainerHandler` object. When you call this method, the system will flag the application for re-initialization and set the `spring.profiles.active` property accordingly.

**Comment by adsil2** [comment]
Thanks @SAPessi  I will give it a run and let you know.

**Comment by SAPessi** [comment]
Great. Keep in mind that this is not published yet. It's in the `servlet-improvements` branch of the GitHub repo. As soon as the last build completes I'll merge into master. The official 0.9 release should go out next week.

**Comment by adsil2** [comment]
@SAPessi I tested this and it looks great!
