### ISSUE TITLE
Preserve unknown properties from HTTP messages

### ISSUE THREAD

**Issue by cslee00** [awslabs/aws-serverless-java-container#93]
Various domain classes use `@JsonIgnoreProperties(ignoreUnknown=true)`, allowing the container to continue to function when AWS adds additional properties to messages (they document that this is a possibility).

Unfortunately those properties are, well... ignored.  No way to see what the original message was.

Perhaps grab any unknown properties into a map (example below).  Small risk here that folks will actually use this map to retrieve values, which will then break when the container adds support for those properties.  Mitigated by documentation & naming (`unknownProperties.get("somePropertyName")` smells funny).

```    @JsonAnyGetter
    public Map<String, String> getUnknownProperties() {
        return this.unknownProperties;
    }

    @JsonAnySetter
    public void setUnknownProperty(String name, String value) {
        this.unknownProperties.put(name, value);
    }
    ```

**Comment by SAPessi** [comment]
That's exactly why we added the ignore properties statement. We need applications to keep working even when the event document changes. We try to keep up as much as possible with the services and I'd rather add native support for new features quickly when notified (via an issue or what's new post) than introduce something that may become confusing later on.
