### ISSUE TITLE
Provide a mechanism to log *raw* requests & responses

### ISSUE THREAD

**Issue by cslee00** [awslabs/aws-serverless-java-container#94]
In support of debugging would be great to have a way to see the raw request/response JSON at container ingress/egress points.

Only when debugging turned on to avoid unnecessary overhead.

**Comment by SAPessi** [comment]
I would rather not do this. Requests and responses may contain confidential data that should never go in a log. I want to avoid blindly logging it when you set the level to debug to look at a different issue. You can log the data yourself directly from the handler.
